v8toolkit: testing::Matcher< T > Class Template Reference
testing::Matcher< T > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
Matcher ()
Matcher (const MatcherInterface< T > *impl)
Matcher (T value)
bool MatchAndExplain (T x, MatchResultListener *listener) const
bool Matches (T x) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
void ExplainMatchResultTo (T x,::std::ostream *os) const
const MatcherDescriberInterface * GetDescriber () const
Detailed Description
template<typename T>
class testing::Matcher< T >
Definition at line 319 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename T> testing::Matcher< T >::Matcher () inline explicit
Definition at line 324 of file gmock-matchers.h.
template<typename T> testing::Matcher< T >::Matcher (const MatcherInterface< T > * impl) inline explicit
Definition at line 327 of file gmock-matchers.h.
template<typename T> testing::Matcher< T >::Matcher (T value)
Definition at line 3747 of file gmock-matchers.h.
References testing::Eq().
Member Function Documentation
template<typename T> bool testing::internal::MatcherBase< T >::MatchAndExplain (T x, MatchResultListener * listener) const inline inherited
Definition at line 256 of file gmock-matchers.h.
Referenced by testing::internal::MatchPrintAndExplain().
template<typename T> bool testing::internal::MatcherBase< T >::Matches (T x) const inline inherited
Definition at line 261 of file gmock-matchers.h.
Referenced by testing::internal::MatchPrintAndExplain(), and TEST().
template<typename T> void testing::internal::MatcherBase< T >::DescribeTo (::std::ostream * os) const inline inherited
Definition at line 267 of file gmock-matchers.h.
Referenced by testing::internal::PredicateFormatterFromMatcher< M >::operator()().
template<typename T> void testing::internal::MatcherBase< T >::DescribeNegationTo (::std::ostream * os) const inline inherited
Definition at line 270 of file gmock-matchers.h.
template<typename T> void testing::internal::MatcherBase< T >::ExplainMatchResultTo (T x, ::std::ostream * os) const inline inherited
Definition at line 275 of file gmock-matchers.h.
template<typename T> const MatcherDescriberInterface* testing::internal::MatcherBase< T >::GetDescriber () const inline inherited
Definition at line 283 of file gmock-matchers.h.
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-matchers.h