v8toolkit: testing::Action< F > Class Template Reference
testing::Action< F > Class Template Reference
#include <gmock-actions.h>
Public Types
typedef internal::Function< F >::Result Result
typedef internal::Function< F >::ArgumentTuple ArgumentTuple
Public Member Functions
Action ()
Action (ActionInterface< F > *impl)
Action (const Action &action)
template<typename Func >
Action (const Action< Func > &action)
bool IsDoDefault () const
Result Perform (const ArgumentTuple &args) const
template<typename From >
Action (const Action< From > &from)
Friends
template<typename F1 , typename F2 >
class internal::ActionAdaptor
Detailed Description
template<typename F>
class testing::Action< F >
Definition at line 355 of file gmock-actions.h.
Member Typedef Documentation
template<typename F> typedef internal::Function<F>::Result testing::Action< F >::Result
Definition at line 357 of file gmock-actions.h.
template<typename F> typedef internal::Function<F>::ArgumentTuple testing::Action< F >::ArgumentTuple
Definition at line 358 of file gmock-actions.h.
Constructor & Destructor Documentation
template<typename F> testing::Action< F >::Action () inline
Definition at line 362 of file gmock-actions.h.
template<typename F> testing::Action< F >::Action (ActionInterface< F > * impl) inline explicit
Definition at line 366 of file gmock-actions.h.
template<typename F> testing::Action< F >::Action (const Action< F > & action) inline
Definition at line 369 of file gmock-actions.h.
template<typename F> template<typename Func > testing::Action< F >::Action (const Action< Func > & action) explicit
template<typename F> template<typename From > testing::Action< F >::Action (const Action< From > & from)
Definition at line 1054 of file gmock-actions.h.
Member Function Documentation
template<typename F> bool testing::Action< F >::IsDoDefault () const inline
Definition at line 379 of file gmock-actions.h.
Referenced by testing::internal::OnCallSpec< F >::WillByDefault().
template<typename F> Result testing::Action< F >::Perform (const ArgumentTuple & args) const inline
Definition at line 387 of file gmock-actions.h.
Referenced by testing::internal::ActionResultHolder< T >::PerformAction(), and testing::internal::ActionResultHolder< void >::PerformAction().
Friends And Related Function Documentation
template<typename F> template<typename F1 , typename F2 > friend class internal::ActionAdaptor friend
Definition at line 400 of file gmock-actions.h.
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-actions.h