v8toolkit: testing::internal::FloatingEqMatcher< FloatType > Class Template Reference
testing::internal::FloatingEqMatcher< FloatType > Class Template Reference
#include <gmock-matchers.h>
Classes
class Impl
Public Member Functions
FloatingEqMatcher (FloatType expected, bool nan_eq_nan)
FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error)
operator Matcher< FloatType > () const
operator Matcher< const FloatType & > () const
operator Matcher< FloatType & > () const
Detailed Description
template<typename FloatType>
class testing::internal::FloatingEqMatcher< FloatType >
Definition at line 1888 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan) inline
Definition at line 1896 of file gmock-matchers.h.
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::FloatingEqMatcher (FloatType expected, bool nan_eq_nan, FloatType max_abs_error) inline
Definition at line 1903 of file gmock-matchers.h.
References GTEST_CHECK_.
Member Function Documentation
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType > () const inline
Definition at line 2016 of file gmock-matchers.h.
References testing::MakeMatcher().
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & > () const inline
Definition at line 2021 of file gmock-matchers.h.
References testing::MakeMatcher().
template<typename FloatType> testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & > () const inline
Definition at line 2026 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, and testing::MakeMatcher().
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-matchers.h