v8toolkit: Annotations Class Reference
Annotations Class Reference
#include <annotations.h>
Public Member Functions
Annotations (const Decl *decl_to_check)
Annotations (const CXXMethodDecl *decl_to_check)
Annotations ()=default
const vector< string > get () const
std::vector< string > get_regex (const string &regex_string) const
bool has (const std::string &target) const
void merge (const Annotations &other)
Annotations (const CXXRecordDecl *decl_to_check)
Static Public Attributes
static map< const ClassTemplateDecl *, Annotations > annotations_for_class_templates
static map< const CXXRecordDecl *, Annotations > annotations_for_record_decls
static map< const CXXRecordDecl *, string > names_for_record_decls
Detailed Description
Definition at line 11 of file annotations.h.
Constructor & Destructor Documentation
Annotations::Annotations (const Decl * decl_to_check) inline
Definition at line 30 of file annotations.h.
Annotations::Annotations (const CXXMethodDecl * decl_to_check) inline
Definition at line 35 of file annotations.h.
References Annotations().
Annotations::Annotations () default
Referenced by Annotations().
Annotations::Annotations (const CXXRecordDecl * decl_to_check)
Definition at line 15 of file annotations.cpp.
References annotations_for_class_templates, get_canonical_name_for_decl(), and merge().
Member Function Documentation
const vector<string> Annotations::get () const inline
Definition at line 42 of file annotations.h.
Referenced by merge(), WrappedClass::should_be_wrapped(), WrappedClass::update_data(), and WrappedClass::WrappedClass().
std::vector<string> Annotations::get_regex (const string & regex_string) const inline
Definition at line 51 of file annotations.h.
Referenced by ClassFunction::ClassFunction(), ClassHandler::run(), and WrappedClass::WrappedClass().
bool Annotations::has (const std::string & target) const inline
Definition at line 67 of file annotations.h.
Referenced by DataMember::DataMember(), foreach_constructor(), get_method_param_qual_types(), WrappedClass::parse_all_methods(), ClassHandler::run(), WrappedClass::should_be_wrapped(), and WrappedClass::WrappedClass().
void Annotations::merge (const Annotations & other) inline
Definition at line 71 of file annotations.h.
References get().
Referenced by Annotations(), and WrappedClass::WrappedClass().
Member Data Documentation
map< const ClassTemplateDecl *, Annotations > Annotations::annotations_for_class_templates static
Definition at line 80 of file annotations.h.
Referenced by Annotations(), and ClassHandler::run().
map< const CXXRecordDecl *, Annotations > Annotations::annotations_for_record_decls static
Definition at line 83 of file annotations.h.
Referenced by ClassHandler::run().
map< const CXXRecordDecl *, string > Annotations::names_for_record_decls static
Definition at line 88 of file annotations.h.
Referenced by ClassHandler::run(), WrappedClass::update_data(), and WrappedClass::WrappedClass().
The documentation for this class was generated from the following files:
class_parser/annotations.h
class_parser/annotations.cpp