v8toolkit: ConstructorFunction Class Reference
ConstructorFunction Class Reference
#include <parsed_method.h>
Public Member Functions
ConstructorFunction (WrappedClass &wrapped_class, CXXConstructorDecl const *constructor_decl)
string generate_js_bindings ()
string generate_js_stub ()
string get_default_argument_tuple_string () const
string get_signature_string ()
bool compare_signatures (ClassFunction const &other)
string get_parameter_types_string () const
string get_return_and_class_and_parameter_types_string () const
string get_return_and_parameter_types_string () const
string get_js_input_parameter_string () const
Public Attributes
CXXConstructorDecl const *const constructor_decl
WrappedClass & wrapped_class
bool is_static
bool is_virtual
bool new_virtual
TypeInfo return_type
string return_type_comment
vector< ParameterInfo > parameters
CXXMethodDecl const * method_decl
string name
string js_name
CompilerInstance & compiler_instance
Annotations annotations
Detailed Description
Definition at line 138 of file parsed_method.h.
Constructor & Destructor Documentation
ConstructorFunction::ConstructorFunction (WrappedClass & wrapped_class, CXXConstructorDecl const * constructor_decl)
Definition at line 638 of file parsed_method.cpp.
References ClassFunction::compiler_instance, data_error(), ClassFunction::js_name, ClassFunction::name, WrappedClass::name_alias, and used_constructor_names.
Member Function Documentation
string ConstructorFunction::generate_js_bindings ()
Definition at line 677 of file parsed_method.cpp.
References ClassFunction::get_default_argument_tuple_string(), ClassFunction::get_parameter_types_string(), and ClassFunction::js_name.
string ConstructorFunction::generate_js_stub ()
Definition at line 751 of file parsed_method.cpp.
References ClassFunction::get_js_input_parameter_string(), and ClassFunction::parameters.
string ClassFunction::get_default_argument_tuple_string () const inherited
Definition at line 427 of file parsed_method.cpp.
References get_type_string(), and ClassFunction::parameters.
Referenced by MemberFunction::generate_js_bindings(), StaticFunction::generate_js_bindings(), and generate_js_bindings().
string ClassFunction::get_signature_string () inherited
Definition at line 602 of file parsed_method.cpp.
References ClassFunction::name, and ClassFunction::parameters.
bool ClassFunction::compare_signatures (ClassFunction const & other) inherited
string ClassFunction::get_parameter_types_string () const inherited
Definition at line 487 of file parsed_method.cpp.
References ClassFunction::parameters.
Referenced by generate_js_bindings(), ClassFunction::get_return_and_class_and_parameter_types_string(), and ClassFunction::get_return_and_parameter_types_string().
string ClassFunction::get_return_and_class_and_parameter_types_string () const inherited
Definition at line 463 of file parsed_method.cpp.
References ClassFunction::get_parameter_types_string(), ClassFunction::TypeInfo::name, ClassFunction::parameters, and ClassFunction::return_type.
Referenced by MemberFunction::generate_js_bindings().
string ClassFunction::get_return_and_parameter_types_string () const inherited
Definition at line 475 of file parsed_method.cpp.
References ClassFunction::get_parameter_types_string(), ClassFunction::TypeInfo::name, ClassFunction::parameters, and ClassFunction::return_type.
Referenced by StaticFunction::generate_js_bindings().
string ClassFunction::get_js_input_parameter_string () const inherited
Definition at line 501 of file parsed_method.cpp.
References ClassFunction::parameters.
Referenced by MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), and generate_js_stub().
Member Data Documentation
CXXConstructorDecl const* const ConstructorFunction::constructor_decl
Definition at line 146 of file parsed_method.h.
WrappedClass& ClassFunction::wrapped_class inherited
Definition at line 16 of file parsed_method.h.
Referenced by ClassFunction::ParameterInfo::ParameterInfo().
bool ClassFunction::is_static inherited
Definition at line 17 of file parsed_method.h.
bool ClassFunction::is_virtual inherited
Definition at line 18 of file parsed_method.h.
bool ClassFunction::new_virtual inherited
Definition at line 21 of file parsed_method.h.
TypeInfo ClassFunction::return_type inherited
Definition at line 87 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), ClassFunction::get_return_and_class_and_parameter_types_string(), and ClassFunction::get_return_and_parameter_types_string().
string ClassFunction::return_type_comment inherited
Definition at line 88 of file parsed_method.h.
vector<ParameterInfo> ClassFunction::parameters inherited
Definition at line 89 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), generate_bidirectional_classes(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), generate_js_stub(), ClassFunction::get_default_argument_tuple_string(), ClassFunction::get_js_input_parameter_string(), ClassFunction::get_parameter_types_string(), ClassFunction::get_return_and_class_and_parameter_types_string(), ClassFunction::get_return_and_parameter_types_string(), and ClassFunction::get_signature_string().
CXXMethodDecl const* ClassFunction::method_decl inherited
Definition at line 90 of file parsed_method.h.
Referenced by MemberFunction::generate_js_bindings().
string ClassFunction::name inherited
Definition at line 93 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), ConstructorFunction(), MemberFunction::generate_js_bindings(), StaticFunction::generate_js_bindings(), and ClassFunction::get_signature_string().
string ClassFunction::js_name inherited
Definition at line 96 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), ConstructorFunction(), MemberFunction::generate_js_bindings(), StaticFunction::generate_js_bindings(), generate_js_bindings(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), MemberFunction::MemberFunction(), and StaticFunction::StaticFunction().
CompilerInstance& ClassFunction::compiler_instance inherited
Definition at line 97 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), and ConstructorFunction().
Annotations ClassFunction::annotations inherited
Definition at line 98 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction().
The documentation for this class was generated from the following files:
class_parser/parsed_method.h
class_parser/parsed_method.cpp