v8toolkit: Interface Class Reference
Interface Class Reference abstract
#include <gmock_link_test.h>
Public Member Functions
virtual ~Interface ()
virtual void VoidFromString (char *str)=0
virtual char * StringFromString (char *str)=0
virtual int IntFromString (char *str)=0
virtual int & IntRefFromString (char *str)=0
virtual void VoidFromFunc (void(*func)(char *str))=0
virtual void VoidFromIntRef (int &n)=0
virtual void VoidFromFloat (float n)=0
virtual void VoidFromDouble (double n)=0
virtual void VoidFromVector (const std::vector< int > &v)=0
Detailed Description
Definition at line 191 of file gmock_link_test.h.
Constructor & Destructor Documentation
virtual Interface::~Interface () inline virtual
Definition at line 193 of file gmock_link_test.h.
References IntFromString(), IntRefFromString(), StringFromString(), VoidFromDouble(), VoidFromFloat(), VoidFromFunc(), VoidFromIntRef(), VoidFromString(), and VoidFromVector().
Member Function Documentation
virtual void Interface::VoidFromString (char * str) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual char* Interface::StringFromString (char * str) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual int Interface::IntFromString (char * str) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual int& Interface::IntRefFromString (char * str) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual void Interface::VoidFromFunc (void(*)(char *str) func) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual void Interface::VoidFromIntRef (int & n) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual void Interface::VoidFromFloat (float n) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual void Interface::VoidFromDouble (double n) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
virtual void Interface::VoidFromVector (const std::vector< int > & v) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().
The documentation for this class was generated from the following file:
test/googletest/googlemock/test/gmock_link_test.h