v8toolkit: v8toolkit::WebsocketChannel Class Reference
v8toolkit::WebsocketChannel Class Reference
#include <debugger.h>
Public Member Functions
WebsocketChannel (v8toolkit::DebugContext &debug_context, short port)
virtual ~WebsocketChannel ()
void wait_for_connection (std::chrono::duration< float > sleep_between_polls=std::chrono::duration< float >(0.1f))
void poll ()
void poll_one ()
void poll_until_idle (float idle_time=1.0f)
void run_one ()
void send_message (void *data, size_t length)
float seconds_since_message_received ()
float seconds_since_message_sent ()
float seconds_since_message ()
Detailed Description
Inspector types:
v8_inspector::V8Inspector::Channel
Interface: sendResponse, sendNotification, flushProtocol
basically takes a string and sends it out
v8_inspector::V8InspectorClient
has a "channel"
has an V8Inspector
creates a V8InspectorSesssion when an inspector is "connected" to a channel
V8InspectorSession:
Does the "main work"
Received messages are sent to session::dispatchProtocolMessage
v8_inspector::V8Inspector
associated and 'connected' to a v8::Context
Definition at line 166 of file debugger.h.
Constructor & Destructor Documentation
v8toolkit::WebsocketChannel::WebsocketChannel (v8toolkit::DebugContext & debug_context, short port)
Definition at line 83 of file debugger.cpp.
References v8toolkit::bind(), v8toolkit::Context::get_global_context(), v8toolkit::Context::get_isolate(), v8toolkit::DebugContext::get_session(), GLOBAL_CONTEXT_SCOPED_RUN, v8toolkit::DebugContext::paused, v8toolkit::DebugContext::reset_session(), and send_message().
v8toolkit::WebsocketChannel::~WebsocketChannel () virtual
Definition at line 81 of file debugger.cpp.
Member Function Documentation
void v8toolkit::WebsocketChannel::wait_for_connection (std::chrono::duration< float > sleep_between_polls = std::chrono::duration<float>(0.1f))
Definition at line 247 of file debugger.cpp.
References poll_one().
void v8toolkit::WebsocketChannel::poll ()
Definition at line 230 of file debugger.cpp.
Referenced by poll_until_idle().
void v8toolkit::WebsocketChannel::poll_one ()
runs a single request if available, otherwise returns immediately
Definition at line 234 of file debugger.cpp.
Referenced by wait_for_connection().
void v8toolkit::WebsocketChannel::poll_until_idle (float idle_time = 1.0f)
polls until connection has been idle for specified amount of time
Parameters
idle_time amount of time between messages to wait until returning
Definition at line 238 of file debugger.cpp.
References poll(), and seconds_since_message().
void v8toolkit::WebsocketChannel::run_one ()
blocks until a request is handled
Definition at line 226 of file debugger.cpp.
void v8toolkit::WebsocketChannel::send_message (void * data, size_t length)
Definition at line 215 of file debugger.cpp.
Referenced by WebsocketChannel().
float v8toolkit::WebsocketChannel::seconds_since_message_received ()
How long ago was most recent message received
Returns
number of seconds
Definition at line 294 of file debugger.cpp.
float v8toolkit::WebsocketChannel::seconds_since_message_sent ()
How long ago was most recent message sent
Returns
number of sceonds
Definition at line 299 of file debugger.cpp.
float v8toolkit::WebsocketChannel::seconds_since_message ()
how long ago was a message either sent or received
Returns
number of seconds
Definition at line 306 of file debugger.cpp.
Referenced by poll_until_idle().
The documentation for this class was generated from the following files:
include/debugger.h
src/debugger.cpp