v8toolkit: testing::internal::UnitTestImpl Class Reference
testing::internal::UnitTestImpl Class Reference
#include <gtest-internal-inl.h>
Public Types
enum ReactionToSharding { HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL }
Public Member Functions
UnitTestImpl (UnitTest *parent)
virtual ~UnitTestImpl ()
TestPartResultReporterInterface * GetGlobalTestPartResultReporter ()
void SetGlobalTestPartResultReporter (TestPartResultReporterInterface *reporter)
TestPartResultReporterInterface * GetTestPartResultReporterForCurrentThread ()
void SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface *reporter)
int successful_test_case_count () const
int failed_test_case_count () const
int total_test_case_count () const
int test_case_to_run_count () const
int successful_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int total_test_count () const
int test_to_run_count () const
TimeInMillis start_timestamp () const
TimeInMillis elapsed_time () const
bool Passed () const
bool Failed () const
const TestCase * GetTestCase (int i) const
TestCase * GetMutableTestCase (int i)
TestEventListeners * listeners ()
TestResult * current_test_result ()
const TestResult * ad_hoc_test_result () const
void set_os_stack_trace_getter (OsStackTraceGetterInterface *getter)
OsStackTraceGetterInterface * os_stack_trace_getter ()
std::string CurrentOsStackTraceExceptTop (int skip_count) GTEST_NO_INLINE_
TestCase * GetTestCase (const char *test_case_name, const char *type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
void AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo *test_info)
void set_current_test_case (TestCase *a_current_test_case)
void set_current_test_info (TestInfo *a_current_test_info)
void RegisterParameterizedTests ()
bool RunAllTests ()
void ClearNonAdHocTestResult ()
void ClearAdHocTestResult ()
void RecordProperty (const TestProperty &test_property)
int FilterTests (ReactionToSharding shard_tests)
void ListTestsMatchingFilter ()
const TestCase * current_test_case () const
TestInfo * current_test_info ()
const TestInfo * current_test_info () const
std::vector< Environment * > & environments ()
std::vector< TraceInfo > & gtest_trace_stack ()
const std::vector< TraceInfo > & gtest_trace_stack () const
void ConfigureXmlOutput ()
void PostFlagParsingInit ()
int random_seed () const
internal::Random * random ()
void ShuffleTests ()
void UnshuffleTests ()
bool catch_exceptions () const
Friends
class ::testing::UnitTest
Detailed Description
Definition at line 499 of file gtest-internal-inl.h.
Member Enumeration Documentation
enum testing::internal::UnitTestImpl::ReactionToSharding
Enumerator
HONOR_SHARDING_PROTOCOL
IGNORE_SHARDING_PROTOCOL
Definition at line 717 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::UnitTestImpl::UnitTestImpl (UnitTest * parent) explicit
virtual testing::internal::UnitTestImpl::~UnitTestImpl () virtual
Member Function Documentation
TestPartResultReporterInterface* testing::internal::UnitTestImpl::GetGlobalTestPartResultReporter ()
void testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter (TestPartResultReporterInterface * reporter)
TestPartResultReporterInterface* testing::internal::UnitTestImpl::GetTestPartResultReporterForCurrentThread ()
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
int testing::internal::UnitTestImpl::successful_test_case_count () const
int testing::internal::UnitTestImpl::failed_test_case_count () const
int testing::internal::UnitTestImpl::total_test_case_count () const
int testing::internal::UnitTestImpl::test_case_to_run_count () const
int testing::internal::UnitTestImpl::successful_test_count () const
int testing::internal::UnitTestImpl::failed_test_count () const
int testing::internal::UnitTestImpl::reportable_disabled_test_count () const
int testing::internal::UnitTestImpl::disabled_test_count () const
int testing::internal::UnitTestImpl::reportable_test_count () const
int testing::internal::UnitTestImpl::total_test_count () const
int testing::internal::UnitTestImpl::test_to_run_count () const
TimeInMillis testing::internal::UnitTestImpl::start_timestamp () const inline
Definition at line 561 of file gtest-internal-inl.h.
TimeInMillis testing::internal::UnitTestImpl::elapsed_time () const inline
Definition at line 564 of file gtest-internal-inl.h.
bool testing::internal::UnitTestImpl::Passed () const inline
Definition at line 567 of file gtest-internal-inl.h.
bool testing::internal::UnitTestImpl::Failed () const inline
Definition at line 571 of file gtest-internal-inl.h.
const TestCase* testing::internal::UnitTestImpl::GetTestCase (int i) const inline
Definition at line 577 of file gtest-internal-inl.h.
References testing::internal::GetElementOr().
TestCase* testing::internal::UnitTestImpl::GetMutableTestCase (int i) inline
Definition at line 584 of file gtest-internal-inl.h.
References testing::internal::GetElementOr().
TestEventListeners* testing::internal::UnitTestImpl::listeners () inline
Definition at line 590 of file gtest-internal-inl.h.
TestResult* testing::internal::UnitTestImpl::current_test_result ()
const TestResult* testing::internal::UnitTestImpl::ad_hoc_test_result () const inline
Definition at line 597 of file gtest-internal-inl.h.
References GTEST_NO_INLINE_.
void testing::internal::UnitTestImpl::set_os_stack_trace_getter (OsStackTraceGetterInterface * getter)
OsStackTraceGetterInterface* testing::internal::UnitTestImpl::os_stack_trace_getter ()
std::string testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop (int skip_count)
TestCase* testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
void testing::internal::UnitTestImpl::AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 645 of file gtest-internal-inl.h.
References testing::internal::FilePath::GetCurrentDir(), GTEST_CHECK_, testing::TestInfo::test_case_name(), and testing::TestInfo::type_param().
void testing::internal::UnitTestImpl::set_current_test_case (TestCase * a_current_test_case) inline
Definition at line 676 of file gtest-internal-inl.h.
void testing::internal::UnitTestImpl::set_current_test_info (TestInfo * a_current_test_info) inline
Definition at line 683 of file gtest-internal-inl.h.
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
bool testing::internal::UnitTestImpl::RunAllTests ()
void testing::internal::UnitTestImpl::ClearNonAdHocTestResult () inline
Definition at line 702 of file gtest-internal-inl.h.
References testing::internal::ForEach().
void testing::internal::UnitTestImpl::ClearAdHocTestResult () inline
Definition at line 707 of file gtest-internal-inl.h.
void testing::internal::UnitTestImpl::RecordProperty (const TestProperty & test_property)
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
const TestCase* testing::internal::UnitTestImpl::current_test_case () const inline
Definition at line 733 of file gtest-internal-inl.h.
TestInfo* testing::internal::UnitTestImpl::current_test_info () inline
Definition at line 734 of file gtest-internal-inl.h.
const TestInfo* testing::internal::UnitTestImpl::current_test_info () const inline
Definition at line 735 of file gtest-internal-inl.h.
std::vector<Environment*>& testing::internal::UnitTestImpl::environments () inline
Definition at line 739 of file gtest-internal-inl.h.
std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () inline
Definition at line 742 of file gtest-internal-inl.h.
const std::vector<TraceInfo>& testing::internal::UnitTestImpl::gtest_trace_stack () const inline
Definition at line 745 of file gtest-internal-inl.h.
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
int testing::internal::UnitTestImpl::random_seed () const inline
Definition at line 789 of file gtest-internal-inl.h.
internal::Random* testing::internal::UnitTestImpl::random () inline
Definition at line 792 of file gtest-internal-inl.h.
void testing::internal::UnitTestImpl::ShuffleTests ()
void testing::internal::UnitTestImpl::UnshuffleTests ()
bool testing::internal::UnitTestImpl::catch_exceptions () const inline
Definition at line 803 of file gtest-internal-inl.h.
Friends And Related Function Documentation
friend class ::testing::UnitTest friend
Definition at line 806 of file gtest-internal-inl.h.
The documentation for this class was generated from the following file:
test/googletest/googletest/src/gtest-internal-inl.h