v8toolkit: func::function< Result(Arguments...)> Class Template Reference
func::function< Result(Arguments...)> Class Template Reference
#include <stdfunctionreplacement.h>
Public Types
typedef Result(* Empty_Function_Type) (Arguments...)
typedef Result result_type
Public Member Functions
function () FUNC_NOEXCEPT
function (std::nullptr_t) FUNC_NOEXCEPT
function (function &&other) FUNC_NOEXCEPT
function (const function &other)
template<typename T >
function (T functor, typename std::enable_if< detail::is_valid_function_argument< T, Result(Arguments...)>::value, detail::empty_struct >::type=detail::empty_struct()) FUNC_TEMPLATE_NOEXCEPT(T
template<typename T , typename Allocator >
void initialize (T functor, Allocator &&allocator)
void initialize_empty () FUNC_NOEXCEPT
Public Attributes
Result(* call)(const detail::functor_padding &, Arguments...)
Detailed Description
template<typename Result, typename... Arguments>
class func::function< Result(Arguments...)>
Definition at line 371 of file stdfunctionreplacement.h.
Member Typedef Documentation
template<typename Result , typename... Arguments> typedef Result(* func::function< Result(Arguments...)>::Empty_Function_Type) (Arguments...)
Definition at line 543 of file stdfunctionreplacement.h.
typedef Result func::detail::typedeffer< Result,... >::result_type inherited
Definition at line 353 of file stdfunctionreplacement.h.
Constructor & Destructor Documentation
template<typename Result , typename... Arguments> func::function< Result(Arguments...)>::function () inline
Definition at line 375 of file stdfunctionreplacement.h.
template<typename Result , typename... Arguments> func::function< Result(Arguments...)>::function (std::nullptr_t) inline
Definition at line 379 of file stdfunctionreplacement.h.
template<typename Result , typename... Arguments> func::function< Result(Arguments...)>::function (function< Result(Arguments...)> && other) inline
Definition at line 383 of file stdfunctionreplacement.h.
References func::swap().
template<typename Result , typename... Arguments> func::function< Result(Arguments...)>::function (const function< Result(Arguments...)> & other) inline
Definition at line 388 of file stdfunctionreplacement.h.
References func::detail::function_manager::call_copy_functor_only, func::detail::function_manager::call_move_and_destroy, func::detail::empty_call(), FUNC_FORWARD, FUNC_MOVE, FUNC_NOEXCEPT, FUNC_TEMPLATE_NOEXCEPT, func::detail::is_null(), func::detail::manager_storage_type::manager, func::swap(), and func::detail::to_functor().
template<typename Result , typename... Arguments> template<typename T > func::function< Result(Arguments...)>::function (T functor, typename std::enable_if< detail::is_valid_function_argument< T, Result(Arguments...)>::value, detail::empty_struct >::type = detail::empty_struct())
Member Function Documentation
template<typename Result , typename... Arguments> template<typename T , typename Allocator > void func::function< Result(Arguments...)>::initialize (T functor, Allocator && allocator) inline
Definition at line 536 of file stdfunctionreplacement.h.
References FUNC_FORWARD, and func::detail::function_manager_inplace_specialization< T, Allocator, Enable >::store_functor().
template<typename Result , typename... Arguments> void func::function< Result(Arguments...)>::initialize_empty () inline
Definition at line 544 of file stdfunctionreplacement.h.
References func::detail::empty_call(), and func::detail::function_manager_inplace_specialization< T, Allocator, Enable >::store_functor().
Member Data Documentation
template<typename Result , typename... Arguments> Result(* func::function< Result(Arguments...)>::call) (const detail::functor_padding &, Arguments...)
Definition at line 533 of file stdfunctionreplacement.h.
The documentation for this class was generated from the following file:
include/stdfunctionreplacement.h