v8toolkit: WrappedClassDerived Class Reference
WrappedClassDerived Class Reference
Public Types
enum EnumClass { EnumClass::A, EnumClass::B, EnumClass::C, EnumClass::D }
Public Member Functions
WrappedClassDerived ()
void method_with_no_constructor_on_class (int, int const &=5, char const *="five", WrappedClassDerived const &s={})
int simple_member_function (char const *some_string="asdf")
void std_function_default_parameter (std::function< void()> some_function=std::function< void()>())
template<class A = int, int b = 4>
void templated_method ()
void after_templated_method ()
void parse_all_methods ()
set< unique_ptr< MemberFunction > > const & get_member_functions ()
set< unique_ptr< StaticFunction > > const & get_static_functions ()
set< unique_ptr< DataMember > > & get_members ()
set< unique_ptr< ConstructorFunction > > const & get_constructors ()
void set_error (string const &error_message)
std::string get_short_name () const
bool has_static_method ()
bool is_template_specialization ()
void foreach_inheritance_level (function< void(WrappedClass &)> callback)
void add_member_name (string const &name)
void add_static_name (string const &name)
void update_data ()
std::string make_sfinae_to_match_wrapped_class () const
bool should_be_wrapped () const
bool ready_for_wrapping (set< WrappedClass * > dumped_classes) const
std::set< string > get_base_type_includes ()
std::set< string > get_derived_type_includes ()
std::string generate_js_stub ()
std::string get_derived_classes_string (int level=0, const std::string indent="")
std::string get_base_class_string ()
std::string get_bindings ()
bool found_method_means_wrapped ()
int takes_int_5 (int x)
int takes_const_int_6 (int const x) const
void default_parameters (int j=1, char const *s="asdf", vector< std::string > &&={}, CopyableWrappedClass={}, CopyableWrappedClass &&={}, CopyableWrappedClass *=nullptr)
Static Public Member Functions
static void static_method_with_no_constructor_on_class (int, int=5, char const *="five")
static V8TOOLKIT_EXTEND_WRAPPER void extend_wrapper ()
static V8TOOLKIT_CUSTOM_EXTENSION void custom_extension ()
static std::string simple_static_function (double some_double)
static void insert_wrapped_class (WrappedClass *wrapped_class)
static WrappedClass * get_if_exists (const CXXRecordDecl *decl)
static WrappedClass & get_or_insert_wrapped_class (const CXXRecordDecl *decl, CompilerInstance &compiler_instance, FOUND_METHOD found_method)
static std::string static_method ()
Public Attributes
double double_member_readwrite2
double double_member_readwrite
V8TOOLKIT_READONLY double double_member_readonly1
double const double_member_readonly2
std::vector< std::string > vector_of_ints
std::vector< WrappedClass * > vector_of_selfs
CXXRecordDecl const * decl = nullptr
CXXRecordDecl const * instantiation_pattern = nullptr
string class_name
string name_alias
this is the possibly shortened javascript name of the type - not necessarily valid in generated c++
set< string > include_files
int declaration_count = 3
string my_header_filename = ""
set< string > used_member_names
set< string > used_static_names
vector< string > data_errors
set< WrappedClass * > derived_types
set< WrappedClass * > base_types
tracked base_types - if it's more than one, that's a data error because javascript only allows one
set< string > wrapper_extension_methods
set< string > wrapper_custom_extensions
CompilerInstance & compiler_instance
string my_include
bool done = false
bool valid = false
Annotations annotations
bool dumped = false
set< WrappedClass * > used_classes
FOUND_METHOD found_method
bool force_no_constructors = false
bool bidirectional = false
CXXConstructorDecl const * bidirectional_constructor = nullptr
int i = 5
int ci = 5
std::unique_ptr< float > upf = std::make_unique<float>(3.5)
std::unique_ptr< float > cupf = std::make_unique<float>(4.5)
std::string string = "string value"
bool default_parameters_called = false
CopyableWrappedClass copyable_wrapped_class
std::unique_ptr< WrappedClass > up_wrapped_class
Static Public Attributes
static vector< WrappedClass * > wrapped_classes
Detailed Description
Definition at line 81 of file sample.cpp.
Member Enumeration Documentation
enum WrappedClass::EnumClass strong inherited
Enumerator
A
B
C
D
Definition at line 72 of file sample.cpp.
Constructor & Destructor Documentation
WrappedClassDerived::WrappedClassDerived ()
Member Function Documentation
static void WrappedClassDerived::static_method_with_no_constructor_on_class (int , int = 5, char const * = "five") static
void WrappedClassDerived::method_with_no_constructor_on_class (int , int const & = 5, char const * = "five", WrappedClassDerived const & s = {})
static V8TOOLKIT_EXTEND_WRAPPER void WrappedClass::extend_wrapper () static inherited
static V8TOOLKIT_CUSTOM_EXTENSION void WrappedClass::custom_extension () static inherited
int WrappedClass::simple_member_function (char const * some_string = "asdf") inherited
static std::string WrappedClass::simple_static_function (double some_double) static inherited
void WrappedClass::std_function_default_parameter (std::function< void()> some_function = std::function< void()>()) inherited
template<class A = int, int b = 4> void WrappedClass::templated_method () inherited
void WrappedClass::after_templated_method () inherited
void WrappedClass::parse_all_methods () inherited
Builds data structures associated with the methods of this class
Definition at line 251 of file wrapped_class.cpp.
References WrappedClass::annotations, data_error(), WrappedClass::decl, EXPORT_ALL, EXPORT_EXCEPT, WrappedClass::force_no_constructors, get_export_type(), get_type_string(), Annotations::has(), WrappedClass::i, testing::internal::move(), print_logging, PRINT_SKIPPED_EXPORT_REASONS, V8TOOLKIT_CUSTOM_EXTENSION_STRING, V8TOOLKIT_DO_NOT_WRAP_CONSTRUCTORS_STRING, V8TOOLKIT_EXTEND_WRAPPER_STRING, WrappedClass::wrapper_custom_extensions, and WrappedClass::wrapper_extension_methods.
Referenced by WrappedClass::get_constructors(), WrappedClass::get_member_functions(), and WrappedClass::get_static_functions().
set< unique_ptr< MemberFunction > > const & WrappedClass::get_member_functions () inherited
Definition at line 239 of file wrapped_class.cpp.
References WrappedClass::parse_all_methods().
Referenced by WrappedClass::generate_js_stub(), and WrappedClass::get_bindings().
set< unique_ptr< StaticFunction > > const & WrappedClass::get_static_functions () inherited
Definition at line 245 of file wrapped_class.cpp.
References WrappedClass::parse_all_methods().
Referenced by WrappedClass::generate_js_stub(), and WrappedClass::get_bindings().
set< unique_ptr< DataMember > > & WrappedClass::get_members () inherited
Definition at line 456 of file wrapped_class.cpp.
References WrappedClass::decl, EXPORT_ALL, EXPORT_EXCEPT, WrappedClass::foreach_inheritance_level(), get_export_type(), and PRINT_SKIPPED_EXPORT_REASONS.
Referenced by WrappedClass::generate_js_stub().
set< unique_ptr< ConstructorFunction > > const & WrappedClass::get_constructors () inherited
Definition at line 233 of file wrapped_class.cpp.
References WrappedClass::parse_all_methods().
Referenced by WrappedClass::generate_js_stub(), and WrappedClass::get_bindings().
void WrappedClass::set_error (string const & error_message) inherited
Definition at line 729 of file wrapped_class.cpp.
References WrappedClass::data_errors, and WrappedClass::valid.
Referenced by WrappedClass::add_member_name(), WrappedClass::add_static_name(), and WrappedClass::WrappedClass().
std::string WrappedClass::get_short_name () const inline inherited
Definition at line 88 of file wrapped_class.h.
Referenced by ClassHandler::run().
bool WrappedClass::has_static_method () inline inherited
Definition at line 95 of file wrapped_class.h.
References WrappedClass::add_member_name(), WrappedClass::add_static_name(), WrappedClass::foreach_inheritance_level(), and WrappedClass::is_template_specialization().
Referenced by WrappedClass::get_bindings(), and ClassHandler::run().
bool WrappedClass::is_template_specialization () inherited
Returns
whether this type is a specialization of a template
Definition at line 779 of file wrapped_class.cpp.
References WrappedClass::decl.
Referenced by WrappedClass::has_static_method().
void WrappedClass::foreach_inheritance_level (function< void(WrappedClass &)> callback) inherited
Parameters
callback called on each parameterized type for this template specialization
Definition at line 442 of file wrapped_class.cpp.
References WrappedClass::base_types.
Referenced by WrappedClass::get_members(), and WrappedClass::has_static_method().
void WrappedClass::add_member_name (string const & name) inherited
Sets a member name as being in use and sets valid = false if it was already in use For member functions and data members (not constructors or static methods)
Parameters
name name to add
Definition at line 710 of file wrapped_class.cpp.
References WrappedClass::set_error(), and WrappedClass::used_member_names.
Referenced by DataMember::DataMember(), WrappedClass::has_static_method(), and MemberFunction::MemberFunction().
void WrappedClass::add_static_name (string const & name) inherited
Definition at line 718 of file wrapped_class.cpp.
References WrappedClass::set_error(), and WrappedClass::used_static_names.
Referenced by WrappedClass::has_static_method(), and StaticFunction::StaticFunction().
void WrappedClass::update_data () inline inherited
Definition at line 118 of file wrapped_class.h.
References WrappedClass::decl, Annotations::get(), and Annotations::names_for_record_decls.
std::string WrappedClass::make_sfinae_to_match_wrapped_class () const inline inherited
Definition at line 132 of file wrapped_class.h.
References FOUND_ANNOTATION, WrappedClass::generate_js_stub(), WrappedClass::get_base_type_includes(), WrappedClass::get_derived_type_includes(), WrappedClass::operator=(), WrappedClass::ready_for_wrapping(), WrappedClass::should_be_wrapped(), and WrappedClass::WrappedClass().
bool WrappedClass::should_be_wrapped () const inherited
Definition at line 547 of file wrapped_class.cpp.
References WrappedClass::annotations, WrappedClass::base_types, WrappedClass::class_name, data_error(), FOUND_ANNOTATION, FOUND_BASE_CLASS, FOUND_GENERATED, FOUND_INHERITANCE, WrappedClass::found_method, FOUND_UNSPECIFIED, Annotations::get(), Annotations::has(), join(), WrappedClass::name_alias, V8TOOLKIT_ALL_STRING, and V8TOOLKIT_NONE_STRING.
Referenced by WrappedClass::make_sfinae_to_match_wrapped_class(), and WrappedClass::ready_for_wrapping().
bool WrappedClass::ready_for_wrapping (set< WrappedClass * > dumped_classes) const inherited
Definition at line 617 of file wrapped_class.cpp.
References WrappedClass::base_types, WrappedClass::class_name, and WrappedClass::should_be_wrapped().
Referenced by WrappedClass::make_sfinae_to_match_wrapped_class().
std::set< string > WrappedClass::get_base_type_includes () inherited
Definition at line 737 of file wrapped_class.cpp.
References WrappedClass::base_types, WrappedClass::include_files, and WrappedClass::my_include.
Referenced by WrappedClass::make_sfinae_to_match_wrapped_class().
std::set< string > WrappedClass::get_derived_type_includes () inherited
Definition at line 757 of file wrapped_class.cpp.
References WrappedClass::derived_types, join(), WrappedClass::my_include, and WrappedClass::name_alias.
Referenced by WrappedClass::make_sfinae_to_match_wrapped_class().
std::string WrappedClass::generate_js_stub () inherited
Definition at line 501 of file wrapped_class.cpp.
References WrappedClass::base_types, WrappedClass::get_constructors(), WrappedClass::get_member_functions(), WrappedClass::get_members(), WrappedClass::get_static_functions(), and WrappedClass::name_alias.
Referenced by WrappedClass::make_sfinae_to_match_wrapped_class().
std::string WrappedClass::get_derived_classes_string (int level = 0, const std::string indent = "") inline inherited
Definition at line 166 of file wrapped_class.h.
References join().
Referenced by WrappedClass::get_bindings().
std::string WrappedClass::get_base_class_string () inline inherited
Definition at line 178 of file wrapped_class.h.
References base_types_to_ignore, data_error(), WrappedClass::get_bindings(), and WrappedClass::i.
Referenced by WrappedClass::get_bindings().
std::string WrappedClass::get_bindings () inherited
Definition at line 656 of file wrapped_class.cpp.
References WrappedClass::class_name, WrappedClass::derived_types, WrappedClass::get_base_class_string(), WrappedClass::get_constructors(), WrappedClass::get_derived_classes_string(), WrappedClass::get_member_functions(), WrappedClass::get_static_functions(), WrappedClass::has_static_method(), WrappedClass::name_alias, WrappedClass::wrapper_custom_extensions, and WrappedClass::wrapper_extension_methods.
Referenced by WrappedClass::get_base_class_string().
static void WrappedClass::insert_wrapped_class (WrappedClass * wrapped_class) inline static inherited
Definition at line 197 of file wrapped_class.h.
References WrappedClass::wrapped_classes.
Referenced by ClassHandler::run(), and WrappedClass::WrappedClass().
static WrappedClass* WrappedClass::get_if_exists (const CXXRecordDecl * decl) inline static inherited
Returns the wrapped class corresponding to the decl if it exists
Parameters
decl the decl to search for in existing wrapped classes
Returns
the existing wrapped class or nullptr if no match found
Definition at line 206 of file wrapped_class.h.
References WrappedClass::wrapped_classes.
Referenced by ClassHandler::run().
static WrappedClass& WrappedClass::get_or_insert_wrapped_class (const CXXRecordDecl * decl, CompilerInstance & compiler_instance, FOUND_METHOD found_method) inline static inherited
Definition at line 218 of file wrapped_class.h.
References FOUND_BASE_CLASS, WrappedClass::found_method_means_wrapped(), get_canonical_name_for_decl(), WrappedClass::wrapped_classes, and WrappedClass::WrappedClass().
Referenced by ClassHandler::run(), update_wrapped_class_for_type(), and WrappedClass::WrappedClass().
bool WrappedClass::found_method_means_wrapped () inherited
Definition at line 788 of file wrapped_class.cpp.
References FOUND_ANNOTATION, FOUND_BASE_CLASS, FOUND_GENERATED, FOUND_INHERITANCE, and WrappedClass::found_method.
Referenced by WrappedClass::get_or_insert_wrapped_class(), and WrappedClass::WrappedClass().
int WrappedClass::takes_int_5 (int x) inline inherited
Definition at line 36 of file wrapped_types_test.cpp.
References EXPECT_EQ.
Referenced by WrappedClassFixture::WrappedClassFixture().
int WrappedClass::takes_const_int_6 (int const x) const inline inherited
Definition at line 40 of file wrapped_types_test.cpp.
References EXPECT_EQ.
Referenced by WrappedClassFixture::WrappedClassFixture().
void WrappedClass::default_parameters (int j = 1, char const * s = "asdf", vector< std::string > && = {}, CopyableWrappedClass = {}, CopyableWrappedClass && = {}, CopyableWrappedClass * = nullptr) inline inherited
Definition at line 47 of file wrapped_types_test.cpp.
References EXPECT_EQ, and EXPECT_STREQ.
Referenced by WrappedClassFixture::WrappedClassFixture().
static std::string WrappedClass::static_method () inline static inherited
Definition at line 58 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
Member Data Documentation
double WrappedClassDerived::double_member_readwrite2
Definition at line 83 of file sample.cpp.
double WrappedClass::double_member_readwrite inherited
Definition at line 58 of file sample.cpp.
V8TOOLKIT_READONLY double WrappedClass::double_member_readonly1 inherited
Definition at line 59 of file sample.cpp.
double const WrappedClass::double_member_readonly2 inherited
Definition at line 60 of file sample.cpp.
std::vector<std::string> WrappedClass::vector_of_ints inherited
Definition at line 61 of file sample.cpp.
std::vector<WrappedClass *> WrappedClass::vector_of_selfs inherited
Definition at line 62 of file sample.cpp.
vector< WrappedClass * > WrappedClass::wrapped_classes static inherited
Definition at line 29 of file wrapped_class.h.
Referenced by generate_bidirectional_classes(), generate_bindings(), generate_javascript_stub(), WrappedClass::get_if_exists(), WrappedClass::get_or_insert_wrapped_class(), WrappedClass::insert_wrapped_class(), and WrappedClass::WrappedClass().
CXXRecordDecl const* WrappedClass::decl = nullptr inherited
Definition at line 31 of file wrapped_class.h.
Referenced by WrappedClass::get_members(), WrappedClass::is_template_specialization(), WrappedClass::parse_all_methods(), ClassHandler::run(), WrappedClass::update_data(), and WrappedClass::WrappedClass().
CXXRecordDecl const* WrappedClass::instantiation_pattern = nullptr inherited
Definition at line 34 of file wrapped_class.h.
string WrappedClass::class_name inherited
Definition at line 43 of file wrapped_class.h.
Referenced by WrappedClass::get_bindings(), ClassHandler::onEndOfTranslationUnit(), WrappedClass::ready_for_wrapping(), ClassHandler::run(), WrappedClass::should_be_wrapped(), update_wrapped_class_for_type(), and WrappedClass::WrappedClass().
string WrappedClass::name_alias inherited
this is the possibly shortened javascript name of the type - not necessarily valid in generated c++
Definition at line 46 of file wrapped_class.h.
Referenced by ConstructorFunction::ConstructorFunction(), WrappedClass::generate_js_stub(), WrappedClass::get_bindings(), WrappedClass::get_derived_type_includes(), ClassHandler::onEndOfTranslationUnit(), ClassFunction::ParameterInfo::ParameterInfo(), ClassHandler::run(), WrappedClass::should_be_wrapped(), update_wrapped_class_for_type(), and WrappedClass::WrappedClass().
set<string> WrappedClass::include_files inherited
Definition at line 48 of file wrapped_class.h.
Referenced by WrappedClass::get_base_type_includes(), ClassHandler::run(), update_wrapped_class_for_type(), and WrappedClass::WrappedClass().
int WrappedClass::declaration_count = 3 inherited
Definition at line 52 of file wrapped_class.h.
Referenced by ClassFunction::ClassFunction(), and DataMember::DataMember().
string WrappedClass::my_header_filename = "" inherited
Definition at line 54 of file wrapped_class.h.
set<string> WrappedClass::used_member_names inherited
Definition at line 61 of file wrapped_class.h.
Referenced by WrappedClass::add_member_name().
set<string> WrappedClass::used_static_names inherited
Definition at line 62 of file wrapped_class.h.
Referenced by WrappedClass::add_static_name().
vector<string> WrappedClass::data_errors inherited
Definition at line 63 of file wrapped_class.h.
Referenced by WrappedClass::set_error().
set<WrappedClass *> WrappedClass::derived_types inherited
Definition at line 64 of file wrapped_class.h.
Referenced by WrappedClass::get_bindings(), WrappedClass::get_derived_type_includes(), ClassHandler::run(), and WrappedClass::WrappedClass().
set<WrappedClass *> WrappedClass::base_types inherited
tracked base_types - if it's more than one, that's a data error because javascript only allows one
Definition at line 67 of file wrapped_class.h.
Referenced by WrappedClass::foreach_inheritance_level(), WrappedClass::generate_js_stub(), WrappedClass::get_base_type_includes(), WrappedClass::ready_for_wrapping(), WrappedClass::should_be_wrapped(), and WrappedClass::WrappedClass().
set<string> WrappedClass::wrapper_extension_methods inherited
Definition at line 69 of file wrapped_class.h.
Referenced by WrappedClass::get_bindings(), and WrappedClass::parse_all_methods().
set<string> WrappedClass::wrapper_custom_extensions inherited
Definition at line 70 of file wrapped_class.h.
Referenced by WrappedClass::get_bindings(), and WrappedClass::parse_all_methods().
CompilerInstance& WrappedClass::compiler_instance inherited
Definition at line 71 of file wrapped_class.h.
Referenced by update_wrapped_class_for_type().
string WrappedClass::my_include inherited
Definition at line 73 of file wrapped_class.h.
Referenced by WrappedClass::get_base_type_includes(), WrappedClass::get_derived_type_includes(), and WrappedClass::WrappedClass().
bool WrappedClass::done = false inherited
Definition at line 74 of file wrapped_class.h.
bool WrappedClass::valid = false inherited
Definition at line 75 of file wrapped_class.h.
Referenced by WrappedClass::set_error().
Annotations WrappedClass::annotations inherited
Definition at line 76 of file wrapped_class.h.
Referenced by WrappedClass::parse_all_methods(), ClassHandler::run(), WrappedClass::should_be_wrapped(), and WrappedClass::WrappedClass().
bool WrappedClass::dumped = false inherited
Definition at line 77 of file wrapped_class.h.
set<WrappedClass *> WrappedClass::used_classes inherited
Definition at line 78 of file wrapped_class.h.
Referenced by update_wrapped_class_for_type().
FOUND_METHOD WrappedClass::found_method inherited
Definition at line 79 of file wrapped_class.h.
Referenced by WrappedClass::found_method_means_wrapped(), ClassHandler::run(), and WrappedClass::should_be_wrapped().
bool WrappedClass::force_no_constructors = false inherited
Definition at line 80 of file wrapped_class.h.
Referenced by WrappedClass::parse_all_methods(), and ClassHandler::run().
bool WrappedClass::bidirectional = false inherited
Definition at line 85 of file wrapped_class.h.
Referenced by WrappedClass::WrappedClass().
CXXConstructorDecl const* WrappedClass::bidirectional_constructor = nullptr inherited
Definition at line 86 of file wrapped_class.h.
Referenced by WrappedClass::WrappedClass().
int WrappedClass::i = 5 inherited
Definition at line 29 of file wrapped_types_test.cpp.
Referenced by WrappedClass::get_base_class_string(), WrappedClass::parse_all_methods(), and WrappedClassFixture::WrappedClassFixture().
int WrappedClass::ci = 5 inherited
Definition at line 30 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
std::unique_ptr<float> WrappedClass::upf = std::make_unique<float>(3.5) inherited
Definition at line 31 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
std::unique_ptr<float> WrappedClass::cupf = std::make_unique<float>(4.5) inherited
Definition at line 32 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
std::string WrappedClass::string = "string value" inherited
Definition at line 34 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
bool WrappedClass::default_parameters_called = false inherited
Definition at line 45 of file wrapped_types_test.cpp.
Referenced by TEST_F().
CopyableWrappedClass WrappedClass::copyable_wrapped_class inherited
Definition at line 60 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
std::unique_ptr<WrappedClass> WrappedClass::up_wrapped_class inherited
Definition at line 61 of file wrapped_types_test.cpp.
Referenced by WrappedClassFixture::WrappedClassFixture().
The documentation for this class was generated from the following file:
class_parser/sample.cpp