v8toolkit: PrintFunctionNamesAction Class Reference
PrintFunctionNamesAction Class Reference
#include <ast_action.h>
Public Member Functions
PrintFunctionNamesAction ()
void EndSourceFileAction ()
Protected Member Functions
std::unique_ptr< ASTConsumer > CreateASTConsumer (CompilerInstance &CI, llvm::StringRef)
bool ParseArgs (const CompilerInstance &CI, const std::vector< std::string > &args)
void PrintHelp (llvm::raw_ostream &ros)
Detailed Description
Definition at line 11 of file ast_action.h.
Constructor & Destructor Documentation
PrintFunctionNamesAction::PrintFunctionNamesAction () inline
Definition at line 15 of file ast_action.h.
References EndSourceFileAction().
Member Function Documentation
void PrintFunctionNamesAction::EndSourceFileAction ()
Definition at line 7 of file ast_action.cpp.
Referenced by PrintFunctionNamesAction().
std::unique_ptr<ASTConsumer> PrintFunctionNamesAction::CreateASTConsumer (CompilerInstance & CI, llvm::StringRef) inline protected
Definition at line 25 of file ast_action.h.
bool PrintFunctionNamesAction::ParseArgs (const CompilerInstance & CI, const std::vector< std::string > & args) inline protected
Definition at line 30 of file ast_action.h.
References MAX_DECLARATIONS_PER_FILE, and PrintHelp().
void PrintFunctionNamesAction::PrintHelp (llvm::raw_ostream & ros) inline protected
Definition at line 47 of file ast_action.h.
Referenced by ParseArgs().
The documentation for this class was generated from the following files:
class_parser/ast_action.h
class_parser/ast_action.cpp