v8toolkit: std::tr1::tuple<> Class Template Reference
std::tr1::tuple<> Class Template Reference
#include <gtest-tuple.h>
Public Member Functions
tuple ()
tuple (GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1) f1, GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3, GTEST_BY_REF_(T4) f4, GTEST_BY_REF_(T5) f5, GTEST_BY_REF_(T6) f6, GTEST_BY_REF_(T7) f7, GTEST_BY_REF_(T8) f8, GTEST_BY_REF_(T9) f9)
tuple (const tuple &t)
template<GTEST_10_TYPENAMES_(U) >
tuple (const GTEST_10_TUPLE_(U)&t)
tuple & operator= (const tuple &t)
template<GTEST_10_TYPENAMES_(U) >
tuple & operator= (const GTEST_10_TUPLE_(U)&t)
template<GTEST_10_TYPENAMES_(U) >
GTEST_DECLARE_TUPLE_AS_FRIEND_ tuple & CopyFrom (const GTEST_10_TUPLE_(U)&t)
Public Attributes
T0 f0_
T1 f1_
T2 f2_
T3 f3_
T4 f4_
T5 f5_
T6 f6_
T7 f7_
T8 f8_
T9 f9_
Friends
template<int k>
class gtest_internal::Get
Detailed Description
template<GTEST_10_TYPENAMES_(T)>
class std::tr1::tuple<>
Definition at line 119 of file gtest-tuple.h.
Constructor & Destructor Documentation
template<GTEST_10_TYPENAMES_(T) > std::tr1::tuple<>::tuple () inline
Definition at line 616 of file gtest-tuple.h.
template<GTEST_10_TYPENAMES_(T) > std::tr1::tuple<>::tuple (GTEST_BY_REF_(T0) f0, GTEST_BY_REF_(T1) f1, GTEST_BY_REF_(T2) f2, GTEST_BY_REF_(T3) f3, GTEST_BY_REF_(T4) f4, GTEST_BY_REF_(T5) f5, GTEST_BY_REF_(T6) f6, GTEST_BY_REF_(T7) f7, GTEST_BY_REF_(T8) f8, GTEST_BY_REF_(T9) f9) inline explicit
Definition at line 619 of file gtest-tuple.h.
template<GTEST_10_TYPENAMES_(T) > std::tr1::tuple<>::tuple (const tuple<> & t) inline
Definition at line 625 of file gtest-tuple.h.
template<GTEST_10_TYPENAMES_(T) > template<GTEST_10_TYPENAMES_(U) > std::tr1::tuple<>::tuple (const GTEST_10_TUPLE_(U)& t) inline
Definition at line 629 of file gtest-tuple.h.
Member Function Documentation
template<GTEST_10_TYPENAMES_(T) > tuple& std::tr1::tuple<>::operator= (const tuple<> & t) inline
Definition at line 633 of file gtest-tuple.h.
template<GTEST_10_TYPENAMES_(T) > template<GTEST_10_TYPENAMES_(U) > tuple& std::tr1::tuple<>::operator= (const GTEST_10_TUPLE_(U)& t) inline
Definition at line 636 of file gtest-tuple.h.
References GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_10_TYPENAMES_(T) > template<GTEST_10_TYPENAMES_(U) > GTEST_DECLARE_TUPLE_AS_FRIEND_ tuple& std::tr1::tuple<>::CopyFrom (const GTEST_10_TUPLE_(U)& t) inline
Definition at line 643 of file gtest-tuple.h.
References std::tr1::tuple<>::f0_.
Friends And Related Function Documentation
template<GTEST_10_TYPENAMES_(T) > template<int k> friend class gtest_internal::Get friend
Definition at line 614 of file gtest-tuple.h.
Member Data Documentation
template<GTEST_10_TYPENAMES_(T) > T0 std::tr1::tuple<>::f0_
Definition at line 657 of file gtest-tuple.h.
Referenced by std::tr1::tuple<>::CopyFrom(), std::tr1::GTEST_1_TUPLE_(), std::tr1::GTEST_2_TUPLE_(), std::tr1::GTEST_3_TUPLE_(), std::tr1::GTEST_4_TUPLE_(), std::tr1::GTEST_5_TUPLE_(), std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T1 std::tr1::tuple<>::f1_
Definition at line 658 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_2_TUPLE_(), std::tr1::GTEST_3_TUPLE_(), std::tr1::GTEST_4_TUPLE_(), std::tr1::GTEST_5_TUPLE_(), std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T2 std::tr1::tuple<>::f2_
Definition at line 659 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_3_TUPLE_(), std::tr1::GTEST_4_TUPLE_(), std::tr1::GTEST_5_TUPLE_(), std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T3 std::tr1::tuple<>::f3_
Definition at line 660 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_4_TUPLE_(), std::tr1::GTEST_5_TUPLE_(), std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T4 std::tr1::tuple<>::f4_
Definition at line 661 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_5_TUPLE_(), std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T5 std::tr1::tuple<>::f5_
Definition at line 662 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_6_TUPLE_(), std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T6 std::tr1::tuple<>::f6_
Definition at line 663 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_7_TUPLE_(), std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T7 std::tr1::tuple<>::f7_
Definition at line 664 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_8_TUPLE_(), and std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T8 std::tr1::tuple<>::f8_
Definition at line 665 of file gtest-tuple.h.
Referenced by std::tr1::GTEST_9_TUPLE_().
template<GTEST_10_TYPENAMES_(T) > T9 std::tr1::tuple<>::f9_
Definition at line 666 of file gtest-tuple.h.
The documentation for this class was generated from the following file:
test/googletest/googletest/include/gtest/internal/gtest-tuple.h