v8toolkit: Mock Class Reference
Mock Class Reference abstract
#include <gmock_link_test.h>
Public Member Functions
Mock ()
MOCK_METHOD1 (VoidFromString, void(char *str))
MOCK_METHOD1 (StringFromString, char *(char *str))
MOCK_METHOD1 (IntFromString, int(char *str))
MOCK_METHOD1 (IntRefFromString, int &(char *str))
MOCK_METHOD1 (VoidFromFunc, void(void(*func)(char *str)))
MOCK_METHOD1 (VoidFromIntRef, void(int &n))
MOCK_METHOD1 (VoidFromFloat, void(float n))
MOCK_METHOD1 (VoidFromDouble, void(double n))
MOCK_METHOD1 (VoidFromVector, void(const std::vector< int > &v))
virtual void VoidFromString (char *str)=0
virtual char * StringFromString (char *str)=0
virtual int IntFromString (char *str)=0
virtual int & IntRefFromString (char *str)=0
virtual void VoidFromFunc (void(*func)(char *str))=0
virtual void VoidFromIntRef (int &n)=0
virtual void VoidFromFloat (float n)=0
virtual void VoidFromDouble (double n)=0
virtual void VoidFromVector (const std::vector< int > &v)=0
Detailed Description
Definition at line 205 of file gmock_link_test.h.
Constructor & Destructor Documentation
Mock::Mock () inline
Definition at line 207 of file gmock_link_test.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_, Interface::IntFromString(), Interface::IntRefFromString(), MOCK_METHOD1, Interface::StringFromString(), Interface::VoidFromDouble(), Interface::VoidFromFloat(), Interface::VoidFromFunc(), Interface::VoidFromIntRef(), Interface::VoidFromString(), and Interface::VoidFromVector().
Member Function Documentation
Mock::MOCK_METHOD1 (VoidFromString , void(char *str))
Mock::MOCK_METHOD1 (StringFromString , char * char *str)
Mock::MOCK_METHOD1 (IntFromString , int(char *str))
Mock::MOCK_METHOD1 (IntRefFromString , int & char *str)
Mock::MOCK_METHOD1 (VoidFromFunc , void(void(*func)(char *str)))
Mock::MOCK_METHOD1 (VoidFromIntRef , void(int &n))
Mock::MOCK_METHOD1 (VoidFromFloat , void(float n))
Mock::MOCK_METHOD1 (VoidFromDouble , void(double n))
Mock::MOCK_METHOD1 (VoidFromVector , void(const std::vector< int > &v))
virtual void Interface::VoidFromString (char * str) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual char* Interface::StringFromString (char * str) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual int Interface::IntFromString (char * str) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual int& Interface::IntRefFromString (char * str) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual void Interface::VoidFromFunc (void(*)(char *str) func) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual void Interface::VoidFromIntRef (int & n) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual void Interface::VoidFromFloat (float n) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual void Interface::VoidFromDouble (double n) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
virtual void Interface::VoidFromVector (const std::vector< int > & v) pure virtual inherited
Referenced by Mock(), TEST(), and Interface::~Interface().
The documentation for this class was generated from the following file:
test/googletest/googlemock/test/gmock_link_test.h