v8toolkit: testing::internal::RE Class Reference
testing::internal::RE Class Reference
#include <gtest-port.h>
Public Member Functions
RE (const RE &other)
RE (const ::std::string &regex)
RE (const char *regex)
~RE ()
const char * pattern () const
Static Public Member Functions
static bool FullMatch (const ::std::string &str, const RE &re)
static bool PartialMatch (const ::std::string &str, const RE &re)
static bool FullMatch (const char *str, const RE &re)
static bool PartialMatch (const char *str, const RE &re)
Detailed Description
Definition at line 1156 of file gtest-port.h.
Constructor & Destructor Documentation
testing::internal::RE::RE (const RE & other) inline
Definition at line 1160 of file gtest-port.h.
References pattern().
testing::internal::RE::RE (const ::std::string & regex) inline
Definition at line 1163 of file gtest-port.h.
testing::internal::RE::RE (const char * regex) inline
Definition at line 1171 of file gtest-port.h.
testing::internal::RE::~RE ()
Member Function Documentation
const char* testing::internal::RE::pattern () const inline
Definition at line 1175 of file gtest-port.h.
Referenced by RE().
static bool testing::internal::RE::FullMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1184 of file gtest-port.h.
static bool testing::internal::RE::PartialMatch (const ::std::string & str, const RE & re) inline static
Definition at line 1187 of file gtest-port.h.
References testing::internal::FormatCompilerIndependentFileLocation(), testing::internal::FormatFileLocation(), and GTEST_DISALLOW_ASSIGN_.
static bool testing::internal::RE::FullMatch (const char * str, const RE & re) static
static bool testing::internal::RE::PartialMatch (const char * str, const RE & re) static
The documentation for this class was generated from the following file:
test/googletest/googletest/include/gtest/internal/gtest-port.h