v8toolkit: testing::internal::ElementsAreMatcherImpl< Container > Class Template Reference
testing::internal::ElementsAreMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef internal::StlContainerView< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InputIter >
ElementsAreMatcherImpl (InputIter first, InputIter last)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Detailed Description
template<typename Container>
class testing::internal::ElementsAreMatcherImpl< Container >
Definition at line 3108 of file gmock-matchers.h.
Member Typedef Documentation
template<typename Container > typedef internal::StlContainerView<RawContainer> testing::internal::ElementsAreMatcherImpl< Container >::View
Definition at line 3111 of file gmock-matchers.h.
template<typename Container > typedef View::type testing::internal::ElementsAreMatcherImpl< Container >::StlContainer
Definition at line 3112 of file gmock-matchers.h.
template<typename Container > typedef View::const_reference testing::internal::ElementsAreMatcherImpl< Container >::StlContainerReference
Definition at line 3113 of file gmock-matchers.h.
template<typename Container > typedef StlContainer::value_type testing::internal::ElementsAreMatcherImpl< Container >::Element
Definition at line 3114 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename Container > template<typename InputIter > testing::internal::ElementsAreMatcherImpl< Container >::ElementsAreMatcherImpl (InputIter first, InputIter last) inline
Definition at line 3119 of file gmock-matchers.h.
Member Function Documentation
template<typename Container > typedef testing::internal::ElementsAreMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
template<typename Container > virtual void testing::internal::ElementsAreMatcherImpl< Container >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3126 of file gmock-matchers.h.
template<typename Container > virtual void testing::internal::ElementsAreMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3145 of file gmock-matchers.h.
template<typename Container > virtual bool testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 3161 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-matchers.h