v8toolkit: testing::internal::PairMatcherImpl< PairType > Class Template Reference
testing::internal::PairMatcherImpl< PairType > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef RawPairType::first_type FirstType
typedef RawPairType::second_type SecondType
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType) RawPairType
template<typename FirstMatcher , typename SecondMatcher >
PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (PairType a_pair, MatchResultListener *listener) const
Detailed Description
template<typename PairType>
class testing::internal::PairMatcherImpl< PairType >
Definition at line 3001 of file gmock-matchers.h.
Member Typedef Documentation
template<typename PairType > typedef RawPairType::first_type testing::internal::PairMatcherImpl< PairType >::FirstType
Definition at line 3004 of file gmock-matchers.h.
template<typename PairType > typedef RawPairType::second_type testing::internal::PairMatcherImpl< PairType >::SecondType
Definition at line 3005 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename PairType > template<typename FirstMatcher , typename SecondMatcher > testing::internal::PairMatcherImpl< PairType >::PairMatcherImpl (FirstMatcher first_matcher, SecondMatcher second_matcher) inline
Definition at line 3008 of file gmock-matchers.h.
Member Function Documentation
template<typename PairType > typedef testing::internal::PairMatcherImpl< PairType >::GTEST_REMOVE_REFERENCE_AND_CONST_ (PairType)
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 3016 of file gmock-matchers.h.
template<typename PairType > virtual void testing::internal::PairMatcherImpl< PairType >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 3024 of file gmock-matchers.h.
template<typename PairType > virtual bool testing::internal::PairMatcherImpl< PairType >::MatchAndExplain (PairType a_pair, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 3033 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-matchers.h