v8toolkit: testing::internal::PredicateFormatterFromMatcher< M > Class Template Reference
testing::internal::PredicateFormatterFromMatcher< M > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
PredicateFormatterFromMatcher (M m)
template<typename T >
AssertionResult operator() (const char *value_text, const T &x) const
Detailed Description
template<typename M>
class testing::internal::PredicateFormatterFromMatcher< M >
Definition at line 1834 of file gmock-matchers.h.
Constructor & Destructor Documentation
template<typename M > testing::internal::PredicateFormatterFromMatcher< M >::PredicateFormatterFromMatcher (M m) inline explicit
Definition at line 1836 of file gmock-matchers.h.
Member Function Documentation
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
Definition at line 1842 of file gmock-matchers.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatcherBase< T >::DescribeTo(), GTEST_DISALLOW_ASSIGN_, and testing::internal::MatchPrintAndExplain().
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-matchers.h