v8toolkit: testing::internal::linked_ptr< T > Class Template Reference
testing::internal::linked_ptr< T > Class Template Reference
#include <gtest-linked_ptr.h>
Public Types
typedef T element_type
Public Member Functions
linked_ptr (T *ptr=NULL)
~linked_ptr ()
template<typename U >
linked_ptr (linked_ptr< U > const &ptr)
linked_ptr (linked_ptr const &ptr)
template<typename U >
linked_ptr & operator= (linked_ptr< U > const &ptr)
linked_ptr & operator= (linked_ptr const &ptr)
void reset (T *ptr=NULL)
T * get () const
T * operator-> () const
T & operator* () const
bool operator== (T *p) const
bool operator!= (T *p) const
template<typename U >
bool operator== (linked_ptr< U > const &ptr) const
template<typename U >
bool operator!= (linked_ptr< U > const &ptr) const
Friends
template<typename U >
class linked_ptr
Detailed Description
template<typename T>
class testing::internal::linked_ptr< T >
Definition at line 146 of file gtest-linked_ptr.h.
Member Typedef Documentation
template<typename T> typedef T testing::internal::linked_ptr< T >::element_type
Definition at line 148 of file gtest-linked_ptr.h.
Constructor & Destructor Documentation
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (T * ptr = NULL) inline explicit
Definition at line 152 of file gtest-linked_ptr.h.
template<typename T> testing::internal::linked_ptr< T >::~linked_ptr () inline
Definition at line 153 of file gtest-linked_ptr.h.
template<typename T> template<typename U > testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< U > const & ptr) inline
Definition at line 156 of file gtest-linked_ptr.h.
template<typename T> testing::internal::linked_ptr< T >::linked_ptr (linked_ptr< T > const & ptr) inline
Definition at line 157 of file gtest-linked_ptr.h.
Member Function Documentation
template<typename T> template<typename U > linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< U > const & ptr) inline
Definition at line 163 of file gtest-linked_ptr.h.
template<typename T> linked_ptr& testing::internal::linked_ptr< T >::operator= (linked_ptr< T > const & ptr) inline
Definition at line 169 of file gtest-linked_ptr.h.
template<typename T> void testing::internal::linked_ptr< T >::reset (T * ptr = NULL) inline
Definition at line 178 of file gtest-linked_ptr.h.
template<typename T> T* testing::internal::linked_ptr< T >::get () const inline
Definition at line 182 of file gtest-linked_ptr.h.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator!=(), testing::internal::operator!=(), testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator==(), and testing::internal::operator==().
template<typename T> T* testing::internal::linked_ptr< T >::operator-> () const inline
Definition at line 183 of file gtest-linked_ptr.h.
template<typename T> T& testing::internal::linked_ptr< T >::operator* () const inline
Definition at line 184 of file gtest-linked_ptr.h.
template<typename T> bool testing::internal::linked_ptr< T >::operator== (T * p) const inline
Definition at line 186 of file gtest-linked_ptr.h.
template<typename T> bool testing::internal::linked_ptr< T >::operator!= (T * p) const inline
Definition at line 187 of file gtest-linked_ptr.h.
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator== (linked_ptr< U > const & ptr) const inline
Definition at line 189 of file gtest-linked_ptr.h.
template<typename T> template<typename U > bool testing::internal::linked_ptr< T >::operator!= (linked_ptr< U > const & ptr) const inline
Definition at line 193 of file gtest-linked_ptr.h.
Friends And Related Function Documentation
template<typename T> template<typename U > friend class linked_ptr friend
Definition at line 199 of file gtest-linked_ptr.h.
The documentation for this class was generated from the following file:
test/googletest/googletest/include/gtest/internal/gtest-linked_ptr.h