v8toolkit: testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Class Template Reference
testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 > Class Template Reference
#include <gmock-generated-matchers.h>
Public Types
typedef internal::TupleFields< RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::type SelectedArgs
typedef Matcher< const SelectedArgs & > MonomorphicInnerMatcher
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple) RawArgsTuple
template<typename InnerMatcher >
ArgsMatcherImpl (const InnerMatcher &inner_matcher)
virtual bool MatchAndExplain (ArgsTuple args, MatchResultListener *listener) const
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
Detailed Description
template<class ArgsTuple, int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1>
class testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >
Definition at line 211 of file gmock-generated-matchers.h.
Member Typedef Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef internal::TupleFields<RawArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9>::type testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::SelectedArgs
Definition at line 216 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef Matcher<const SelectedArgs&> testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MonomorphicInnerMatcher
Definition at line 217 of file gmock-generated-matchers.h.
Constructor & Destructor Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> template<typename InnerMatcher > testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::ArgsMatcherImpl (const InnerMatcher & inner_matcher) inline explicit
Definition at line 220 of file gmock-generated-matchers.h.
Member Function Documentation
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> typedef testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GTEST_REMOVE_REFERENCE_AND_CONST_ (ArgsTuple)
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual bool testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain (ArgsTuple args, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< ArgsTuple >.
Definition at line 223 of file gmock-generated-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeTo (::std::ostream * os) const inline virtual
Implements testing::MatcherDescriberInterface.
Definition at line 239 of file gmock-generated-matchers.h.
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual void testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::DescribeNegationTo (::std::ostream * os) const inline virtual
Reimplemented from testing::MatcherDescriberInterface.
Definition at line 245 of file gmock-generated-matchers.h.
References testing::internal::TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::GetSelectedFields(), and GTEST_DISALLOW_ASSIGN_.
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-generated-matchers.h