v8toolkit: testing::internal::GTestFlagSaver Class Reference
testing::internal::GTestFlagSaver Class Reference
#include <gtest-internal-inl.h>
Public Member Functions
GTestFlagSaver ()
~GTestFlagSaver ()
Detailed Description
Definition at line 162 of file gtest-internal-inl.h.
Constructor & Destructor Documentation
testing::internal::GTestFlagSaver::GTestFlagSaver () inline
Definition at line 165 of file gtest-internal-inl.h.
References GTEST_FLAG.
testing::internal::GTestFlagSaver::~GTestFlagSaver () inline
Definition at line 186 of file gtest-internal-inl.h.
References testing::internal::CodePointToUtf8(), GTEST_API_, testing::internal::GTEST_ATTRIBUTE_UNUSED_, GTEST_FLAG, testing::internal::Int32FromEnvOrDie(), testing::internal::ShouldRunTestOnShard(), testing::internal::ShouldShard(), testing::internal::WideStringToUtf8(), and testing::internal::WriteToShardStatusFileIfNeeded().
The documentation for this class was generated from the following file:
test/googletest/googletest/src/gtest-internal-inl.h