v8toolkit: testing::internal::TuplePrefix< N > Class Template Reference
testing::internal::TuplePrefix< N > Class Template Reference
#include <gmock-matchers.h>
Static Public Member Functions
template<typename MatcherTuple , typename ValueTuple >
static bool Matches (const MatcherTuple &matcher_tuple, const ValueTuple &value_tuple)
template<typename MatcherTuple , typename ValueTuple >
static void ExplainMatchFailuresTo (const MatcherTuple &matchers, const ValueTuple &values,::std::ostream *os)
Detailed Description
template<size_t N>
class testing::internal::TuplePrefix< N >
Definition at line 726 of file gmock-matchers.h.
Member Function Documentation
template<size_t N> template<typename MatcherTuple , typename ValueTuple > static bool testing::internal::TuplePrefix< N >::Matches (const MatcherTuple & matcher_tuple, const ValueTuple & value_tuple) inline static
Definition at line 732 of file gmock-matchers.h.
References testing::Matches().
template<size_t N> template<typename MatcherTuple , typename ValueTuple > static void testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo (const MatcherTuple & matchers, const ValueTuple & values, ::std::ostream * os) inline static
Definition at line 743 of file gmock-matchers.h.
References testing::internal::PrintIfNotEmpty(), testing::internal::UniversalPrint(), and testing::Value().
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-matchers.h