v8toolkit: v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE > Class Template Reference
v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE > Class Template Reference
#include <v8_class_wrapper.h>
Classes
struct NamedPropertyCallbackData
class NoResultAvailable
Public Types
template<class ReturnT >
using NamedPropertyGetter = func::function< ReturnT(T *, std::string const &)>
template<class ReturnT >
using NamedPropertySetter = func::function< ReturnT(T *, std::string const &)>
Public Member Functions
T * get_cpp_object (v8::Local< v8::Object > object)
void register_callback (PropertyChangedCallback callback)
T * release_internal_field_memory (v8::Local< v8::Object > object)
v8::Local< v8::FunctionTemplate > make_wrapping_function_template (v8::FunctionCallback callback=nullptr, const v8::Local< v8::Value > &data=v8::Local< v8::Value >())
v8::Local< v8::FunctionTemplate > get_function_template ()
T * cast (AnyBase *any_base)
void init_instance_object_template (v8::Local< v8::ObjectTemplate > object_template)
void init_prototype_object_template (v8::Local< v8::ObjectTemplate > object_template)
void init_static_methods (v8::Local< v8::FunctionTemplate > constructor_function_template)
void isolate_about_to_be_destroyed (v8::Isolate *isolate)
void set_class_name (const std::string &name)
template<class... CompatibleTypes>
std::enable_if_t< static_all_of< std::is_base_of< T, CompatibleTypes >::value... >::value > set_compatible_types ()
template<template< class > class Deleter>
void set_deleter ()
template<class ParentType >
std::enable_if_t< std::is_base_of< ParentType, T >::value > set_parent_type ()
virtual ~V8ClassWrapper ()
template<typename... CONSTRUCTOR_PARAMETER_TYPES, class DefaultArgsTuple = std::tuple<>>
void add_constructor (const std::string &js_constructor_name, v8::Local< v8::ObjectTemplate > parent_template, DefaultArgsTuple const &default_args=DefaultArgsTuple())
void expose_static_methods (const std::string &js_name, v8::Local< v8::ObjectTemplate > parent_template)
v8::Local< v8::Object > wrap_existing_cpp_object (v8::Local< v8::Context > context, T *existing_cpp_object, DestructorBehavior &destructor_behavior, bool force_wrap_this_type=false)
template<class R , class... Params, class DefaultArgs = std::tuple<>>
void add_static_method (const std::string &method_name, R(*callable)(Params...), DefaultArgs const &default_args_tuple=DefaultArgs{})
template<class Callable , class DefaultArgs = std::tuple<>>
void add_static_method (const std::string &method_name, Callable callable, DefaultArgs const &default_args_tuple=DefaultArgs{})
void finalize (bool wrap_as_most_derived=false)
bool is_finalized ()
template<class MemberType , class MemberClass , MemberType MemberClass::* member>
void add_member (std::string const &member_name)
template<auto member>
void add_member (std::string const &member_name)
template<class MemberType , class MemberClass , MemberType MemberClass::* member, std::enable_if_t< std::is_base_of< MemberClass, T >::value, int > = 0>
void add_member_readonly (std::string const &member_name)
template<auto member>
void add_member_readonly (std::string const &member_name)
template<class R , class TBase , class... Args, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void make_callable (R(TBase::*method)(Args...))
template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void add_method (const std::string &method_name, R(TBase::*method)(Args...) const, DefaultArgs const &default_args=DefaultArgs())
template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void add_method (const std::string &method_name, R(TBase::*method)(Args...) const &, DefaultArgs const &default_args=DefaultArgs())
template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void add_method (const std::string &method_name, R(TBase::*method)(Args...) const &&, DefaultArgs const &default_args=DefaultArgs())
template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void add_method (const std::string &method_name, R(TBase::*method)(Args...), DefaultArgs const &default_args=DefaultArgs())
template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void add_method (const std::string &method_name, R(TBase::*method)(Args...)&, DefaultArgs const &default_args=DefaultArgs())
template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0>
void add_method (const std::string &method_name, R(TBase::*method)(Args...)&&, DefaultArgs const &default_args=DefaultArgs())
template<class R , class Head , class... Tail, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_const< Head >::value &&!std::is_const< T >::value, int > = 0>
void add_fake_method_for_const_type (const std::string &method_name, func::function< R(Head *, Tail...)> method, DefaultArgs const &default_args=DefaultArgs())
template<class R , class Head , class... Tail, class DefaultArgs = std::tuple<>, std::enable_if_t<!(std::is_const< Head >::value &&!std::is_const< T >::value), int > = 0>
void add_fake_method_for_const_type (const std::string &method_name, func::function< R(Head *, Tail...)> method, DefaultArgs const &default_args=DefaultArgs())
template<class R , class Head , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_pointer< Head >::value &&std::is_same< std::remove_const_t< std::remove_pointer_t< Head >>, T >::value, int > = 0>
void add_method (const std::string &method_name, func::function< R(Head, Args...)> &method, DefaultArgs const &default_args=DefaultArgs())
template<class R , class Head , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_pointer< Head >::value &&std::is_base_of< std::remove_const_t< std::remove_pointer_t< Head >>, T >::value, int > = 0>
void add_method (const std::string &method_name, R(*method)(Head, Args...), DefaultArgs const &default_args=DefaultArgs())
template<class Callback , class DefaultArgs = std::tuple<>>
void add_method (const std::string &method_name, Callback &&callback, DefaultArgs const &default_args=DefaultArgs())
v8::Local< v8::Object > wrap_as_most_derived (T *cpp_object, DestructorBehavior &destructor_behavior)
template<class R , class Head , class... Tail, class DefaultArgsTuple , std::enable_if_t< std::is_pointer< Head >::value &&std::is_same< std::remove_const_t< std::remove_pointer_t< Head >>, std::remove_const_t< T >>::value, int > = 0>
void _add_fake_method (const std::string &method_name, func::function< R(Head, Tail...)> method, DefaultArgsTuple const &default_args)
template<class M , class... Args, class... DefaultArgTypes>
void _add_method (const std::string &method_name, M method, TypeList< Args... > const &, std::tuple< DefaultArgTypes... > const &default_args_tuple, bool add_as_callable_object_callback=false)
void add_index_getter (v8::IndexedPropertyGetterCallback getter)
template<class ResultT >
std::enable_if_t< std::is_pointer< ResultT >::value, void > handle_getter_result (ResultT &&result, v8::PropertyCallbackInfo< v8::Value > const &info)
template<class ResultT >
std::enable_if_t<!std::is_pointer< ResultT >::value, void > handle_getter_result (ResultT &&result, v8::PropertyCallbackInfo< v8::Value > const &info)
void add_new_constructor_function_template_callback (FunctionTemplateCallback const &callback)
Static Public Member Functions
static bool does_object_own_memory (v8::Local< v8::Object > object)
static void initialize_new_js_object (v8::Isolate *isolate, v8::Local< v8::Object > js_object, T *cpp_object, DestructorBehavior const &destructor_behavior)
static V8ClassWrapper< T > & get_instance (v8::Isolate *isolate)
Public Attributes
std::unique_ptr< DestructorBehavior > destructor_behavior_delete = std::make_unique<DestructorBehavior_Delete<T>>()
std::unique_ptr< DestructorBehavior > destructor_behavior_leave_alone = std::make_unique<DestructorBehavior_LeaveAlone>()
Detailed Description
template<class T>
class v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >
Definition at line 329 of file v8_class_wrapper.h.
Class Documentation
struct v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::NamedPropertyCallbackData
template<class T>
struct v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::NamedPropertyCallbackData
Definition at line 1477 of file v8_class_wrapper.h.
Class Members
T * cpp_object
function< void(Local< Name >
property_name,
PropertyCallbackInfo< Value >
const &)> getter
function< void(Local< Name >
property_name, Local< Value >
new_property_value,
PropertyCallbackInfo< Value >
const &)> setter
Member Typedef Documentation
template<class T > template<class ReturnT > using v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::NamedPropertyGetter = func::function<ReturnT(T*, std::string const &)>
Definition at line 1487 of file v8_class_wrapper.h.
template<class T > template<class ReturnT > using v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::NamedPropertySetter = func::function<ReturnT(T*, std::string const &)>
Definition at line 1490 of file v8_class_wrapper.h.
Constructor & Destructor Documentation
template<class T > v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::~V8ClassWrapper () virtual
V8ClassWrapper objects shouldn't be deleted during the normal flow of your program unless the associated isolate is going away forever. Things will break otherwise as no additional objects will be able to be created even though V8 will still present the ability to your javascript (I think)
Definition at line 253 of file v8_class_wrapper_impl.h.
Member Function Documentation
template<class T > T * v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::get_cpp_object (v8::Local< v8::Object > object)
Returns the embedded C++ object in a JavaScript object
Parameters
object JavaScript object containing an embedded C++ object
Returns
The embedded C++ object
Returns the embedded native object inside a javascript object or nullptr if none is present or it isn't of the correct type
Definition at line 160 of file v8_class_wrapper_impl.h.
References V8TOOLKIT_DEBUG.
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::register_callback (PropertyChangedCallback callback)
Experimental
Parameters
callback
Definition at line 88 of file v8_class_wrapper_impl.h.
template<class T > T* v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::release_internal_field_memory (v8::Local< v8::Object > object) inline
Object still has the memory, it just doesn't own it. It may or may not have owned it before, but now it definitely doesn't.
Parameters
object JS object to make sure no longer owns its internal CPP object
Returns
the cpp object from inside the provided JS object
Definition at line 646 of file v8_class_wrapper.h.
template<class T > static bool v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::does_object_own_memory (v8::Local< v8::Object > object) inline static
Definition at line 671 of file v8_class_wrapper.h.
template<class T > static void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::initialize_new_js_object (v8::Isolate * isolate, v8::Local< v8::Object > js_object, T * cpp_object, DestructorBehavior const & destructor_behavior) inline static
Definition at line 682 of file v8_class_wrapper.h.
References v8toolkit::DestructorBehavior::destructive(), and v8toolkit::global_set_weak().
template<class T > v8::Local< v8::FunctionTemplate > v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::make_wrapping_function_template (v8::FunctionCallback callback = nullptr, const v8::Local< v8::Value > & data = v8::Local<v8::Value>())
Creates a new v8::FunctionTemplate capabale of creating wrapped T objects based on previously added methods and members. TODO: This needs to track all FunctionTemplates ever created so it can try to use them in GetInstanceByPrototypeChain
Creates a new v8::FunctionTemplate capable of creating wrapped T objects based on previously added methods and members. TODO: This needs to track all FunctionTemplates ever created so it can try to use them in GetInstanceByPrototypeChain
Definition at line 100 of file v8_class_wrapper_impl.h.
template<class T > v8::Local< v8::FunctionTemplate > v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::get_function_template ()
Returns an existing constructor function template for the class/isolate OR creates one if none exist. This is to keep the number of constructor function templates as small as possible because looking up which one created an object takes linear time based on the number that exist
Definition at line 141 of file v8_class_wrapper_impl.h.
template<class T > T * v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::cast (AnyBase * any_base)
Check to see if an object can be converted to type T, else return nullptr
Definition at line 185 of file v8_class_wrapper_impl.h.
References V8TOOLKIT_DEBUG.
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::init_instance_object_template (v8::Local< v8::ObjectTemplate > object_template)
Definition at line 208 of file v8_class_wrapper_impl.h.
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::init_prototype_object_template (v8::Local< v8::ObjectTemplate > object_template)
Definition at line 224 of file v8_class_wrapper_impl.h.
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::init_static_methods (v8::Local< v8::FunctionTemplate > constructor_function_template)
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::isolate_about_to_be_destroyed (v8::Isolate * isolate) inline
Definition at line 752 of file v8_class_wrapper.h.
template<class T > static V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::get_instance (v8::Isolate * isolate) inline static
Returns a "singleton-per-isolate" instance of the V8ClassWrapper for the wrapped class type. For each isolate you need to add constructors/methods/members separately.
Definition at line 767 of file v8_class_wrapper.h.
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::set_class_name (const std::string & name)
Specify the name of the object which will be used for debugging statements as well as being the type returned from javascript typeof
Definition at line 262 of file v8_class_wrapper_impl.h.
template<class T > template<class... CompatibleTypes> std::enable_if_t<static_all_of<std::is_base_of<T,CompatibleTypes>::value...>::value> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::set_compatible_types () inline
Species other types that can be substituted for T when calling a function expecting T but T is not being passsed. Only available for classes derived from T. Every type is always compatible with itself and should not be specified here. Not calling this means that only T objects will be accepted for things that want a T. There is no automatic determination of inherited types by this library because I cannot figure out how. It's VERY important that any type marked as having this type as a parent be marked as being a compatible type.
Definition at line 799 of file v8_class_wrapper.h.
template<class T > template<template< class > class Deleter> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::set_deleter () inline
Definition at line 825 of file v8_class_wrapper.h.
template<class T > template<class ParentType > std::enable_if_t<std::is_base_of<ParentType, T>::value> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::set_parent_type () inline
This wrapped class will inherit all the methods from the parent type (and its parent...)
It is VERY important that the type being marked as the parent type has this type set with set_compatible_types<>()
Definition at line 843 of file v8_class_wrapper.h.
References ISOLATE_SCOPED_RUN.
template<class T > template<typename... CONSTRUCTOR_PARAMETER_TYPES, class DefaultArgsTuple = std::tuple<>> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_constructor (const std::string & js_constructor_name, v8::Local< v8::ObjectTemplate > parent_template, DefaultArgsTuple const & default_args = DefaultArgsTuple()) inline
Creates a javascript method with the specified name inside parent_template which, when called with the "new" keyword, will return a new object of this type.
Definition at line 880 of file v8_class_wrapper.h.
References testing::internal::move().
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::expose_static_methods (const std::string & js_name, v8::Local< v8::ObjectTemplate > parent_template) inline
When you don't want a "constructor" but you still need something to attach the static method names to, use this instead of add_constructor
Definition at line 901 of file v8_class_wrapper.h.
References v8toolkit::global_name_conflicts().
template<class T > v8::Local<v8::Object> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::wrap_existing_cpp_object (v8::Local< v8::Context > context, T * existing_cpp_object, DestructorBehavior & destructor_behavior, bool force_wrap_this_type = false) inline
Used when wanting to return an object from a c++ function call back to javascript, or in conjunction with add_variable to give a javascript name to an existing c++ object
add_variable(context, context->GetGlobal(), "js_name", class_wrapper.wrap_existing_cpp_object(context, some_c++_object));
Definition at line 929 of file v8_class_wrapper.h.
References v8toolkit::safe_get_javascript_object(), and V8TOOLKIT_DEBUG.
template<class T > template<class R , class... Params, class DefaultArgs = std::tuple<>> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_static_method (const std::string & method_name, R(*)(Params...) callable, DefaultArgs const & default_args_tuple = DefaultArgs{}) inline
Definition at line 996 of file v8_class_wrapper.h.
References v8toolkit::make_function_template().
template<class T > template<class Callable , class DefaultArgs = std::tuple<>> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_static_method (const std::string & method_name, Callable callable, DefaultArgs const & default_args_tuple = DefaultArgs{}) inline
Definition at line 1030 of file v8_class_wrapper.h.
References v8toolkit::make_function_template().
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::finalize (bool wrap_as_most_derived_flag = false)
Function to force API user to declare that all members/methods have been added before any objects of the wrapped type can be created to make sure everything stays consistent Must be called before adding any constructors or using wrap_existing_object()
Definition at line 275 of file v8_class_wrapper_impl.h.
template<class T > bool v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::is_finalized () inline
returns whether finalize() has been called on this type for this isolate
Definition at line 1068 of file v8_class_wrapper.h.
template<class T > template<class MemberType , class MemberClass , MemberType MemberClass::* member> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_member (std::string const & member_name) inline
Adds a getter and setter method for the specified class member add_member(&ClassName::member_name, "javascript_attribute_name");
Definition at line 1081 of file v8_class_wrapper.h.
template<class T > template<auto member> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_member (std::string const & member_name) inline
Definition at line 1087 of file v8_class_wrapper.h.
template<class T > template<class MemberType , class MemberClass , MemberType MemberClass::* member, std::enable_if_t< std::is_base_of< MemberClass, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_member_readonly (std::string const & member_name) inline
Definition at line 1118 of file v8_class_wrapper.h.
template<class T > template<auto member> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_member_readonly (std::string const & member_name) inline
Definition at line 1123 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::make_callable (R(TBase::*)(Args...) method) inline
The specified function will be called when the JavaScript object is called like a function
Parameters
method function to call
Definition at line 1149 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(TBase::*)(Args...) const method, DefaultArgs const & default_args = DefaultArgs()) inline
Adds const-qualified member instance functions
Parameters
method_name JavaScript property name to use
method member instance function pointer
default_args any default arguments to be used if insufficient JavaScript arguments provided
Definition at line 1164 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(TBase::*)(Args...) const method & , DefaultArgs const & default_args = DefaultArgs()) inline
Adds const-and-lvalue-qualified member instance functions
Parameters
method_name JavaScript property name to use
method member instance function pointer
default_args any default arguments to be used if insufficient JavaScript arguments provided
Definition at line 1179 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(TBase::*)(Args...) const method && , DefaultArgs const & default_args = DefaultArgs()) inline
const rvalue instance functions not supported yet. Using this triggers a static assertion failure
Parameters
method_name ignored
method member ignored
default_args ignored
Definition at line 1195 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(TBase::*)(Args...) method, DefaultArgs const & default_args = DefaultArgs()) inline
Adds const-and-lvalue-qualified member instance functions
Parameters
method_name JavaScript property name to use
method member instance function pointer
default_args any default arguments to be used if insufficient JavaScript arguments provided
Definition at line 1208 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(TBase::*)(Args...) method & , DefaultArgs const & default_args = DefaultArgs()) inline
Adds lvalue-qualified member instance functions
Parameters
method_name JavaScript property name to use
method member instance function pointer
default_args any default arguments to be used if insufficient JavaScript arguments provided
Definition at line 1221 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class TBase , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_base_of< TBase, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(TBase::*)(Args...) method && , DefaultArgs const & default_args = DefaultArgs()) inline
rvalue instance functions not supported yet. Using this triggers a static assertion failure
Parameters
method_name ignored
method member ignored
default_args ignored
Definition at line 1235 of file v8_class_wrapper.h.
template<class T > template<class R , class Head , class... Tail, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_const< Head >::value &&!std::is_const< T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_fake_method_for_const_type (const std::string & method_name, func::function< R(Head *, Tail...)> method, DefaultArgs const & default_args = DefaultArgs()) inline
If the method is marked const, add it to the const version of the wrapped type
Definition at line 1248 of file v8_class_wrapper.h.
template<class T > template<class R , class Head , class... Tail, class DefaultArgs = std::tuple<>, std::enable_if_t<!(std::is_const< Head >::value &&!std::is_const< T >::value), int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_fake_method_for_const_type (const std::string & method_name, func::function< R(Head *, Tail...)> method, DefaultArgs const & default_args = DefaultArgs()) inline
If the method is not marked const, don't add it to the const type (since it's incompatible)
Definition at line 1259 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class Head , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_pointer< Head >::value &&std::is_same< std::remove_const_t< std::remove_pointer_t< Head >>, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, func::function< R(Head, Args...)> & method, DefaultArgs const & default_args = DefaultArgs()) inline
Creates a "fake" method from any callable which takes a T* as its first parameter. Does not create the method on the const type
Parameters
method_name JavaScript name to expose this method as
method method to call when JavaScript function invoked
Definition at line 1274 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class R , class Head , class... Args, class DefaultArgs = std::tuple<>, std::enable_if_t< std::is_pointer< Head >::value &&std::is_base_of< std::remove_const_t< std::remove_pointer_t< Head >>, T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, R(*)(Head, Args...) method, DefaultArgs const & default_args = DefaultArgs()) inline
Creates a "fake" method from any callable which takes a T* as its first parameter. Does not create the method on the const type
Parameters
method_name JavaScript name to expose this method as
method method to call when JavaScript function invoked
Definition at line 1289 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class Callback , class DefaultArgs = std::tuple<>> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_method (const std::string & method_name, Callback && callback, DefaultArgs const & default_args = DefaultArgs()) inline
Takes a lambda taking a T* as its first parameter and creates a 'fake method' with it
Definition at line 1300 of file v8_class_wrapper.h.
template<class T > v8::Local<v8::Object> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::wrap_as_most_derived (T * cpp_object, DestructorBehavior & destructor_behavior) inline
Definition at line 1308 of file v8_class_wrapper.h.
template<class T > template<class R , class Head , class... Tail, class DefaultArgsTuple , std::enable_if_t< std::is_pointer< Head >::value &&std::is_same< std::remove_const_t< std::remove_pointer_t< Head >>, std::remove_const_t< T >>::value, int > = 0> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::_add_fake_method (const std::string & method_name, func::function< R(Head, Tail...)> method, DefaultArgsTuple const & default_args) inline
Definition at line 1317 of file v8_class_wrapper.h.
References testing::Args().
template<class T > template<class M , class... Args, class... DefaultArgTypes> void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::_add_method (const std::string & method_name, M method, TypeList< Args... > const & , std::tuple< DefaultArgTypes... > const & default_args_tuple, bool add_as_callable_object_callback = false) inline
A list of methods to be added to each object
Definition at line 1380 of file v8_class_wrapper.h.
References v8toolkit::MethodAdderData::callback, v8toolkit::dump_prototypes(), v8toolkit::stringify_value(), and V8TOOLKIT_DEBUG.
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_index_getter (v8::IndexedPropertyGetterCallback getter) inline
http://v8.paulfryzel.com/docs/master/classv8_1_1_object_template.html#ae3303f3d55370684ac02b02e67712eac This version hasn't been enhanced yet like the named property version has. Sets a callback when some_object[4] is called
Parameters
callable function to be called
Definition at line 1470 of file v8_class_wrapper.h.
template<class T > template<class ResultT > std::enable_if_t<std::is_pointer<ResultT>::value, void> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::handle_getter_result (ResultT && result, v8::PropertyCallbackInfo< v8::Value > const & info) inline
Definition at line 1505 of file v8_class_wrapper.h.
template<class T > template<class ResultT > std::enable_if_t<!std::is_pointer<ResultT>::value, void> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::handle_getter_result (ResultT && result, v8::PropertyCallbackInfo< v8::Value > const & info) inline
Definition at line 1514 of file v8_class_wrapper.h.
References v8toolkit::bind(), and testing::internal::move().
template<class T > void v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_new_constructor_function_template_callback (FunctionTemplateCallback const & callback) inline
ADVANCED: allows direct customization of the v8::FunctionTemplate used to create objects Use for anything this library doesn't take care of
Definition at line 1634 of file v8_class_wrapper.h.
Member Data Documentation
template<class T > std::unique_ptr<DestructorBehavior> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::destructor_behavior_delete = std::make_unique<DestructorBehavior_Delete<T>>()
Definition at line 622 of file v8_class_wrapper.h.
template<class T > std::unique_ptr<DestructorBehavior> v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::destructor_behavior_leave_alone = std::make_unique<DestructorBehavior_LeaveAlone>()
Definition at line 623 of file v8_class_wrapper.h.
The documentation for this class was generated from the following files:
include/v8_class_wrapper.h
include/v8_class_wrapper_impl.h