v8toolkit: StaticFunction Class Reference
StaticFunction Class Reference
#include <parsed_method.h>
Public Member Functions
StaticFunction (WrappedClass &wrapped_class, CXXMethodDecl const *method_decl)
string generate_js_bindings ()
string generate_js_stub ()
string get_default_argument_tuple_string () const
string get_signature_string ()
bool compare_signatures (ClassFunction const &other)
string get_parameter_types_string () const
string get_return_and_class_and_parameter_types_string () const
string get_return_and_parameter_types_string () const
string get_js_input_parameter_string () const
Public Attributes
WrappedClass & wrapped_class
bool is_static
bool is_virtual
bool new_virtual
TypeInfo return_type
string return_type_comment
vector< ParameterInfo > parameters
CXXMethodDecl const * method_decl
string name
string js_name
CompilerInstance & compiler_instance
Annotations annotations
Detailed Description
Definition at line 131 of file parsed_method.h.
Constructor & Destructor Documentation
StaticFunction::StaticFunction (WrappedClass & wrapped_class, CXXMethodDecl const * method_decl)
Definition at line 625 of file parsed_method.cpp.
References WrappedClass::add_static_name(), ClassFunction::js_name, and static_method_renames.
Member Function Documentation
string StaticFunction::generate_js_bindings ()
Definition at line 724 of file parsed_method.cpp.
References ClassFunction::get_default_argument_tuple_string(), ClassFunction::get_return_and_parameter_types_string(), ClassFunction::js_name, and ClassFunction::name.
string StaticFunction::generate_js_stub ()
Definition at line 733 of file parsed_method.cpp.
References ClassFunction::get_js_input_parameter_string(), ClassFunction::TypeInfo::get_jsdoc_type_name(), ClassFunction::TypeInfo::is_void(), ClassFunction::js_name, ClassFunction::parameters, and ClassFunction::return_type.
string ClassFunction::get_default_argument_tuple_string () const inherited
Definition at line 427 of file parsed_method.cpp.
References get_type_string(), and ClassFunction::parameters.
Referenced by MemberFunction::generate_js_bindings(), generate_js_bindings(), and ConstructorFunction::generate_js_bindings().
string ClassFunction::get_signature_string () inherited
Definition at line 602 of file parsed_method.cpp.
References ClassFunction::name, and ClassFunction::parameters.
bool ClassFunction::compare_signatures (ClassFunction const & other) inherited
string ClassFunction::get_parameter_types_string () const inherited
Definition at line 487 of file parsed_method.cpp.
References ClassFunction::parameters.
Referenced by ConstructorFunction::generate_js_bindings(), ClassFunction::get_return_and_class_and_parameter_types_string(), and ClassFunction::get_return_and_parameter_types_string().
string ClassFunction::get_return_and_class_and_parameter_types_string () const inherited
Definition at line 463 of file parsed_method.cpp.
References ClassFunction::get_parameter_types_string(), ClassFunction::TypeInfo::name, ClassFunction::parameters, and ClassFunction::return_type.
Referenced by MemberFunction::generate_js_bindings().
string ClassFunction::get_return_and_parameter_types_string () const inherited
Definition at line 475 of file parsed_method.cpp.
References ClassFunction::get_parameter_types_string(), ClassFunction::TypeInfo::name, ClassFunction::parameters, and ClassFunction::return_type.
Referenced by generate_js_bindings().
string ClassFunction::get_js_input_parameter_string () const inherited
Definition at line 501 of file parsed_method.cpp.
References ClassFunction::parameters.
Referenced by MemberFunction::generate_js_stub(), generate_js_stub(), and ConstructorFunction::generate_js_stub().
Member Data Documentation
WrappedClass& ClassFunction::wrapped_class inherited
Definition at line 16 of file parsed_method.h.
Referenced by ClassFunction::ParameterInfo::ParameterInfo().
bool ClassFunction::is_static inherited
Definition at line 17 of file parsed_method.h.
bool ClassFunction::is_virtual inherited
Definition at line 18 of file parsed_method.h.
bool ClassFunction::new_virtual inherited
Definition at line 21 of file parsed_method.h.
TypeInfo ClassFunction::return_type inherited
Definition at line 87 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), MemberFunction::generate_js_stub(), generate_js_stub(), ClassFunction::get_return_and_class_and_parameter_types_string(), and ClassFunction::get_return_and_parameter_types_string().
string ClassFunction::return_type_comment inherited
Definition at line 88 of file parsed_method.h.
vector<ParameterInfo> ClassFunction::parameters inherited
Definition at line 89 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), generate_bidirectional_classes(), MemberFunction::generate_js_stub(), generate_js_stub(), ConstructorFunction::generate_js_stub(), ClassFunction::get_default_argument_tuple_string(), ClassFunction::get_js_input_parameter_string(), ClassFunction::get_parameter_types_string(), ClassFunction::get_return_and_class_and_parameter_types_string(), ClassFunction::get_return_and_parameter_types_string(), and ClassFunction::get_signature_string().
CXXMethodDecl const* ClassFunction::method_decl inherited
Definition at line 90 of file parsed_method.h.
Referenced by MemberFunction::generate_js_bindings().
string ClassFunction::name inherited
Definition at line 93 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), ConstructorFunction::ConstructorFunction(), MemberFunction::generate_js_bindings(), generate_js_bindings(), and ClassFunction::get_signature_string().
string ClassFunction::js_name inherited
Definition at line 96 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), ConstructorFunction::ConstructorFunction(), MemberFunction::generate_js_bindings(), generate_js_bindings(), ConstructorFunction::generate_js_bindings(), MemberFunction::generate_js_stub(), generate_js_stub(), MemberFunction::MemberFunction(), and StaticFunction().
CompilerInstance& ClassFunction::compiler_instance inherited
Definition at line 97 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), and ConstructorFunction::ConstructorFunction().
Annotations ClassFunction::annotations inherited
Definition at line 98 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction().
The documentation for this class was generated from the following files:
class_parser/parsed_method.h
class_parser/parsed_method.cpp