v8toolkit: JavaScriptFixture Class Reference
JavaScriptFixture Class Reference
#include <fixtures.h>
Public Types
typedef internal::SetUpTestCaseFunc SetUpTestCaseFunc
typedef internal::TearDownTestCaseFunc TearDownTestCaseFunc
Public Member Functions
JavaScriptFixture ()
void create_context ()
Static Public Member Functions
static void SetUpTestCase ()
static void TearDownTestCase ()
static bool HasFatalFailure ()
static bool HasNonfatalFailure ()
static bool HasFailure ()
static void RecordProperty (const std::string &key, const std::string &value)
static void RecordProperty (const std::string &key, int value)
Public Attributes
v8toolkit::IsolatePtr i
v8toolkit::ContextPtr c
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
Detailed Description
Definition at line 29 of file fixtures.h.
Member Typedef Documentation
typedef internal::SetUpTestCaseFunc testing::Test::SetUpTestCaseFunc inherited
Definition at line 377 of file gtest.h.
typedef internal::TearDownTestCaseFunc testing::Test::TearDownTestCaseFunc inherited
Definition at line 378 of file gtest.h.
Constructor & Destructor Documentation
JavaScriptFixture::JavaScriptFixture () inline
Definition at line 34 of file fixtures.h.
References v8toolkit::Platform::create_isolate().
Member Function Documentation
void JavaScriptFixture::create_context () inline
Definition at line 39 of file fixtures.h.
References v8toolkit::compare_contents(), EXPECT_TRUE, and v8toolkit::stringify_value().
static void testing::Test::SetUpTestCase () inline static inherited
Definition at line 389 of file gtest.h.
static void testing::Test::TearDownTestCase () inline static inherited
Definition at line 397 of file gtest.h.
static bool testing::Test::HasFatalFailure () static inherited
static bool testing::Test::HasNonfatalFailure () static inherited
static bool testing::Test::HasFailure () inline static inherited
Definition at line 407 of file gtest.h.
References GTEST_DISALLOW_COPY_AND_ASSIGN_.
static void testing::Test::RecordProperty (const std::string & key, const std::string & value) static inherited
static void testing::Test::RecordProperty (const std::string & key, int value) static inherited
virtual void testing::Test::SetUp () protected virtual inherited
Reimplemented in ExampleFixture.
virtual void testing::Test::TearDown () protected virtual inherited
Member Data Documentation
v8toolkit::IsolatePtr JavaScriptFixture::i
Definition at line 32 of file fixtures.h.
v8toolkit::ContextPtr JavaScriptFixture::c
Definition at line 33 of file fixtures.h.
The documentation for this class was generated from the following file:
test/fixtures.h