v8toolkit: testing::internal::TypedExpectation< F > Class Template Reference
testing::internal::TypedExpectation< F > Class Template Reference
#include <gmock-spec-builders.h>
Public Types
typedef Function< F >::ArgumentTuple ArgumentTuple
typedef Function< F >::ArgumentMatcherTuple ArgumentMatcherTuple
typedef Function< F >::Result Result
Public Member Functions
TypedExpectation (FunctionMockerBase< F > *owner, const char *a_file, int a_line, const string &a_source_text, const ArgumentMatcherTuple &m)
virtual ~TypedExpectation ()
TypedExpectation & With (const Matcher< const ArgumentTuple & > &m)
TypedExpectation & Times (const Cardinality &a_cardinality)
TypedExpectation & Times (int n)
TypedExpectation & InSequence (const Sequence &s)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4)
TypedExpectation & InSequence (const Sequence &s1, const Sequence &s2, const Sequence &s3, const Sequence &s4, const Sequence &s5)
TypedExpectation & After (const ExpectationSet &s)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4)
TypedExpectation & After (const ExpectationSet &s1, const ExpectationSet &s2, const ExpectationSet &s3, const ExpectationSet &s4, const ExpectationSet &s5)
TypedExpectation & WillOnce (const Action< F > &action)
TypedExpectation & WillRepeatedly (const Action< F > &action)
TypedExpectation & RetiresOnSaturation ()
const ArgumentMatcherTuple & matchers () const
const Matcher< const ArgumentTuple & > & extra_matcher () const
const Action< F > & repeated_action () const
virtual void MaybeDescribeExtraMatcherTo (::std::ostream *os)
const char * file () const
int line () const
const char * source_text () const
const Cardinality & cardinality () const
void DescribeLocationTo (::std::ostream *os) const
void DescribeCallCountTo (::std::ostream *os) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
Protected Types
enum Clause {
kNone, kWith, kTimes, kInSequence,
kAfter, kWillOnce, kWillRepeatedly, kRetiresOnSaturation
}
typedef std::vector< const void * > UntypedActions
Protected Member Functions
void AssertSpecProperty (bool property, const string &failure_message) const
void ExpectSpecProperty (bool property, const string &failure_message) const
void SpecifyCardinality (const Cardinality &cardinality)
bool cardinality_specified () const
void set_cardinality (const Cardinality &a_cardinality)
void RetireAllPreRequisites () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool is_retired () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void Retire () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool IsOverSaturated () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
bool AllPrerequisitesAreSatisfied () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void FindUnsatisfiedPrerequisites (ExpectationSet *result) const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
int call_count () const GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void IncrementCallCount () GTEST_EXCLUSIVE_LOCK_REQUIRED_(g_gmock_mutex)
void CheckActionCountIfNotDone () const GTEST_LOCK_EXCLUDED_(mutex_)
void UntypedTimes (const Cardinality &a_cardinality)
GTEST_DISALLOW_ASSIGN_ (ExpectationBase)
Protected Attributes
const char * file_
int line_
const string source_text_
bool cardinality_specified_
Cardinality cardinality_
ExpectationSet immediate_prerequisites_
int call_count_
bool retired_
UntypedActions untyped_actions_
bool extra_matcher_specified_
bool repeated_action_specified_
bool retires_on_saturation_
Clause last_clause_
bool action_count_checked_
Mutex mutex_
Friends
template<typename Function >
class FunctionMockerBase
Detailed Description
template<typename F>
class testing::internal::TypedExpectation< F >
Definition at line 99 of file gmock-spec-builders.h.
Member Typedef Documentation
template<typename F> typedef Function<F>::ArgumentTuple testing::internal::TypedExpectation< F >::ArgumentTuple
Definition at line 879 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::ArgumentMatcherTuple testing::internal::TypedExpectation< F >::ArgumentMatcherTuple
Definition at line 880 of file gmock-spec-builders.h.
template<typename F> typedef Function<F>::Result testing::internal::TypedExpectation< F >::Result
Definition at line 881 of file gmock-spec-builders.h.
typedef std::vector<const void*> testing::internal::ExpectationBase::UntypedActions protected inherited
Definition at line 734 of file gmock-spec-builders.h.
Member Enumeration Documentation
enum testing::internal::ExpectationBase::Clause protected inherited
Enumerator
kNone
kWith
kTimes
kInSequence
kAfter
kWillOnce
kWillRepeatedly
kRetiresOnSaturation
Definition at line 722 of file gmock-spec-builders.h.
Constructor & Destructor Documentation
template<typename F> testing::internal::TypedExpectation< F >::TypedExpectation (FunctionMockerBase< F > * owner, const char * a_file, int a_line, const string & a_source_text, const ArgumentMatcherTuple & m) inline
Definition at line 883 of file gmock-spec-builders.h.
template<typename F> virtual testing::internal::TypedExpectation< F >::~TypedExpectation () inline virtual
Definition at line 896 of file gmock-spec-builders.h.
Member Function Documentation
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::With (const Matcher< const ArgumentTuple & > & m) inline
Definition at line 907 of file gmock-spec-builders.h.
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (const Cardinality & a_cardinality) inline
Definition at line 925 of file gmock-spec-builders.h.
References testing::internal::ExpectationBase::UntypedTimes().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::Times (int n) inline
Definition at line 931 of file gmock-spec-builders.h.
References testing::Exactly().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s) inline
Definition at line 936 of file gmock-spec-builders.h.
References testing::Sequence::AddExpectation().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2) inline
Definition at line 946 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3) inline
Definition at line 949 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4) inline
Definition at line 953 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::InSequence (const Sequence & s1, const Sequence & s2, const Sequence & s3, const Sequence & s4, const Sequence & s5) inline
Definition at line 957 of file gmock-spec-builders.h.
References testing::InSequence::InSequence().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
Definition at line 964 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), and testing::ExpectationSet::end().
Referenced by testing::internal::TypedExpectation< F >::After().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2) inline
Definition at line 976 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3) inline
Definition at line 979 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4) inline
Definition at line 983 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s1, const ExpectationSet & s2, const ExpectationSet & s3, const ExpectationSet & s4, const ExpectationSet & s5) inline
Definition at line 987 of file gmock-spec-builders.h.
References testing::internal::TypedExpectation< F >::After().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillOnce (const Action< F > & action) inline
Definition at line 994 of file gmock-spec-builders.h.
References testing::Exactly().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::WillRepeatedly (const Action< F > & action) inline
Definition at line 1008 of file gmock-spec-builders.h.
References testing::AtLeast().
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::RetiresOnSaturation () inline
Definition at line 1033 of file gmock-spec-builders.h.
template<typename F> const ArgumentMatcherTuple& testing::internal::TypedExpectation< F >::matchers () const inline
Definition at line 1048 of file gmock-spec-builders.h.
template<typename F> const Matcher<const ArgumentTuple&>& testing::internal::TypedExpectation< F >::extra_matcher () const inline
Definition at line 1053 of file gmock-spec-builders.h.
template<typename F> const Action<F>& testing::internal::TypedExpectation< F >::repeated_action () const inline
Definition at line 1058 of file gmock-spec-builders.h.
template<typename F> virtual void testing::internal::TypedExpectation< F >::MaybeDescribeExtraMatcherTo (::std::ostream * os) inline virtual
Implements testing::internal::ExpectationBase.
Definition at line 1062 of file gmock-spec-builders.h.
const char* testing::internal::ExpectationBase::file () const inline inherited
Definition at line 698 of file gmock-spec-builders.h.
int testing::internal::ExpectationBase::line () const inline inherited
Definition at line 699 of file gmock-spec-builders.h.
const char* testing::internal::ExpectationBase::source_text () const inline inherited
Definition at line 700 of file gmock-spec-builders.h.
const Cardinality& testing::internal::ExpectationBase::cardinality () const inline inherited
Definition at line 702 of file gmock-spec-builders.h.
void testing::internal::ExpectationBase::DescribeLocationTo (::std::ostream * os) const inline inherited
Definition at line 705 of file gmock-spec-builders.h.
References testing::internal::FormatFileLocation(), and GTEST_EXCLUSIVE_LOCK_REQUIRED_.
void testing::internal::ExpectationBase::DescribeCallCountTo (::std::ostream * os) const inherited
void testing::internal::ExpectationBase::AssertSpecProperty (bool property, const string & failure_message) const inline protected inherited
Definition at line 741 of file gmock-spec-builders.h.
References testing::internal::Assert().
void testing::internal::ExpectationBase::ExpectSpecProperty (bool property, const string & failure_message) const inline protected inherited
Definition at line 746 of file gmock-spec-builders.h.
References testing::internal::Expect().
void testing::internal::ExpectationBase::SpecifyCardinality (const Cardinality & cardinality) protected inherited
bool testing::internal::ExpectationBase::cardinality_specified () const inline protected inherited
Definition at line 756 of file gmock-spec-builders.h.
void testing::internal::ExpectationBase::set_cardinality (const Cardinality & a_cardinality) inline protected inherited
Definition at line 759 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_.
void testing::internal::ExpectationBase::RetireAllPreRequisites () protected inherited
bool testing::internal::ExpectationBase::is_retired () const inline protected inherited
Definition at line 772 of file gmock-spec-builders.h.
void testing::internal::ExpectationBase::Retire () inline protected inherited
Definition at line 779 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::IsSatisfied () const inline protected inherited
Definition at line 786 of file gmock-spec-builders.h.
References testing::Cardinality::IsSatisfiedByCallCount().
bool testing::internal::ExpectationBase::IsSaturated () const inline protected inherited
Definition at line 793 of file gmock-spec-builders.h.
References testing::Cardinality::IsSaturatedByCallCount().
bool testing::internal::ExpectationBase::IsOverSaturated () const inline protected inherited
Definition at line 800 of file gmock-spec-builders.h.
References GTEST_EXCLUSIVE_LOCK_REQUIRED_, and testing::Cardinality::IsOverSaturatedByCallCount().
bool testing::internal::ExpectationBase::AllPrerequisitesAreSatisfied () const protected inherited
void testing::internal::ExpectationBase::FindUnsatisfiedPrerequisites (ExpectationSet * result) const protected inherited
int testing::internal::ExpectationBase::call_count () const inline protected inherited
Definition at line 815 of file gmock-spec-builders.h.
void testing::internal::ExpectationBase::IncrementCallCount () inline protected inherited
Definition at line 822 of file gmock-spec-builders.h.
References GTEST_LOCK_EXCLUDED_.
void testing::internal::ExpectationBase::CheckActionCountIfNotDone () const protected inherited
void testing::internal::ExpectationBase::UntypedTimes (const Cardinality & a_cardinality) protected inherited
Referenced by testing::internal::TypedExpectation< F >::Times().
testing::internal::ExpectationBase::GTEST_DISALLOW_ASSIGN_ (ExpectationBase) protected inherited
Friends And Related Function Documentation
template<typename F> template<typename Function > friend class FunctionMockerBase friend
Definition at line 1072 of file gmock-spec-builders.h.
Member Data Documentation
const char* testing::internal::ExpectationBase::file_ protected inherited
Definition at line 846 of file gmock-spec-builders.h.
int testing::internal::ExpectationBase::line_ protected inherited
Definition at line 847 of file gmock-spec-builders.h.
const string testing::internal::ExpectationBase::source_text_ protected inherited
Definition at line 848 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::cardinality_specified_ protected inherited
Definition at line 850 of file gmock-spec-builders.h.
Cardinality testing::internal::ExpectationBase::cardinality_ protected inherited
Definition at line 851 of file gmock-spec-builders.h.
ExpectationSet testing::internal::ExpectationBase::immediate_prerequisites_ protected inherited
Definition at line 858 of file gmock-spec-builders.h.
int testing::internal::ExpectationBase::call_count_ protected inherited
Definition at line 862 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::retired_ protected inherited
Definition at line 863 of file gmock-spec-builders.h.
UntypedActions testing::internal::ExpectationBase::untyped_actions_ protected inherited
Definition at line 864 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::extra_matcher_specified_ protected inherited
Definition at line 865 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::repeated_action_specified_ protected inherited
Definition at line 866 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::retires_on_saturation_ protected inherited
Definition at line 867 of file gmock-spec-builders.h.
Clause testing::internal::ExpectationBase::last_clause_ protected inherited
Definition at line 868 of file gmock-spec-builders.h.
bool testing::internal::ExpectationBase::action_count_checked_ mutable protected inherited
Definition at line 869 of file gmock-spec-builders.h.
Mutex testing::internal::ExpectationBase::mutex_ mutable protected inherited
Definition at line 870 of file gmock-spec-builders.h.
The documentation for this class was generated from the following file:
test/googletest/googlemock/include/gmock/gmock-spec-builders.h