v8toolkit: ClassFunction::ParameterInfo Class Reference
ClassFunction::ParameterInfo Class Reference
#include <parsed_method.h>
Public Member Functions
ParameterInfo (ClassFunction &method, int position, ParmVarDecl const *parameter_decl, CompilerInstance &compiler_instance)
string generate_js_stub ()
Public Attributes
TypeInfo const type
Protected Attributes
ClassFunction & method
CompilerInstance & compiler_instance
ParmVarDecl const * parameter_decl
int position
string name
string default_value
string description = ""
Friends
class ClassFunction
Detailed Description
Definition at line 64 of file parsed_method.h.
Constructor & Destructor Documentation
ClassFunction::ParameterInfo::ParameterInfo (ClassFunction & method, int position, ParmVarDecl const * parameter_decl, CompilerInstance & compiler_instance)
Definition at line 217 of file parsed_method.cpp.
References data_warning(), default_value, get_source_for_source_range(), ClassFunction::TypeInfo::name, name, WrappedClass::name_alias, ClassFunction::TypeInfo::plain_without_const(), type, and ClassFunction::wrapped_class.
Member Function Documentation
string ClassFunction::ParameterInfo::generate_js_stub ()
Definition at line 202 of file parsed_method.cpp.
References ClassFunction::TypeInfo::get_jsdoc_type_name(), and DataMember::type.
Friends And Related Function Documentation
friend class ClassFunction friend
Definition at line 65 of file parsed_method.h.
Member Data Documentation
ClassFunction& ClassFunction::ParameterInfo::method protected
Definition at line 67 of file parsed_method.h.
CompilerInstance& ClassFunction::ParameterInfo::compiler_instance protected
Definition at line 68 of file parsed_method.h.
ParmVarDecl const* ClassFunction::ParameterInfo::parameter_decl protected
Definition at line 69 of file parsed_method.h.
int ClassFunction::ParameterInfo::position protected
Definition at line 70 of file parsed_method.h.
string ClassFunction::ParameterInfo::name protected
Definition at line 71 of file parsed_method.h.
Referenced by ParameterInfo().
string ClassFunction::ParameterInfo::default_value protected
Definition at line 72 of file parsed_method.h.
Referenced by ParameterInfo().
string ClassFunction::ParameterInfo::description = "" protected
Definition at line 75 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction().
TypeInfo const ClassFunction::ParameterInfo::type
Definition at line 82 of file parsed_method.h.
Referenced by ParameterInfo().
The documentation for this class was generated from the following files:
class_parser/parsed_method.h
class_parser/parsed_method.cpp