v8toolkit: func Namespace Reference
func Namespace Reference
Namespaces
detail
Classes
struct bad_function_call
struct force_function_heap_allocation
class function
class function< Result(Arguments...)>
Functions
template<typename T >
bool operator== (std::nullptr_t, const function< T > &rhs) FUNC_NOEXCEPT
template<typename T >
bool operator== (const function< T > &lhs, std::nullptr_t) FUNC_NOEXCEPT
template<typename T >
bool operator!= (std::nullptr_t, const function< T > &rhs) FUNC_NOEXCEPT
template<typename T >
bool operator!= (const function< T > &lhs, std::nullptr_t) FUNC_NOEXCEPT
template<typename T >
void swap (function< T > &lhs, function< T > &rhs)
Class Documentation
class func::function
template<typename>
class func::function< typename >
Definition at line 48 of file stdfunctionreplacement.h.
Function Documentation
template<typename T > bool func::operator== (std::nullptr_t , const function< T > & rhs)
Definition at line 560 of file stdfunctionreplacement.h.
template<typename T > bool func::operator== (const function< T > & lhs, std::nullptr_t)
Definition at line 565 of file stdfunctionreplacement.h.
template<typename T > bool func::operator!= (std::nullptr_t , const function< T > & rhs)
Definition at line 570 of file stdfunctionreplacement.h.
template<typename T > bool func::operator!= (const function< T > & lhs, std::nullptr_t)
Definition at line 575 of file stdfunctionreplacement.h.
template<typename T > void func::swap (function< T > & lhs, function< T > & rhs)
Definition at line 581 of file stdfunctionreplacement.h.
Referenced by func::function< Result(Arguments...)>::function(), testing::AssertionResult::operator<<(), testing::AssertionResult::operator=(), and testing::internal::ShuffleRange().