v8toolkit: testing::internal Namespace Reference
testing::internal Namespace Reference
Namespaces
edit_distance
invoke_argument
posix
Classes
class ActionAdaptor
class ActionHelper
class ActionResultHolder
class ActionResultHolder< void >
struct AddReference
struct AddReference< T & >
struct AllOfResult1
struct AllOfResult10
struct AllOfResult2
struct AllOfResult3
struct AllOfResult4
struct AllOfResult5
struct AllOfResult6
struct AllOfResult7
struct AllOfResult8
struct AllOfResult9
struct AnyEq
struct AnyGe
struct AnyGt
struct AnyLe
struct AnyLt
class AnyMatcherImpl
struct AnyNe
struct AnyOfResult1
struct AnyOfResult10
struct AnyOfResult2
struct AnyOfResult3
struct AnyOfResult4
struct AnyOfResult5
struct AnyOfResult6
struct AnyOfResult7
struct AnyOfResult8
struct AnyOfResult9
class AnythingMatcher
class ArgsMatcher
class ArgsMatcherImpl
class AssertHelper
class AssignAction
class BeginEndDistanceIsMatcher
struct bool_constant
struct BooleanConstant
class BothOfMatcher
class BothOfMatcherImpl
class BoundSecondMatcher
class BuiltInDefaultValue
class BuiltInDefaultValue< const T >
class BuiltInDefaultValue< T * >
struct BuiltInDefaultValueGetter
struct BuiltInDefaultValueGetter< T, false >
struct ByMoveWrapper
struct CallableTraits
struct CallableTraits< ResType(*)(ArgType)>
struct CastAndAppendTransform
struct CodeLocation
class ComparisonBase
struct CompileAssert
struct CompileAssertTypesEqual
struct CompileAssertTypesEqual< T, T >
struct ConstCharPtr
class ContainerEqMatcher
class ContainsMatcher
class ContainsMatcherImpl
struct DecayArray
struct DecayArray< T[]>
struct DecayArray< T[N]>
class DefaultGlobalTestPartResultReporter
class DefaultPerThreadTestPartResultReporter
class DoBothAction
class DoDefaultAction
class DummyMatchResultListener
class EachMatcher
class EachMatcherImpl
class EitherOfMatcher
class EitherOfMatcherImpl
class ElementsAreArrayMatcher
class ElementsAreMatcher
class ElementsAreMatcherImpl
struct EnableIf
struct EnableIf< true >
class EndsWithMatcher
class Eq2Matcher
class EqHelper
class EqHelper< true >
class EqMatcher
struct ExcessiveArg
class ExpectationBase
class FieldMatcher
class FilePath
class FloatingEqMatcher
class FloatingPoint
class FormatForComparison
class FormatForComparison< ToPrint[N], OtherOperand >
struct Function
struct Function< R(A1)>
struct Function< R(A1, A2)>
struct Function< R(A1, A2, A3)>
struct Function< R(A1, A2, A3, A4)>
struct Function< R(A1, A2, A3, A4, A5)>
struct Function< R(A1, A2, A3, A4, A5, A6)>
struct Function< R(A1, A2, A3, A4, A5, A6, A7)>
struct Function< R(A1, A2, A3, A4, A5, A6, A7, A8)>
struct Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
struct Function< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>
class FunctionMocker
class FunctionMocker< R(A1)>
class FunctionMocker< R(A1, A2)>
class FunctionMocker< R(A1, A2, A3)>
class FunctionMocker< R(A1, A2, A3, A4)>
class FunctionMocker< R(A1, A2, A3, A4, A5)>
class FunctionMocker< R(A1, A2, A3, A4, A5, A6)>
class FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>
class FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>
class FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>
class FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>
class FunctionMockerBase
class Ge2Matcher
class GeMatcher
class Gt2Matcher
class GTestFlagSaver
class GTestLog
class GTestMutexLock
class GtMatcher
class HasNewFatalFailureHelper
class HasSubstrMatcher
class IgnoredValue
class IgnoreResultAction
class ImplicitlyConvertible
class InvokeAction
class InvokeHelper
class InvokeHelper< R,::testing::tuple< A1 > >
class InvokeHelper< R,::testing::tuple< A1, A2 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4, A5 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4, A5, A6 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4, A5, A6, A7 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9 > >
class InvokeHelper< R,::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 > >
class InvokeHelper< R,::testing::tuple<> >
class InvokeMethodAction
class InvokeMethodWithoutArgsAction
class InvokeWithoutArgsAction
struct is_pointer
struct is_pointer< T * >
struct is_reference
struct is_reference< T & >
struct IsAProtocolMessage
class IsNullMatcher
struct IteratorTraits
struct IteratorTraits< const T * >
struct IteratorTraits< T * >
class KeyMatcher
class KeyMatcherImpl
struct KindOf
class Le2Matcher
class LeMatcher
struct LessComparator
class linked_ptr
class linked_ptr_internal
struct LinkedPtrLessThan
struct LosslessArithmeticConvertibleImpl
struct LosslessArithmeticConvertibleImpl< kBool, bool, kBool, bool >
struct LosslessArithmeticConvertibleImpl< kBool, bool, kFloatingPoint, To >
struct LosslessArithmeticConvertibleImpl< kBool, bool, kInteger, To >
struct LosslessArithmeticConvertibleImpl< kFloatingPoint, From, kBool, bool >
struct LosslessArithmeticConvertibleImpl< kFloatingPoint, From, kInteger, To >
struct LosslessArithmeticConvertibleImpl< kInteger, From, kBool, bool >
struct LosslessArithmeticConvertibleImpl< kInteger, From, kFloatingPoint, To >
struct LosslessArithmeticConvertibleImpl< kInteger, From, kInteger, To >
class Lt2Matcher
class LtMatcher
class MatcherAsPredicate
class MatcherBase
class MatcherCastImpl
class MatcherCastImpl< T, Matcher< T > >
class MatcherCastImpl< T, Matcher< U > >
struct MatcherTuple
struct MatcherTuple< ::testing::tuple< A1 > >
struct MatcherTuple< ::testing::tuple< A1, A2 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9 > >
struct MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 > >
struct MatcherTuple< ::testing::tuple<> >
class MatchesRegexMatcher
class MatchMatrix
class MockSpec
class Mutex
class NativeArray
class Ne2Matcher
class NeMatcher
class NotMatcher
class NotMatcherImpl
class NotNullMatcher
class OnCallSpec
class OsStackTraceGetter
class OsStackTraceGetterInterface
class PairMatchBase
class PairMatcher
class PairMatcherImpl
class PointeeMatcher
struct PointeeOf
struct PointeeOf< T * >
class PointwiseMatcher
class PredicateFormatterFromMatcher
class PropertyMatcher
class QuantifierMatcherImpl
class Random
class RE
class ReferenceOrValueWrapper
class ReferenceOrValueWrapper< T & >
class ReferenceWrapper
class RefMatcher
class RefMatcher< T & >
struct RelationToSourceCopy
struct RelationToSourceReference
struct remove_reference
struct remove_reference< T & >
struct RemoveConst
struct RemoveConst< const T >
struct RemoveConst< const T[N]>
struct RemoveConstFromKey
struct RemoveConstFromKey< std::pair< const K, V > >
struct RemoveReference
struct RemoveReference< T & >
class ResultOfMatcher
class ReturnAction
class ReturnNullAction
class ReturnRefAction
class ReturnRefOfCopyAction
class ReturnVoidAction
class scoped_ptr
class ScopedTrace
class SelectArgs
class SelectArgs< Result, ArgumentTuple, -1,-1,-1,-1,-1,-1,-1,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3, k4, k5, k6, k7, k8, k9,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3, k4, k5, k6, k7, k8,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3, k4, k5, k6, k7,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3, k4, k5, k6,-1,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3, k4, k5,-1,-1,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3, k4,-1,-1,-1,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2, k3,-1,-1,-1,-1,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1, k2,-1,-1,-1,-1,-1,-1,-1,-1 >
class SelectArgs< Result, ArgumentTuple, k1,-1,-1,-1,-1,-1,-1,-1,-1,-1 >
class SetArgumentPointeeAction
class SetArgumentPointeeAction< N, Proto, true >
class SetErrnoAndReturnAction
class SingleFailureChecker
class SizeIsMatcher
class StartsWithMatcher
struct StaticAssertTypeEqHelper
struct StaticAssertTypeEqHelper< T, T >
class StlContainerView
class StlContainerView< ::testing::tuple< ElementPointer, Size > >
class StlContainerView< Element[N]>
class StreamMatchResultListener
class StrEqualityMatcher
class String
class TestFactoryBase
class TestFactoryImpl
class TestPropertyKeyIs
class TestResultAccessor
class ThreadLocal
struct TraceInfo
class TransformTupleValuesHelper
class TrulyMatcher
class TupleFields
class TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6, k7, k8,-1 >
class TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6, k7,-1,-1 >
class TupleFields< Tuple, k0, k1, k2, k3, k4, k5, k6,-1,-1,-1 >
class TupleFields< Tuple, k0, k1, k2, k3, k4, k5,-1,-1,-1,-1 >
class TupleFields< Tuple, k0, k1, k2, k3, k4,-1,-1,-1,-1,-1 >
class TupleFields< Tuple, k0, k1, k2, k3,-1,-1,-1,-1,-1,-1 >
class TupleFields< Tuple, k0, k1, k2,-1,-1,-1,-1,-1,-1,-1 >
class TupleFields< Tuple, k0, k1,-1,-1,-1,-1,-1,-1,-1,-1 >
class TupleFields< Tuple, k0,-1,-1,-1,-1,-1,-1,-1,-1,-1 >
class TupleFields< Tuple,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1 >
struct TuplePolicy
class TuplePrefix
class TuplePrefix< 0 >
struct type_equals
struct type_equals< T, T >
class TypedExpectation
class TypeIdHelper
class TypeWithSize
class TypeWithSize< 4 >
class TypeWithSize< 8 >
class UnitTestImpl
class UnitTestOptions
class UniversalPrinter
class UniversalPrinter< T & >
class UniversalPrinter< T[N]>
class UniversalTersePrinter
class UniversalTersePrinter< char * >
class UniversalTersePrinter< const char * >
class UniversalTersePrinter< T & >
class UniversalTersePrinter< T[N]>
class UniversalTersePrinter< wchar_t * >
class UnorderedElementsAreArrayMatcher
class UnorderedElementsAreMatcher
class UnorderedElementsAreMatcherImpl
class UnorderedElementsAreMatcherImplBase
class UntypedActionResultHolderBase
class UntypedFunctionMockerBase
class UntypedOnCallSpecBase
class WhenDynamicCastToMatcher
class WhenDynamicCastToMatcher< To & >
class WhenDynamicCastToMatcherBase
class WhenSortedByMatcher
class WithArgsAction
Typedefs
typedef ::std::pair< size_t, size_t > ElementMatcherPair
typedef ::std::vector< ElementMatcherPair > ElementMatcherPairs
typedef ::std::vector< string > Strings
typedef FloatingPoint< float > Float
typedef FloatingPoint< double > Double
typedef const void * TypeId
typedef void(* SetUpTestCaseFunc) ()
typedef void(* TearDownTestCaseFunc) ()
typedef int IsContainer
typedef char IsNotContainer
typedef ::std::string string
typedef ::std::wstring wstring
typedef GTestMutexLock MutexLock
typedef bool_constant< false > false_type
typedef bool_constant< true > true_type
typedef long long BiggestInt
typedef TypeWithSize< 4 >::Int Int32
typedef TypeWithSize< 4 >::UInt UInt32
typedef TypeWithSize< 8 >::Int Int64
typedef TypeWithSize< 8 >::UInt UInt64
typedef TypeWithSize< 8 >::Int TimeInMillis
Enumerations
enum CallReaction { kAllow, kWarn, kFail, kDefault = kWarn }
enum TypeKind { kBool, kInteger, kFloatingPoint, kOther }
enum LogSeverity { kInfo = 0, kWarning = 1 }
enum GTestLogSeverity { GTEST_INFO, GTEST_WARNING, GTEST_ERROR, GTEST_FATAL }
Functions
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (void,)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (::std::string,"")
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (bool, false)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (unsigned char, '\0')
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (signed char, '\0')
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (char, '\0')
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (unsigned short, 0U)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (signed short, 0)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (unsigned long, 0UL)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (signed long, 0L)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (UInt64, 0)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (Int64, 0)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (float, 0)
GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (double, 0)
template<typename T >
void PrintTo (const ReferenceWrapper< T > &ref,::std::ostream *os)
void PrintIfNotEmpty (const internal::string &explanation,::std::ostream *os)
bool IsReadableTypeName (const string &type_name)
template<typename Value , typename T >
bool MatchPrintAndExplain (Value &value, const Matcher< T > &matcher, MatchResultListener *listener)
template<typename MatcherTuple , typename ValueTuple >
bool TupleMatches (const MatcherTuple &matcher_tuple, const ValueTuple &value_tuple)
template<typename MatcherTuple , typename ValueTuple >
void ExplainMatchFailureTupleTo (const MatcherTuple &matchers, const ValueTuple &values,::std::ostream *os)
template<typename Tuple , typename Func , typename OutIter >
OutIter TransformTupleValues (Func f, const Tuple &t, OutIter out)
bool CaseInsensitiveCStringEquals (const char *lhs, const char *rhs)
bool CaseInsensitiveCStringEquals (const wchar_t *lhs, const wchar_t *rhs)
template<typename StringType >
bool CaseInsensitiveStringEquals (const StringType &s1, const StringType &s2)
template<typename M >
PredicateFormatterFromMatcher< M > MakePredicateFormatterFromMatcher (M matcher)
GTEST_API_ ElementMatcherPairs FindMaxBipartiteMatching (const MatchMatrix &g)
GTEST_API_ bool FindPairing (const MatchMatrix &matrix, MatchResultListener *listener)
template<typename Tuple2Matcher , typename Second >
BoundSecondMatcher< Tuple2Matcher, Second > MatcherBindSecond (const Tuple2Matcher &tm, const Second &second)
GTEST_API_ string FormatMatcherDescription (bool negation, const char *matcher_name, const Strings &param_values)
template<typename InputIterator , typename OutputIterator >
OutputIterator CopyElements (InputIterator first, InputIterator last, OutputIterator output)
GTEST_API_ GTEST_DECLARE_STATIC_MUTEX_ (g_gmock_mutex)
GTEST_API_ void LogWithLocation (testing::internal::LogSeverity severity, const char *file, int line, const string &message)
void ReportUninterestingCall (CallReaction reaction, const string &msg)
GTEST_API_ string ConvertIdentifierNameToWords (const char *id_name)
template<typename Pointer >
const Pointer::element_type * GetRawPointer (const Pointer &p)
template<typename Element >
Element * GetRawPointer (Element *p)
GMOCK_DECLARE_KIND_ (bool, kBool)
GMOCK_DECLARE_KIND_ (char, kInteger)
GMOCK_DECLARE_KIND_ (signed char, kInteger)
GMOCK_DECLARE_KIND_ (unsigned char, kInteger)
GMOCK_DECLARE_KIND_ (short, kInteger)
GMOCK_DECLARE_KIND_ (int, kInteger)
GMOCK_DECLARE_KIND_ (long, kInteger)
GMOCK_DECLARE_KIND_ (wchar_t, kInteger)
GMOCK_DECLARE_KIND_ (Int64, kInteger)
GMOCK_DECLARE_KIND_ (UInt64, kInteger)
GMOCK_DECLARE_KIND_ (float, kFloatingPoint)
GMOCK_DECLARE_KIND_ (double, kFloatingPoint)
GMOCK_DECLARE_KIND_ (long double, kFloatingPoint)
template<typename From , typename To >
void Assert (bool condition, const char *file, int line)
void Expect (bool condition, const char *file, int line, const string &msg)
void Expect (bool condition, const char *file, int line)
GTEST_API_ bool LogIsVisible (LogSeverity severity)
GTEST_API_ void Log (LogSeverity severity, const string &message, int stack_frames_to_skip)
template<typename T >
T Invalid ()
template<typename T >
std::string StreamableToString (const T &streamable)
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (char)
GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (wchar_t)
GTEST_IMPL_FORMAT_C_STRING_AS_STRING_ (char,::std::string)
template<typename T1 , typename T2 >
std::string FormatForComparisonFailureMessage (const T1 &value, const T2 &)
template<typename T >
void UniversalPrint (const T &value,::std::ostream *os)
template<typename C >
void DefaultPrintTo (IsContainer, false_type, const C &container,::std::ostream *os)
template<typename T >
void DefaultPrintTo (IsNotContainer, true_type, T *p,::std::ostream *os)
template<typename T >
void DefaultPrintTo (IsNotContainer, false_type, const T &value,::std::ostream *os)
template<typename T >
void PrintTo (const T &value,::std::ostream *os)
GTEST_API_ void PrintTo (unsigned char c,::std::ostream *os)
GTEST_API_ void PrintTo (signed char c,::std::ostream *os)
void PrintTo (char c,::std::ostream *os)
void PrintTo (bool x,::std::ostream *os)
GTEST_API_ void PrintTo (wchar_t wc,::std::ostream *os)
GTEST_API_ void PrintTo (const char *s,::std::ostream *os)
void PrintTo (char *s,::std::ostream *os)
void PrintTo (const signed char *s,::std::ostream *os)
void PrintTo (signed char *s,::std::ostream *os)
void PrintTo (const unsigned char *s,::std::ostream *os)
void PrintTo (unsigned char *s,::std::ostream *os)
GTEST_API_ void PrintTo (const wchar_t *s,::std::ostream *os)
void PrintTo (wchar_t *s,::std::ostream *os)
template<typename T >
void PrintRawArrayTo (const T a[], size_t count,::std::ostream *os)
GTEST_API_ void PrintStringTo (const ::std::string &s,::std::ostream *os)
void PrintTo (const ::std::string &s,::std::ostream *os)
template<typename T1 , typename T2 >
void PrintTo (const ::std::pair< T1, T2 > &value,::std::ostream *os)
template<typename T >
void UniversalPrintArray (const T *begin, size_t len,::std::ostream *os)
GTEST_API_ void UniversalPrintArray (const char *begin, size_t len,::std::ostream *os)
GTEST_API_ void UniversalPrintArray (const wchar_t *begin, size_t len,::std::ostream *os)
template<typename T >
void UniversalTersePrint (const T &value,::std::ostream *os)
class UnitTestImpl * GetUnitTestImpl ()
void ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string &message)
template<typename T1 , typename T2 >
AssertionResult CmpHelperEQFailure (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
template<typename T1 , typename T2 >
AssertionResult CmpHelperEQ (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
GTEST_API_ AssertionResult CmpHelperEQ (const char *lhs_expression, const char *rhs_expression, BiggestInt lhs, BiggestInt rhs)
template<typename T1 , typename T2 >
AssertionResult CmpHelperOpFailure (const char *expr1, const char *expr2, const T1 &val1, const T2 &val2, const char *op)
GTEST_IMPL_CMP_HELPER_ (NE,!=)
GTEST_IMPL_CMP_HELPER_ (LE,<=)
GTEST_IMPL_CMP_HELPER_ (LT,<)
GTEST_IMPL_CMP_HELPER_ (GE, >=)
GTEST_IMPL_CMP_HELPER_ (GT, >)
GTEST_API_ AssertionResult CmpHelperSTREQ (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
GTEST_API_ AssertionResult CmpHelperSTRCASEEQ (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
GTEST_API_ AssertionResult CmpHelperSTRNE (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
GTEST_API_ AssertionResult CmpHelperSTRCASENE (const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
GTEST_API_ AssertionResult CmpHelperSTREQ (const char *s1_expression, const char *s2_expression, const wchar_t *s1, const wchar_t *s2)
GTEST_API_ AssertionResult CmpHelperSTRNE (const char *s1_expression, const char *s2_expression, const wchar_t *s1, const wchar_t *s2)
template<typename RawType >
AssertionResult CmpHelperFloatingPointEQ (const char *lhs_expression, const char *rhs_expression, RawType lhs_value, RawType rhs_value)
GTEST_API_ AssertionResult DoubleNearPredFormat (const char *expr1, const char *expr2, const char *abs_error_expr, double val1, double val2, double abs_error)
GTEST_DECLARE_string_ (internal_run_death_test)
char IsNullLiteralHelper (Secret *p)
char(& IsNullLiteralHelper (...))[2]
GTEST_API_ std::string AppendUserMessage (const std::string &gtest_msg, const Message &user_msg)
GTEST_API_ std::string DiffStrings (const std::string &left, const std::string &right, size_t *total_line_count)
GTEST_API_ AssertionResult EqFailure (const char *expected_expression, const char *actual_expression, const std::string &expected_value, const std::string &actual_value, bool ignoring_case)
GTEST_API_ std::string GetBoolAssertionFailureMessage (const AssertionResult &assertion_result, const char *expression_text, const char *actual_predicate_value, const char *expected_predicate_value)
template<typename T >
TypeId GetTypeId ()
GTEST_API_ TypeId GetTestTypeId ()
GTEST_API_ TestInfo * MakeAndRegisterTestInfo (const char *test_case_name, const char *name, const char *type_param, const char *value_param, CodeLocation code_location, TypeId fixture_class_id, SetUpTestCaseFunc set_up_tc, TearDownTestCaseFunc tear_down_tc, TestFactoryBase *factory)
GTEST_API_ bool SkipPrefix (const char *prefix, const char **pstr)
GTEST_API_ std::string GetCurrentOsStackTraceExceptTop (UnitTest *unit_test, int skip_count)
GTEST_API_ bool AlwaysTrue ()
bool AlwaysFalse ()
template<class C >
IsContainer IsContainerTest (int, typename C::iterator *=NULL, typename C::const_iterator *=NULL)
template<class C >
IsNotContainer IsContainerTest (long)
template<typename T , typename U >
bool ArrayEq (const T *lhs, size_t size, const U *rhs)
template<typename T , typename U >
bool ArrayEq (const T &lhs, const U &rhs)
template<typename T , typename U , size_t N>
bool ArrayEq (const T(&lhs)[N], const U(&rhs)[N])
template<typename Iter , typename Element >
Iter ArrayAwareFind (Iter begin, Iter end, const Element &elem)
template<typename T , typename U >
void CopyArray (const T *from, size_t size, U *to)
template<typename T , typename U >
void CopyArray (const T &from, U *to)
template<typename T , typename U , size_t N>
void CopyArray (const T(&from)[N], U(*to)[N])
GTEST_API_ GTEST_DECLARE_STATIC_MUTEX_ (g_linked_ptr_mutex)
template<typename T >
bool operator== (T *ptr, const linked_ptr< T > &x)
template<typename T >
bool operator!= (T *ptr, const linked_ptr< T > &x)
template<typename T >
linked_ptr< T > make_linked_ptr (T *ptr)
GTEST_API_ bool IsTrue (bool condition)
GTEST_API_::std::string FormatFileLocation (const char *file, int line)
GTEST_API_::std::string FormatCompilerIndependentFileLocation (const char *file, int line)
void LogToStderr ()
void FlushInfoLog ()
template<typename T >
const T & move (const T &t)
template<typename To >
To ImplicitCast_ (To x)
template<typename To , typename From >
To DownCast_ (From *f)
template<class Derived , class Base >
Derived * CheckedDowncastToActualType (Base *base)
GTEST_API_ void CaptureStdout ()
GTEST_API_ std::string GetCapturedStdout ()
GTEST_API_ void CaptureStderr ()
GTEST_API_ std::string GetCapturedStderr ()
GTEST_API_ std::string TempDir ()
GTEST_API_ size_t GetFileSize (FILE *file)
GTEST_API_ std::string ReadEntireFile (FILE *file)
GTEST_API_ const ::std::vector< testing::internal::string > & GetArgvs ()
GTEST_API_ size_t GetThreadCount ()
bool IsAlpha (char ch)
bool IsAlNum (char ch)
bool IsDigit (char ch)
bool IsLower (char ch)
bool IsSpace (char ch)
bool IsUpper (char ch)
bool IsXDigit (char ch)
bool IsXDigit (wchar_t ch)
char ToLower (char ch)
char ToUpper (char ch)
std::string StripTrailingSpaces (std::string str)
bool ParseInt32 (const Message &src_text, const char *str, Int32 *value)
bool BoolFromGTestEnv (const char *flag, bool default_val)
GTEST_API_ Int32 Int32FromGTestEnv (const char *flag, Int32 default_val)
std::string StringFromGTestEnv (const char *flag, const char *default_val)
GTEST_API_ std::string StringStreamToString (::std::stringstream *stream)
template<typename T >
std::string GetTypeName ()
GTEST_API_ TimeInMillis GetTimeInMillis ()
GTEST_API_ bool ShouldUseColor (bool stdout_is_tty)
GTEST_API_ std::string FormatTimeInMillisAsSeconds (TimeInMillis ms)
GTEST_API_ std::string FormatEpochTimeInMillisAsIso8601 (TimeInMillis ms)
GTEST_API_ bool ParseInt32Flag (const char *str, const char *flag, Int32 *value)
int GetRandomSeedFromFlag (Int32 random_seed_flag)
int GetNextRandomSeed (int seed)
GTEST_API_ std::string CodePointToUtf8 (UInt32 code_point)
GTEST_API_ std::string WideStringToUtf8 (const wchar_t *str, int num_chars)
void WriteToShardStatusFileIfNeeded ()
GTEST_API_ bool ShouldShard (const char *total_shards_str, const char *shard_index_str, bool in_subprocess_for_death_test)
GTEST_API_ Int32 Int32FromEnvOrDie (const char *env_var, Int32 default_val)
GTEST_API_ bool ShouldRunTestOnShard (int total_shards, int shard_index, int test_id)
template<class Container , typename Predicate >
int CountIf (const Container &c, Predicate predicate)
template<class Container , typename Functor >
void ForEach (const Container &c, Functor functor)
template<typename E >
E GetElementOr (const std::vector< E > &v, int i, E default_value)
template<typename E >
void ShuffleRange (internal::Random *random, int begin, int end, std::vector< E > *v)
template<typename E >
void Shuffle (internal::Random *random, std::vector< E > *v)
template<typename T >
static void Delete (T *x)
GTEST_API_ FilePath GetCurrentExecutableName ()
GTEST_API_ void ParseGoogleTestFlagsOnly (int *argc, char **argv)
GTEST_API_ void ParseGoogleTestFlagsOnly (int *argc, wchar_t **argv)
Variables
GTEST_API_ ThreadLocal< Sequence * > g_gmock_implicit_sequence
const char kInfoVerbosity [] = "info"
const char kWarningVerbosity [] = "warning"
const char kErrorVerbosity [] = "error"
const char kDeathTestStyleFlag [] = "death_test_style"
const char kDeathTestUseFork [] = "death_test_use_fork"
const char kInternalRunDeathTestFlag [] = "internal_run_death_test"
GTEST_API_ const char kStackTraceMarker []
class GTEST_API_ testing::internal::ScopedTrace GTEST_ATTRIBUTE_UNUSED_
const BiggestInt kMaxBiggestInt
GTEST_API_ const TypeId kTestTypeIdInGoogleTest
const char kAlsoRunDisabledTestsFlag [] = "also_run_disabled_tests"
const char kBreakOnFailureFlag [] = "break_on_failure"
const char kCatchExceptionsFlag [] = "catch_exceptions"
const char kColorFlag [] = "color"
const char kFilterFlag [] = "filter"
const char kListTestsFlag [] = "list_tests"
const char kOutputFlag [] = "output"
const char kPrintTimeFlag [] = "print_time"
const char kRandomSeedFlag [] = "random_seed"
const char kRepeatFlag [] = "repeat"
const char kShuffleFlag [] = "shuffle"
const char kStackTraceDepthFlag [] = "stack_trace_depth"
const char kStreamResultToFlag [] = "stream_result_to"
const char kThrowOnFailureFlag [] = "throw_on_failure"
const char kFlagfileFlag [] = "flagfile"
const int kMaxRandomSeed = 99999
GTEST_API_ bool g_help_flag
Class Documentation
struct testing::internal::AddReference
template<typename T>
struct testing::internal::AddReference< T >
Definition at line 830 of file gtest-internal.h.
Class Members
typedef T & type
struct testing::internal::AddReference< T & >
template<typename T>
struct testing::internal::AddReference< T & >
Definition at line 832 of file gtest-internal.h.
Class Members
typedef T & type
struct testing::internal::AllOfResult1
template<typename M1>
struct testing::internal::AllOfResult1< M1 >
Definition at line 305 of file gmock-generated-matchers.h.
Class Members
typedef M1 type
struct testing::internal::AllOfResult10
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7, typename M8, typename M9, typename M10>
struct testing::internal::AllOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >
Definition at line 379 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult5< M1,
M2, M3, M4, M5 >::type,
typename AllOfResult5< M6, M7,
M8, M9, M10 >::type > type
struct testing::internal::AllOfResult2
template<typename M1, typename M2>
struct testing::internal::AllOfResult2< M1, M2 >
Definition at line 310 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult1< M1 >
::type, typename AllOfResult1
< M2 >::type > type
struct testing::internal::AllOfResult3
template<typename M1, typename M2, typename M3>
struct testing::internal::AllOfResult3< M1, M2, M3 >
Definition at line 318 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult1< M1 >
::type, typename AllOfResult2
< M2, M3 >::type > type
struct testing::internal::AllOfResult4
template<typename M1, typename M2, typename M3, typename M4>
struct testing::internal::AllOfResult4< M1, M2, M3, M4 >
Definition at line 326 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult2< M1,
M2 >::type, typename
AllOfResult2< M3, M4 >::type > type
struct testing::internal::AllOfResult5
template<typename M1, typename M2, typename M3, typename M4, typename M5>
struct testing::internal::AllOfResult5< M1, M2, M3, M4, M5 >
Definition at line 334 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult2< M1,
M2 >::type, typename
AllOfResult3< M3, M4, M5 >
::type > type
struct testing::internal::AllOfResult6
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6>
struct testing::internal::AllOfResult6< M1, M2, M3, M4, M5, M6 >
Definition at line 343 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult3< M1,
M2, M3 >::type, typename
AllOfResult3< M4, M5, M6 >
::type > type
struct testing::internal::AllOfResult7
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7>
struct testing::internal::AllOfResult7< M1, M2, M3, M4, M5, M6, M7 >
Definition at line 352 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult3< M1,
M2, M3 >::type, typename
AllOfResult4< M4, M5, M6, M7 >
::type > type
struct testing::internal::AllOfResult8
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7, typename M8>
struct testing::internal::AllOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >
Definition at line 361 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult4< M1,
M2, M3, M4 >::type, typename
AllOfResult4< M5, M6, M7, M8 >
::type > type
struct testing::internal::AllOfResult9
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7, typename M8, typename M9>
struct testing::internal::AllOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >
Definition at line 370 of file gmock-generated-matchers.h.
Class Members
typedef BothOfMatcher
< typename AllOfResult4< M1,
M2, M3, M4 >::type, typename
AllOfResult5< M5, M6, M7, M8,
M9 >::type > type
struct testing::internal::AnyOfResult1
template<typename M1>
struct testing::internal::AnyOfResult1< M1 >
Definition at line 393 of file gmock-generated-matchers.h.
Class Members
typedef M1 type
struct testing::internal::AnyOfResult10
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7, typename M8, typename M9, typename M10>
struct testing::internal::AnyOfResult10< M1, M2, M3, M4, M5, M6, M7, M8, M9, M10 >
Definition at line 467 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult5< M1,
M2, M3, M4, M5 >::type,
typename AnyOfResult5< M6, M7,
M8, M9, M10 >::type > type
struct testing::internal::AnyOfResult2
template<typename M1, typename M2>
struct testing::internal::AnyOfResult2< M1, M2 >
Definition at line 398 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult1< M1 >
::type, typename AnyOfResult1
< M2 >::type > type
struct testing::internal::AnyOfResult3
template<typename M1, typename M2, typename M3>
struct testing::internal::AnyOfResult3< M1, M2, M3 >
Definition at line 406 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult1< M1 >
::type, typename AnyOfResult2
< M2, M3 >::type > type
struct testing::internal::AnyOfResult4
template<typename M1, typename M2, typename M3, typename M4>
struct testing::internal::AnyOfResult4< M1, M2, M3, M4 >
Definition at line 414 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult2< M1,
M2 >::type, typename
AnyOfResult2< M3, M4 >::type > type
struct testing::internal::AnyOfResult5
template<typename M1, typename M2, typename M3, typename M4, typename M5>
struct testing::internal::AnyOfResult5< M1, M2, M3, M4, M5 >
Definition at line 422 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult2< M1,
M2 >::type, typename
AnyOfResult3< M3, M4, M5 >
::type > type
struct testing::internal::AnyOfResult6
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6>
struct testing::internal::AnyOfResult6< M1, M2, M3, M4, M5, M6 >
Definition at line 431 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult3< M1,
M2, M3 >::type, typename
AnyOfResult3< M4, M5, M6 >
::type > type
struct testing::internal::AnyOfResult7
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7>
struct testing::internal::AnyOfResult7< M1, M2, M3, M4, M5, M6, M7 >
Definition at line 440 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult3< M1,
M2, M3 >::type, typename
AnyOfResult4< M4, M5, M6, M7 >
::type > type
struct testing::internal::AnyOfResult8
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7, typename M8>
struct testing::internal::AnyOfResult8< M1, M2, M3, M4, M5, M6, M7, M8 >
Definition at line 449 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult4< M1,
M2, M3, M4 >::type, typename
AnyOfResult4< M5, M6, M7, M8 >
::type > type
struct testing::internal::AnyOfResult9
template<typename M1, typename M2, typename M3, typename M4, typename M5, typename M6, typename M7, typename M8, typename M9>
struct testing::internal::AnyOfResult9< M1, M2, M3, M4, M5, M6, M7, M8, M9 >
Definition at line 458 of file gmock-generated-matchers.h.
Class Members
typedef EitherOfMatcher
< typename AnyOfResult4< M1,
M2, M3, M4 >::type, typename
AnyOfResult5< M5, M6, M7, M8,
M9 >::type > type
struct testing::internal::BooleanConstant
template<bool kValue>
struct testing::internal::BooleanConstant< kValue >
Definition at line 505 of file gmock-internal-utils.h.
struct testing::internal::CompileAssert
template<bool>
struct testing::internal::CompileAssert< bool >
Definition at line 1029 of file gtest-port.h.
struct testing::internal::CompileAssertTypesEqual
template<typename T1, typename T2>
struct testing::internal::CompileAssertTypesEqual< T1, T2 >
Definition at line 772 of file gtest-internal.h.
struct testing::internal::CompileAssertTypesEqual< T, T >
template<typename T>
struct testing::internal::CompileAssertTypesEqual< T, T >
Definition at line 775 of file gtest-internal.h.
struct testing::internal::DecayArray
template<typename T>
struct testing::internal::DecayArray< T >
Definition at line 353 of file gmock-internal-utils.h.
Class Members
typedef T type
struct testing::internal::DecayArray< T[]>
template<typename T>
struct testing::internal::DecayArray< T[]>
Definition at line 360 of file gmock-internal-utils.h.
Class Members
typedef const T * type
struct testing::internal::DecayArray< T[N]>
template<typename T, size_t N>
struct testing::internal::DecayArray< T[N]>
Definition at line 354 of file gmock-internal-utils.h.
Class Members
typedef const T * type
struct testing::internal::EnableIf
template<bool>
struct testing::internal::EnableIf< bool >
Definition at line 946 of file gtest-internal.h.
struct testing::internal::EnableIf< true >
template<>
struct testing::internal::EnableIf< true >
Definition at line 947 of file gtest-internal.h.
Class Members
typedef void type
struct testing::internal::ExcessiveArg
Definition at line 508 of file gmock-generated-actions.h.
struct testing::internal::Function
template<typename F>
struct testing::internal::Function< F >
Definition at line 154 of file gmock-generated-internal-utils.h.
class testing::internal::FunctionMocker
template<typename F>
class testing::internal::FunctionMocker< F >
Definition at line 62 of file gmock-generated-function-mockers.h.
class testing::internal::InvokeHelper
template<typename Result, typename ArgumentTuple>
class testing::internal::InvokeHelper< Result, ArgumentTuple >
Definition at line 51 of file gmock-generated-actions.h.
struct testing::internal::IteratorTraits
template<typename Iterator>
struct testing::internal::IteratorTraits< Iterator >
Definition at line 2219 of file gtest-port.h.
Class Members
typedef value_type value_type
struct testing::internal::IteratorTraits< const T * >
template<typename T>
struct testing::internal::IteratorTraits< const T * >
Definition at line 2229 of file gtest-port.h.
Class Members
typedef T value_type
struct testing::internal::IteratorTraits< T * >
template<typename T>
struct testing::internal::IteratorTraits< T * >
Definition at line 2224 of file gtest-port.h.
Class Members
typedef T value_type
struct testing::internal::KindOf
template<typename T>
struct testing::internal::KindOf< T >
Definition at line 131 of file gmock-internal-utils.h.
Class Members
__unnamed__
struct testing::internal::MatcherTuple
template<typename Tuple>
struct testing::internal::MatcherTuple< Tuple >
Definition at line 69 of file gmock-generated-internal-utils.h.
struct testing::internal::MatcherTuple< ::testing::tuple< A1 > >
template<typename A1>
struct testing::internal::MatcherTuple< ::testing::tuple< A1 > >
Definition at line 77 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2 > >
template<typename A1, typename A2>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2 > >
Definition at line 82 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3 > >
template<typename A1, typename A2, typename A3>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3 > >
Definition at line 87 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4 > >
template<typename A1, typename A2, typename A3, typename A4>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4 > >
Definition at line 92 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5 > >
template<typename A1, typename A2, typename A3, typename A4, typename A5>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5 > >
Definition at line 98 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 >, Matcher< A5 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6 > >
template<typename A1, typename A2, typename A3, typename A4, typename A5, typename A6>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6 > >
Definition at line 105 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 >, Matcher< A5 >
, Matcher< A6 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7 > >
template<typename A1, typename A2, typename A3, typename A4, typename A5, typename A6, typename A7>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7 > >
Definition at line 112 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 >, Matcher< A5 >
, Matcher< A6 >, Matcher< A7 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8 > >
template<typename A1, typename A2, typename A3, typename A4, typename A5, typename A6, typename A7, typename A8>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8 > >
Definition at line 119 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 >, Matcher< A5 >
, Matcher< A6 >, Matcher< A7 >
, Matcher< A8 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9 > >
template<typename A1, typename A2, typename A3, typename A4, typename A5, typename A6, typename A7, typename A8, typename A9>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9 > >
Definition at line 126 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 >, Matcher< A5 >
, Matcher< A6 >, Matcher< A7 >
, Matcher< A8 >, Matcher< A9 > > type
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 > >
template<typename A1, typename A2, typename A3, typename A4, typename A5, typename A6, typename A7, typename A8, typename A9, typename A10>
struct testing::internal::MatcherTuple< ::testing::tuple< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 > >
Definition at line 133 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< Matcher< A1 >
, Matcher< A2 >, Matcher< A3 >
, Matcher< A4 >, Matcher< A5 >
, Matcher< A6 >, Matcher< A7 >
, Matcher< A8 >, Matcher< A9 >
, Matcher< A10 > > type
struct testing::internal::MatcherTuple< ::testing::tuple<> >
template<>
struct testing::internal::MatcherTuple< ::testing::tuple<> >
Definition at line 72 of file gmock-generated-internal-utils.h.
Class Members
typedef ::tuple< > type
struct testing::internal::PointeeOf
template<typename Pointer>
struct testing::internal::PointeeOf< Pointer >
Definition at line 63 of file gmock-internal-utils.h.
Class Members
typedef element_type type
struct testing::internal::PointeeOf< T * >
template<typename T>
struct testing::internal::PointeeOf< T * >
Definition at line 70 of file gmock-internal-utils.h.
Class Members
typedef T type
class testing::internal::RefMatcher
template<typename T>
class testing::internal::RefMatcher< T >
Definition at line 1029 of file gmock-matchers.h.
struct testing::internal::RelationToSourceCopy
Definition at line 1023 of file gtest-internal.h.
struct testing::internal::RelationToSourceReference
Definition at line 1022 of file gtest-internal.h.
struct testing::internal::remove_reference
template<typename T>
struct testing::internal::remove_reference< T >
Definition at line 348 of file gmock-internal-utils.h.
Class Members
typedef T type
struct testing::internal::remove_reference< T & >
template<typename T>
struct testing::internal::remove_reference< T & >
Definition at line 349 of file gmock-internal-utils.h.
Class Members
typedef T type
struct testing::internal::RemoveConst
template<typename T>
struct testing::internal::RemoveConst< T >
Definition at line 795 of file gtest-internal.h.
Class Members
typedef T type
struct testing::internal::RemoveConst< const T >
template<typename T>
struct testing::internal::RemoveConst< const T >
Definition at line 797 of file gtest-internal.h.
Class Members
typedef T type
struct testing::internal::RemoveConst< const T[N]>
template<typename T, size_t N>
struct testing::internal::RemoveConst< const T[N]>
Definition at line 803 of file gtest-internal.h.
Class Members
typedef RemoveConst< T >::type type
struct testing::internal::RemoveConstFromKey
template<typename T>
struct testing::internal::RemoveConstFromKey< T >
Definition at line 492 of file gmock-internal-utils.h.
Class Members
typedef T type
struct testing::internal::RemoveConstFromKey< std::pair< const K, V > >
template<typename K, typename V>
struct testing::internal::RemoveConstFromKey< std::pair< const K, V > >
Definition at line 498 of file gmock-internal-utils.h.
Class Members
typedef pair< K, V > type
struct testing::internal::RemoveReference
template<typename T>
struct testing::internal::RemoveReference< T >
Definition at line 782 of file gtest-internal.h.
Class Members
typedef T type
struct testing::internal::RemoveReference< T & >
template<typename T>
struct testing::internal::RemoveReference< T & >
Definition at line 784 of file gtest-internal.h.
Class Members
typedef T type
struct testing::internal::StaticAssertTypeEqHelper
template<typename T1, typename T2>
struct testing::internal::StaticAssertTypeEqHelper< T1, T2 >
Definition at line 1084 of file gtest-port.h.
struct testing::internal::StaticAssertTypeEqHelper< T, T >
template<typename T>
struct testing::internal::StaticAssertTypeEqHelper< T, T >
Definition at line 1087 of file gtest-port.h.
Class Members
__unnamed__
struct testing::internal::TraceInfo
Definition at line 457 of file gtest-internal-inl.h.
Class Members
const char * file
int line
string message
struct testing::internal::TuplePolicy
template<typename TupleT>
struct testing::internal::TuplePolicy< TupleT >
Definition at line 869 of file gtest-printers.h.
class testing::internal::TypeWithSize
template<size_t size>
class testing::internal::TypeWithSize< size >
Definition at line 2461 of file gtest-port.h.
Class Members
typedef void UInt
class testing::internal::TypeWithSize< 4 >
template<>
class testing::internal::TypeWithSize< 4 >
Definition at line 2470 of file gtest-port.h.
Class Members
typedef int Int
typedef unsigned int UInt
class testing::internal::TypeWithSize< 8 >
template<>
class testing::internal::TypeWithSize< 8 >
Definition at line 2482 of file gtest-port.h.
Class Members
typedef long long Int
typedef unsigned long long UInt
Typedef Documentation
typedef ::std::pair<size_t, size_t> testing::internal::ElementMatcherPair
Definition at line 3297 of file gmock-matchers.h.
typedef ::std::vector<ElementMatcherPair> testing::internal::ElementMatcherPairs
Definition at line 3298 of file gmock-matchers.h.
typedef ::std::vector<string> testing::internal::Strings
Definition at line 859 of file gtest-printers.h.
typedef FloatingPoint<float> testing::internal::Float
Definition at line 420 of file gtest-internal.h.
typedef FloatingPoint<double> testing::internal::Double
Definition at line 421 of file gtest-internal.h.
typedef const void* testing::internal::TypeId
Definition at line 429 of file gtest-internal.h.
typedef void(* testing::internal::SetUpTestCaseFunc) ()
Definition at line 501 of file gtest-internal.h.
typedef void(* testing::internal::TearDownTestCaseFunc) ()
Definition at line 502 of file gtest-internal.h.
typedef int testing::internal::IsContainer
Definition at line 930 of file gtest-internal.h.
typedef char testing::internal::IsNotContainer
Definition at line 938 of file gtest-internal.h.
typedef ::std::string testing::internal::string
Definition at line 1097 of file gtest-port.h.
typedef ::std::wstring testing::internal::wstring
Definition at line 1103 of file gtest-port.h.
typedef GTestMutexLock testing::internal::MutexLock
Definition at line 2159 of file gtest-port.h.
typedef bool_constant<false> testing::internal::false_type
Definition at line 2209 of file gtest-port.h.
typedef bool_constant<true> testing::internal::true_type
Definition at line 2210 of file gtest-port.h.
typedef long long testing::internal::BiggestInt
Definition at line 2241 of file gtest-port.h.
typedef TypeWithSize<4>::Int testing::internal::Int32
Definition at line 2494 of file gtest-port.h.
typedef TypeWithSize<4>::UInt testing::internal::UInt32
Definition at line 2495 of file gtest-port.h.
typedef TypeWithSize<8>::Int testing::internal::Int64
Definition at line 2496 of file gtest-port.h.
typedef TypeWithSize<8>::UInt testing::internal::UInt64
Definition at line 2497 of file gtest-port.h.
typedef TypeWithSize<8>::Int testing::internal::TimeInMillis
Definition at line 2498 of file gtest-port.h.
Enumeration Type Documentation
enum testing::internal::CallReaction
Enumerator
kAllow
kWarn
kFail
kDefault
Definition at line 361 of file gmock-spec-builders.h.
enum testing::internal::TypeKind
Enumerator
kBool
kInteger
kFloatingPoint
kOther
Definition at line 126 of file gmock-internal-utils.h.
enum testing::internal::LogSeverity
Enumerator
kInfo
kWarning
Definition at line 306 of file gmock-internal-utils.h.
enum testing::internal::GTestLogSeverity
Enumerator
GTEST_INFO
GTEST_WARNING
GTEST_ERROR
GTEST_FATAL
Definition at line 1244 of file gtest-port.h.
Function Documentation
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (void)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (::std::string , "")
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (bool , false)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (unsigned char, '\0')
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (signed char, '\0')
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (char , '\0')
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (unsigned short, 0U)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (signed short, 0)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (unsigned long, 0UL)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (signed long, 0L)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (UInt64 , 0)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (Int64 , 0)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (float , 0)
testing::internal::GMOCK_DEFINE_DEFAULT_ACTION_FOR_RETURN_TYPE_ (double , 0)
template<typename T > void testing::internal::PrintTo (const ReferenceWrapper< T > & ref, ::std::ostream * os)
Definition at line 964 of file gmock-actions.h.
References testing::internal::UniversalPrinter< T >::Print().
void testing::internal::PrintIfNotEmpty (const internal::string & explanation, ::std::ostream * os) inline
Definition at line 678 of file gmock-matchers.h.
Referenced by testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl(), and MatchPrintAndExplain().
bool testing::internal::IsReadableTypeName (const string & type_name) inline
Definition at line 688 of file gmock-matchers.h.
Referenced by MatchPrintAndExplain().
template<typename Value , typename T > bool testing::internal::MatchPrintAndExplain (Value & value, const Matcher< T > & matcher, MatchResultListener * listener)
Definition at line 701 of file gmock-matchers.h.
References testing::MatchResultListener::IsInterested(), IsReadableTypeName(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), PrintIfNotEmpty(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and UniversalPrint().
Referenced by testing::internal::WhenDynamicCastToMatcher< To >::MatchAndExplain(), testing::internal::WhenDynamicCastToMatcher< To & >::MatchAndExplain(), testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplain(), testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplain(), testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer >(), testing::internal::ResultOfMatcher< Callable >::operator Matcher< T >(), and testing::internal::PredicateFormatterFromMatcher< M >::operator()().
template<typename MatcherTuple , typename ValueTuple > bool testing::internal::TupleMatches (const MatcherTuple & matcher_tuple, const ValueTuple & value_tuple)
Definition at line 796 of file gmock-matchers.h.
References GTEST_COMPILE_ASSERT_.
Referenced by testing::internal::OnCallSpec< F >::Matches().
template<typename MatcherTuple , typename ValueTuple > void testing::internal::ExplainMatchFailureTupleTo (const MatcherTuple & matchers, const ValueTuple & values, ::std::ostream * os)
Definition at line 810 of file gmock-matchers.h.
template<typename Tuple , typename Func , typename OutIter > OutIter testing::internal::TransformTupleValues (Func f, const Tuple & t, OutIter out)
Definition at line 853 of file gmock-matchers.h.
Referenced by testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::operator Matcher< Container >(), and testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container >().
bool testing::internal::CaseInsensitiveCStringEquals (const char * lhs, const char * rhs) inline
Definition at line 1090 of file gmock-matchers.h.
References CaseInsensitiveCStringEquals().
bool testing::internal::CaseInsensitiveCStringEquals (const wchar_t * lhs, const wchar_t * rhs) inline
Definition at line 1094 of file gmock-matchers.h.
Referenced by CaseInsensitiveCStringEquals(), and CaseInsensitiveStringEquals().
template<typename StringType > bool testing::internal::CaseInsensitiveStringEquals (const StringType & s1, const StringType & s2)
Definition at line 1102 of file gmock-matchers.h.
References CaseInsensitiveCStringEquals().
Referenced by testing::internal::StrEqualityMatcher< StringType >::MatchAndExplain().
template<typename M > PredicateFormatterFromMatcher<M> testing::internal::MakePredicateFormatterFromMatcher (M matcher) inline
Definition at line 1879 of file gmock-matchers.h.
References move().
GTEST_API_ ElementMatcherPairs testing::internal::FindMaxBipartiteMatching (const MatchMatrix & g)
GTEST_API_ bool testing::internal::FindPairing (const MatchMatrix & matrix, MatchResultListener * listener)
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain().
template<typename Tuple2Matcher , typename Second > BoundSecondMatcher<Tuple2Matcher, Second> testing::internal::MatcherBindSecond (const Tuple2Matcher & tm, const Second & second)
Definition at line 3612 of file gmock-matchers.h.
References FormatMatcherDescription(), and GTEST_API_.
Referenced by testing::UnorderedPointwise().
GTEST_API_ string testing::internal::FormatMatcherDescription (bool negation, const char * matcher_name, const Strings & param_values)
Referenced by MatcherBindSecond().
template<typename InputIterator , typename OutputIterator > OutputIterator testing::internal::CopyElements (InputIterator first, InputIterator last, OutputIterator output) inline
Definition at line 98 of file gmock-more-actions.h.
Referenced by testing::ACTION_TEMPLATE().
GTEST_API_ testing::internal::GTEST_DECLARE_STATIC_MUTEX_ (g_gmock_mutex)
GTEST_API_ void testing::internal::LogWithLocation (testing::internal::LogSeverity severity, const char * file, int line, const string & message)
Referenced by testing::internal::MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::InternalDefaultActionSetAt(), and testing::internal::MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::InternalExpectedAt().
void testing::internal::ReportUninterestingCall (CallReaction reaction, const string & msg)
GTEST_API_ string testing::internal::ConvertIdentifierNameToWords (const char * id_name)
template<typename Pointer > const Pointer::element_type* testing::internal::GetRawPointer (const Pointer & p) inline
Definition at line 76 of file gmock-internal-utils.h.
Referenced by testing::internal::IsNullMatcher::MatchAndExplain(), testing::internal::NotNullMatcher::MatchAndExplain(), and testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer >().
template<typename Element > Element* testing::internal::GetRawPointer (Element * p) inline
Definition at line 81 of file gmock-internal-utils.h.
testing::internal::GMOCK_DECLARE_KIND_ (bool , kBool)
testing::internal::GMOCK_DECLARE_KIND_ (char , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (signed char, kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (unsigned char, kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (short , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (int , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (long , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (wchar_t , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (Int64 , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (UInt64 , kInteger)
testing::internal::GMOCK_DECLARE_KIND_ (float , kFloatingPoint)
testing::internal::GMOCK_DECLARE_KIND_ (double , kFloatingPoint)
testing::internal::GMOCK_DECLARE_KIND_ (long double, kFloatingPoint)
template<typename From , typename To > void testing::internal::Assert (bool condition, const char * file, int line) inline
Definition at line 288 of file gmock-internal-utils.h.
Referenced by testing::internal::UntypedOnCallSpecBase::AssertSpecProperty(), testing::internal::ExpectationBase::AssertSpecProperty(), testing::internal::BuiltInDefaultValueGetter< T, false >::Get(), Invalid(), testing::Action< InnerFunctionType >::Perform(), and testing::internal::FunctionMockerBase< R(A1, A2)>::PerformDefaultAction().
void testing::internal::Expect (bool condition, const char * file, int line, const string & msg) inline
Definition at line 294 of file gmock-internal-utils.h.
Referenced by Expect(), testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty(), and testing::internal::ExpectationBase::ExpectSpecProperty().
void testing::internal::Expect (bool condition, const char * file, int line) inline
Definition at line 301 of file gmock-internal-utils.h.
References Expect().
GTEST_API_ bool testing::internal::LogIsVisible (LogSeverity severity)
GTEST_API_ void testing::internal::Log (LogSeverity severity, const string & message, int stack_frames_to_skip)
template<typename T > T testing::internal::Invalid () inline
Definition at line 377 of file gmock-internal-utils.h.
References Assert().
template<typename T > std::string testing::internal::StreamableToString (const T & streamable)
Definition at line 243 of file gtest-message.h.
Referenced by testing::internal::TestResultAccessor::test_part_results().
testing::internal::GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (char)
testing::internal::GTEST_IMPL_FORMAT_C_STRING_AS_POINTER_ (wchar_t)
testing::internal::GTEST_IMPL_FORMAT_C_STRING_AS_STRING_ (char , ::std::string)
template<typename T1 , typename T2 > std::string testing::internal::FormatForComparisonFailureMessage (const T1 & value, const T2 &)
Definition at line 349 of file gtest-printers.h.
Referenced by CmpHelperEQFailure(), and CmpHelperOpFailure().
template<typename T > void testing::internal::UniversalPrint (const T & value, ::std::ostream * os)
Definition at line 852 of file gtest-printers.h.
Referenced by DefaultPrintTo(), testing::internal::StrEqualityMatcher< StringType >::DescribeNegationTo(), testing::internal::HasSubstrMatcher< StringType >::DescribeNegationTo(), testing::internal::StartsWithMatcher< StringType >::DescribeNegationTo(), testing::internal::EndsWithMatcher< StringType >::DescribeNegationTo(), testing::internal::ContainerEqMatcher< Container >::DescribeNegationTo(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeNegationTo(), testing::internal::HasSubstrMatcher< StringType >::DescribeTo(), testing::internal::StartsWithMatcher< StringType >::DescribeTo(), testing::internal::EndsWithMatcher< StringType >::DescribeTo(), testing::internal::ContainerEqMatcher< Container >::DescribeTo(), testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo(), testing::internal::ContainerEqMatcher< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), MatchPrintAndExplain(), testing::internal::ComparisonBase< LtMatcher< Rhs >, Rhs, AnyLt >::operator Matcher< Lhs >(), testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator=(), testing::internal::UniversalPrinter< T & >::Print(), testing::internal::UniversalTersePrinter< T >::Print(), testing::internal::UniversalTersePrinter< T & >::Print(), testing::internal::UniversalTersePrinter< const char * >::Print(), testing::internal::UniversalTersePrinter< char * >::Print(), and PrintRawArrayTo().
template<typename C > void testing::internal::DefaultPrintTo (IsContainer , false_type , const C & container, ::std::ostream * os)
Definition at line 370 of file gtest-printers.h.
References UniversalPrint().
template<typename T > void testing::internal::DefaultPrintTo (IsNotContainer , true_type , T * p, ::std::ostream * os)
Definition at line 404 of file gtest-printers.h.
References IsTrue().
template<typename T > void testing::internal::DefaultPrintTo (IsNotContainer , false_type , const T & value, ::std::ostream * os)
Definition at line 436 of file gtest-printers.h.
References testing_internal::DefaultPrintNonContainerTo().
Referenced by PrintTo().
template<typename T > void testing::internal::PrintTo (const T & value, ::std::ostream * os)
Definition at line 454 of file gtest-printers.h.
References DefaultPrintTo(), GTEST_API_, and PrintTo().
GTEST_API_ void testing::internal::PrintTo (unsigned char c, ::std::ostream * os)
GTEST_API_ void testing::internal::PrintTo (signed char c, ::std::ostream * os)
void testing::internal::PrintTo (char c, ::std::ostream * os) inline
Definition at line 487 of file gtest-printers.h.
References PrintTo().
void testing::internal::PrintTo (bool x, ::std::ostream * os) inline
Definition at line 495 of file gtest-printers.h.
References GTEST_API_, and PrintTo().
GTEST_API_ void testing::internal::PrintTo (wchar_t wc, ::std::ostream * os)
GTEST_API_ void testing::internal::PrintTo (const char * s, ::std::ostream * os)
void testing::internal::PrintTo (char * s, ::std::ostream * os) inline
Definition at line 510 of file gtest-printers.h.
References PrintTo().
void testing::internal::PrintTo (const signed char * s, ::std::ostream * os) inline
Definition at line 516 of file gtest-printers.h.
References PrintTo().
void testing::internal::PrintTo (signed char * s, ::std::ostream * os) inline
Definition at line 519 of file gtest-printers.h.
References PrintTo().
void testing::internal::PrintTo (const unsigned char * s, ::std::ostream * os) inline
Definition at line 522 of file gtest-printers.h.
References PrintTo().
void testing::internal::PrintTo (unsigned char * s, ::std::ostream * os) inline
Definition at line 525 of file gtest-printers.h.
References GTEST_API_, and PrintTo().
GTEST_API_ void testing::internal::PrintTo (const wchar_t * s, ::std::ostream * os)
void testing::internal::PrintTo (wchar_t * s, ::std::ostream * os) inline
Definition at line 537 of file gtest-printers.h.
References PrintTo().
template<typename T > void testing::internal::PrintRawArrayTo (const T a[], size_t count, ::std::ostream * os)
Definition at line 548 of file gtest-printers.h.
References GTEST_API_, PrintStringTo(), PrintTo(), and UniversalPrint().
Referenced by UniversalPrintArray().
GTEST_API_ void testing::internal::PrintStringTo (const ::std::string & s, ::std::ostream * os)
Referenced by PrintRawArrayTo(), and PrintTo().
void testing::internal::PrintTo (const ::std::string & s, ::std::ostream * os) inline
Definition at line 565 of file gtest-printers.h.
References GTEST_API_, PrintStringTo(), and PrintTo().
template<typename T1 , typename T2 > void testing::internal::PrintTo (const ::std::pair< T1, T2 > & value, ::std::ostream * os)
Definition at line 676 of file gtest-printers.h.
References GTEST_DISABLE_MSC_WARNINGS_PUSH_.
Referenced by testing::internal::UniversalPrinter< T >::Print(), PrintRawArrayTo(), and PrintTo().
template<typename T > void testing::internal::UniversalPrintArray (const T * begin, size_t len, ::std::ostream * os)
Definition at line 716 of file gtest-printers.h.
References GTEST_API_, PrintRawArrayTo(), and UniversalPrintArray().
GTEST_API_ void testing::internal::UniversalPrintArray (const char * begin, size_t len, ::std::ostream * os)
GTEST_API_ void testing::internal::UniversalPrintArray (const wchar_t * begin, size_t len, ::std::ostream * os)
Referenced by testing::internal::UniversalPrinter< T[N]>::Print(), and UniversalPrintArray().
template<typename T > void testing::internal::UniversalTersePrint (const T & value, ::std::ostream * os)
Definition at line 843 of file gtest-printers.h.
UnitTestImpl * testing::internal::GetUnitTestImpl () inline
Definition at line 927 of file gtest-internal-inl.h.
References testing::UnitTest::GetInstance(), GTEST_API_, GTEST_CHECK_, IsDigit(), and ParseGoogleTestFlagsOnly().
void testing::internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message)
template<typename T1 , typename T2 > AssertionResult testing::internal::CmpHelperEQFailure (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)
Definition at line 1375 of file gtest.h.
References EqFailure(), and FormatForComparisonFailureMessage().
Referenced by CmpHelperEQ().
template<typename T1 , typename T2 > AssertionResult testing::internal::CmpHelperEQ (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)
Definition at line 1387 of file gtest.h.
References testing::AssertionSuccess(), CmpHelperEQFailure(), GTEST_API_, GTEST_DISABLE_MSC_WARNINGS_POP_, and GTEST_DISABLE_MSC_WARNINGS_PUSH_.
Referenced by testing::internal::EqHelper< lhs_is_null_literal >::Compare(), and testing::internal::EqHelper< true >::Compare().
GTEST_API_ AssertionResult testing::internal::CmpHelperEQ (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs)
template<typename T1 , typename T2 > AssertionResult testing::internal::CmpHelperOpFailure (const char * expr1, const char * expr2, const T1 & val1, const T2 & val2, const char * op)
Definition at line 1486 of file gtest.h.
References testing::AssertionFailure(), and FormatForComparisonFailureMessage().
testing::internal::GTEST_IMPL_CMP_HELPER_ (NE , !)
testing::internal::GTEST_IMPL_CMP_HELPER_ (LE , <=)
testing::internal::GTEST_IMPL_CMP_HELPER_ (LT)
testing::internal::GTEST_IMPL_CMP_HELPER_ (GE , >=)
testing::internal::GTEST_IMPL_CMP_HELPER_ (GT)
GTEST_API_ AssertionResult testing::internal::CmpHelperSTREQ (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRCASEEQ (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRNE (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRCASENE (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
GTEST_API_ AssertionResult testing::internal::CmpHelperSTREQ (const char * s1_expression, const char * s2_expression, const wchar_t * s1, const wchar_t * s2)
GTEST_API_ AssertionResult testing::internal::CmpHelperSTRNE (const char * s1_expression, const char * s2_expression, const wchar_t * s1, const wchar_t * s2)
template<typename RawType > AssertionResult testing::internal::CmpHelperFloatingPointEQ (const char * lhs_expression, const char * rhs_expression, RawType lhs_value, RawType rhs_value)
Definition at line 1631 of file gtest.h.
References testing::AssertionSuccess(), DoubleNearPredFormat(), EqFailure(), GTEST_API_, and StringStreamToString().
GTEST_API_ AssertionResult testing::internal::DoubleNearPredFormat (const char * expr1, const char * expr2, const char * abs_error_expr, double val1, double val2, double abs_error)
Referenced by CmpHelperFloatingPointEQ().
testing::internal::GTEST_DECLARE_string_ (internal_run_death_test)
char testing::internal::IsNullLiteralHelper (Secret * p)
char(& testing::internal::IsNullLiteralHelper (...))[2]
GTEST_API_ std::string testing::internal::AppendUserMessage (const std::string & gtest_msg, const Message & user_msg)
GTEST_API_ std::string testing::internal::DiffStrings (const std::string & left, const std::string & right, size_t * total_line_count)
GTEST_API_ AssertionResult testing::internal::EqFailure (const char * expected_expression, const char * actual_expression, const std::string & expected_value, const std::string & actual_value, bool ignoring_case)
Referenced by CmpHelperEQFailure(), and CmpHelperFloatingPointEQ().
GTEST_API_ std::string testing::internal::GetBoolAssertionFailureMessage (const AssertionResult & assertion_result, const char * expression_text, const char * actual_predicate_value, const char * expected_predicate_value)
template<typename T > TypeId testing::internal::GetTypeId ()
Definition at line 447 of file gtest-internal.h.
References GetTestTypeId(), and GTEST_API_.
GTEST_API_ TypeId testing::internal::GetTestTypeId ()
Referenced by GetTypeId().
GTEST_API_ TestInfo* testing::internal::MakeAndRegisterTestInfo (const char * test_case_name, const char * name, const char * type_param, const char * value_param, CodeLocation code_location, TypeId fixture_class_id, SetUpTestCaseFunc set_up_tc, TearDownTestCaseFunc tear_down_tc, TestFactoryBase * factory)
GTEST_API_ bool testing::internal::SkipPrefix (const char * prefix, const char ** pstr)
GTEST_API_ std::string testing::internal::GetCurrentOsStackTraceExceptTop (UnitTest * unit_test, int skip_count)
GTEST_API_ bool testing::internal::AlwaysTrue ()
Referenced by AlwaysFalse().
bool testing::internal::AlwaysFalse () inline
Definition at line 736 of file gtest-internal.h.
References AlwaysTrue().
template<class C > IsContainer testing::internal::IsContainerTest (int , typename C::iterator * = NULL, typename C::const_iterator * = NULL)
Definition at line 932 of file gtest-internal.h.
template<class C > IsNotContainer testing::internal::IsContainerTest (long)
Definition at line 940 of file gtest-internal.h.
template<typename T , typename U > bool testing::internal::ArrayEq (const T * lhs, size_t size, const U * rhs)
Definition at line 972 of file gtest-internal.h.
References ArrayEq().
template<typename T , typename U > bool testing::internal::ArrayEq (const T & lhs, const U & rhs) inline
Definition at line 960 of file gtest-internal.h.
template<typename T , typename U , size_t N> bool testing::internal::ArrayEq (const T(&) lhs[N], const U(&) rhs[N]) inline
Definition at line 964 of file gtest-internal.h.
Referenced by ArrayAwareFind(), ArrayEq(), and testing::internal::NativeArray< Element >::operator==().
template<typename Iter , typename Element > Iter testing::internal::ArrayAwareFind (Iter begin, Iter end, const Element & elem)
Definition at line 983 of file gtest-internal.h.
References ArrayEq(), and CopyArray().
Referenced by testing::internal::ContainerEqMatcher< Container >::MatchAndExplain().
template<typename T , typename U > void testing::internal::CopyArray (const T * from, size_t size, U * to)
Definition at line 1012 of file gtest-internal.h.
References CopyArray().
template<typename T , typename U > void testing::internal::CopyArray (const T & from, U * to) inline
Definition at line 1000 of file gtest-internal.h.
template<typename T , typename U , size_t N> void testing::internal::CopyArray (const T(&) from[N], U(*) to[N]) inline
Definition at line 1004 of file gtest-internal.h.
Referenced by ArrayAwareFind(), CopyArray(), and testing::internal::NativeArray< Element >::operator==().
GTEST_API_ testing::internal::GTEST_DECLARE_STATIC_MUTEX_ (g_linked_ptr_mutex)
template<typename T > bool testing::internal::operator== (T * ptr, const linked_ptr< T > & x) inline
Definition at line 223 of file gtest-linked_ptr.h.
References testing::internal::linked_ptr< T >::get().
template<typename T > bool testing::internal::operator!= (T * ptr, const linked_ptr< T > & x) inline
Definition at line 228 of file gtest-linked_ptr.h.
References testing::internal::linked_ptr< T >::get().
template<typename T > linked_ptr<T> testing::internal::make_linked_ptr (T * ptr)
Definition at line 236 of file gtest-linked_ptr.h.
GTEST_API_ bool testing::internal::IsTrue (bool condition)
Referenced by DefaultPrintTo(), and testing::internal::scoped_ptr< const ::std::string >::reset().
GTEST_API_ ::std::string testing::internal::FormatFileLocation (const char * file, int line)
Referenced by testing::internal::ExpectationBase::DescribeLocationTo(), and testing::internal::RE::PartialMatch().
GTEST_API_ ::std::string testing::internal::FormatCompilerIndependentFileLocation (const char * file, int line)
Referenced by testing::internal::RE::PartialMatch().
void testing::internal::LogToStderr () inline
Definition at line 1275 of file gtest-port.h.
void testing::internal::FlushInfoLog () inline
Definition at line 1276 of file gtest-port.h.
template<typename T > const T& testing::internal::move (const T & t)
Definition at line 1317 of file gtest-port.h.
Referenced by v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::add_constructor(), testing::ByMove(), v8toolkit::V8ClassWrapper< T, V8TOOLKIT_V8CLASSWRAPPER_USE_REAL_TEMPLATE_SFINAE >::handle_getter_result(), MakePredicateFormatterFromMatcher(), testing::internal::ReturnAction< R >::operator Action< F >(), v8toolkit::ParameterBuilder< T &, std::enable_if_t<!std::is_same_v< std::remove_const_t< T >, char > &&!is_wrapped_type_v< T > > >::operator()(), v8toolkit::CastToNative< eastl::vector_set< T, Args... > >::operator()(), v8toolkit::ParameterBuilder< T &&, std::enable_if_t<!is_wrapped_type_v< T > > >::operator()(), v8toolkit::CallCallable< func::function< ReturnType(Args...)> >::operator()(), v8toolkit::CallCallable< func::function< void(Args...)> >::operator()(), v8toolkit::ParameterBuilder< char * >::operator()(), v8toolkit::enable_if_t<!std::is_reference< std::result_of_t< CastToNative< std::remove_const_t< std::remove_reference_t< Container< char *, Rest... > > > >(v8::Isolate *, v8::Local< v8::Value >)> >::value >::operator()(), v8toolkit::ParameterBuilder< char const * >::operator()(), v8toolkit::CastToJS< std::unique_ptr< T, Rest... >, std::enable_if_t<!is_wrapped_type_v< T > > >::operator()(), v8toolkit::CastToJS< T, std::enable_if_t< is_wrapped_type_v< T > > >::operator()(), v8toolkit::CastToJS< T &&, std::enable_if_t< is_wrapped_type_v< T > > >::operator()(), v8toolkit::CastToNative< T &&, std::enable_if_t< is_wrapped_type_v< T > > >::operator()(), v8toolkit::ParameterBuilder< T, std::enable_if_t< std::is_reference_v< T > &&is_wrapped_type_v< std::remove_reference_t< T > > > >::operator()(), WrappedClass::parse_all_methods(), testing::internal::ActionResultHolder< T >::PerformAction(), testing::Return(), v8toolkit::safe_move_constructor(), v8toolkit::stringify_value(), v8toolkit::Stuff< T >::stuffer(), TEST_F(), testing::internal::ReferenceOrValueWrapper< T >::Unwrap(), and WrappedClassFixture::WrappedClassFixture().
template<typename To > To testing::internal::ImplicitCast_ (To x) inline
Definition at line 1343 of file gtest-port.h.
template<typename To , typename From > To testing::internal::DownCast_ (From * f) inline
Definition at line 1367 of file gtest-port.h.
References GTEST_CHECK_, GTEST_INTENTIONAL_CONST_COND_POP_, and GTEST_INTENTIONAL_CONST_COND_PUSH_.
template<class Derived , class Base > Derived* testing::internal::CheckedDowncastToActualType (Base * base)
Definition at line 1392 of file gtest-port.h.
References CaptureStderr(), CaptureStdout(), GetArgvs(), GetCapturedStderr(), GetCapturedStdout(), GetFileSize(), GTEST_API_, GTEST_CHECK_, GTEST_CHECK_POSIX_SUCCESS_, GTEST_DISALLOW_COPY_AND_ASSIGN_, ReadEntireFile(), and TempDir().
GTEST_API_ void testing::internal::CaptureStdout ()
Referenced by CheckedDowncastToActualType().
GTEST_API_ std::string testing::internal::GetCapturedStdout ()
Referenced by CheckedDowncastToActualType().
GTEST_API_ void testing::internal::CaptureStderr ()
Referenced by CheckedDowncastToActualType().
GTEST_API_ std::string testing::internal::GetCapturedStderr ()
Referenced by CheckedDowncastToActualType().
GTEST_API_ std::string testing::internal::TempDir ()
Referenced by CheckedDowncastToActualType().
GTEST_API_ size_t testing::internal::GetFileSize (FILE * file)
Referenced by CheckedDowncastToActualType(), and v8toolkit::get_file_contents().
GTEST_API_ std::string testing::internal::ReadEntireFile (FILE * file)
Referenced by CheckedDowncastToActualType().
GTEST_API_ const ::std::vector<testing::internal::string>& testing::internal::GetArgvs ()
Referenced by CheckedDowncastToActualType().
GTEST_API_ size_t testing::internal::GetThreadCount ()
Referenced by testing::internal::ThreadLocal< testing::TestPartResultReporterInterface * >::set().
bool testing::internal::IsAlpha (char ch) inline
Definition at line 2251 of file gtest-port.h.
bool testing::internal::IsAlNum (char ch) inline
Definition at line 2254 of file gtest-port.h.
bool testing::internal::IsDigit (char ch) inline
Definition at line 2257 of file gtest-port.h.
Referenced by GetUnitTestImpl().
bool testing::internal::IsLower (char ch) inline
Definition at line 2260 of file gtest-port.h.
bool testing::internal::IsSpace (char ch) inline
Definition at line 2263 of file gtest-port.h.
Referenced by StripTrailingSpaces().
bool testing::internal::IsUpper (char ch) inline
Definition at line 2266 of file gtest-port.h.
bool testing::internal::IsXDigit (char ch) inline
Definition at line 2269 of file gtest-port.h.
bool testing::internal::IsXDigit (wchar_t ch) inline
Definition at line 2272 of file gtest-port.h.
char testing::internal::ToLower (char ch) inline
Definition at line 2277 of file gtest-port.h.
char testing::internal::ToUpper (char ch) inline
Definition at line 2280 of file gtest-port.h.
std::string testing::internal::StripTrailingSpaces (std::string str) inline
Definition at line 2284 of file gtest-port.h.
References IsSpace().
bool testing::internal::ParseInt32 (const Message & src_text, const char * str, Int32 * value)
bool testing::internal::BoolFromGTestEnv (const char * flag, bool default_val)
GTEST_API_ Int32 testing::internal::Int32FromGTestEnv (const char * flag, Int32 default_val)
std::string testing::internal::StringFromGTestEnv (const char * flag, const char * default_val)
GTEST_API_ std::string testing::internal::StringStreamToString (::std::stringstream * stream)
Referenced by CmpHelperFloatingPointEQ().
template<typename T > std::string testing::internal::GetTypeName ()
Definition at line 64 of file gtest-type-util.h.
GTEST_API_ TimeInMillis testing::internal::GetTimeInMillis ()
Referenced by GetRandomSeedFromFlag().
GTEST_API_ bool testing::internal::ShouldUseColor (bool stdout_is_tty)
GTEST_API_ std::string testing::internal::FormatTimeInMillisAsSeconds (TimeInMillis ms)
GTEST_API_ std::string testing::internal::FormatEpochTimeInMillisAsIso8601 (TimeInMillis ms)
GTEST_API_ bool testing::internal::ParseInt32Flag (const char * str, const char * flag, Int32 * value)
int testing::internal::GetRandomSeedFromFlag (Int32 random_seed_flag) inline
Definition at line 136 of file gtest-internal-inl.h.
References GetTimeInMillis().
int testing::internal::GetNextRandomSeed (int seed) inline
Definition at line 152 of file gtest-internal-inl.h.
References GTEST_CHECK_.
GTEST_API_ std::string testing::internal::CodePointToUtf8 (UInt32 code_point)
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
GTEST_API_ std::string testing::internal::WideStringToUtf8 (const wchar_t * str, int num_chars)
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
void testing::internal::WriteToShardStatusFileIfNeeded ()
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
GTEST_API_ bool testing::internal::ShouldShard (const char * total_shards_str, const char * shard_index_str, bool in_subprocess_for_death_test)
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
GTEST_API_ Int32 testing::internal::Int32FromEnvOrDie (const char * env_var, Int32 default_val)
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
GTEST_API_ bool testing::internal::ShouldRunTestOnShard (int total_shards, int shard_index, int test_id)
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
template<class Container , typename Predicate > int testing::internal::CountIf (const Container & c, Predicate predicate) inline
Definition at line 283 of file gtest-internal-inl.h.
template<class Container , typename Functor > void testing::internal::ForEach (const Container & c, Functor functor)
Definition at line 296 of file gtest-internal-inl.h.
Referenced by testing::internal::UnitTestImpl::ClearNonAdHocTestResult().
template<typename E > E testing::internal::GetElementOr (const std::vector< E > & v, int i, E default_value) inline
Definition at line 303 of file gtest-internal-inl.h.
Referenced by testing::internal::UnitTestImpl::GetMutableTestCase(), and testing::internal::UnitTestImpl::GetTestCase().
template<typename E > void testing::internal::ShuffleRange (internal::Random * random, int begin, int end, std::vector< E > * v)
Definition at line 312 of file gtest-internal-inl.h.
References testing::internal::Random::Generate(), GTEST_CHECK_, and func::swap().
Referenced by Shuffle().
template<typename E > void testing::internal::Shuffle (internal::Random * random, std::vector< E > * v) inline
Definition at line 333 of file gtest-internal-inl.h.
References ShuffleRange().
template<typename T > static void testing::internal::Delete (T * x) static
Definition at line 340 of file gtest-internal-inl.h.
GTEST_API_ FilePath testing::internal::GetCurrentExecutableName ()
GTEST_API_ void testing::internal::ParseGoogleTestFlagsOnly (int * argc, char ** argv)
Referenced by GetUnitTestImpl().
GTEST_API_ void testing::internal::ParseGoogleTestFlagsOnly (int * argc, wchar_t ** argv)
Variable Documentation
GTEST_API_ ThreadLocal<Sequence*> testing::internal::g_gmock_implicit_sequence
const char testing::internal::kInfoVerbosity[] = "info"
Definition at line 314 of file gmock-internal-utils.h.
const char testing::internal::kWarningVerbosity[] = "warning"
Definition at line 316 of file gmock-internal-utils.h.
const char testing::internal::kErrorVerbosity[] = "error"
Definition at line 318 of file gmock-internal-utils.h.
const char testing::internal::kDeathTestStyleFlag[] = "death_test_style"
Definition at line 50 of file gtest-death-test-internal.h.
const char testing::internal::kDeathTestUseFork[] = "death_test_use_fork"
Definition at line 51 of file gtest-death-test-internal.h.
const char testing::internal::kInternalRunDeathTestFlag[] = "internal_run_death_test"
Definition at line 52 of file gtest-death-test-internal.h.
GTEST_API_ const char testing::internal::kStackTraceMarker[]
class testing::internal::GTestFlagSaver testing::internal::GTEST_ATTRIBUTE_UNUSED_
Referenced by testing::internal::GTestFlagSaver::~GTestFlagSaver().
const BiggestInt testing::internal::kMaxBiggestInt
Initial value:
=
    ~(static_cast<BiggestInt>(1) << (8*sizeof(BiggestInt) - 1))
Definition at line 2439 of file gtest-port.h.
GTEST_API_ const TypeId testing::internal::kTestTypeIdInGoogleTest
const char testing::internal::kAlsoRunDisabledTestsFlag[] = "also_run_disabled_tests"
Definition at line 89 of file gtest-internal-inl.h.
const char testing::internal::kBreakOnFailureFlag[] = "break_on_failure"
Definition at line 90 of file gtest-internal-inl.h.
const char testing::internal::kCatchExceptionsFlag[] = "catch_exceptions"
Definition at line 91 of file gtest-internal-inl.h.
const char testing::internal::kColorFlag[] = "color"
Definition at line 92 of file gtest-internal-inl.h.
const char testing::internal::kFilterFlag[] = "filter"
Definition at line 93 of file gtest-internal-inl.h.
const char testing::internal::kListTestsFlag[] = "list_tests"
Definition at line 94 of file gtest-internal-inl.h.
const char testing::internal::kOutputFlag[] = "output"
Definition at line 95 of file gtest-internal-inl.h.
const char testing::internal::kPrintTimeFlag[] = "print_time"
Definition at line 96 of file gtest-internal-inl.h.
const char testing::internal::kRandomSeedFlag[] = "random_seed"
Definition at line 97 of file gtest-internal-inl.h.
const char testing::internal::kRepeatFlag[] = "repeat"
Definition at line 98 of file gtest-internal-inl.h.
const char testing::internal::kShuffleFlag[] = "shuffle"
Definition at line 99 of file gtest-internal-inl.h.
const char testing::internal::kStackTraceDepthFlag[] = "stack_trace_depth"
Definition at line 100 of file gtest-internal-inl.h.
const char testing::internal::kStreamResultToFlag[] = "stream_result_to"
Definition at line 101 of file gtest-internal-inl.h.
const char testing::internal::kThrowOnFailureFlag[] = "throw_on_failure"
Definition at line 102 of file gtest-internal-inl.h.
const char testing::internal::kFlagfileFlag[] = "flagfile"
Definition at line 103 of file gtest-internal-inl.h.
const int testing::internal::kMaxRandomSeed = 99999
Definition at line 106 of file gtest-internal-inl.h.
GTEST_API_ bool testing::internal::g_help_flag