v8toolkit: v8toolkit::CastToNative< eastl::vector_map< Key, Value, Args... > > Struct Template Reference
v8toolkit::CastToNative< eastl::vector_map< Key, Value, Args... > > Struct Template Reference
#include <casts_eastl.hpp>
Public Member Functions
eastl::vector_map< Key, Value, Args... > operator() (v8::Isolate *isolate, v8::Local< v8::Value > value) const
Detailed Description
template<class Key, class Value, class... Args>
struct v8toolkit::CastToNative< eastl::vector_map< Key, Value, Args... > >
Definition at line 33 of file casts_eastl.hpp.
Member Function Documentation
template<class Key , class Value , class... Args> eastl::vector_map<Key, Value, Args...> v8toolkit::CastToNative< eastl::vector_map< Key, Value, Args... > >::operator() (v8::Isolate * isolate, v8::Local< v8::Value > value) const inline
Definition at line 34 of file casts_eastl.hpp.
References testing::Args(), HANDLE_FUNCTION_VALUES, testing::Key(), v8toolkit::map_type_helper(), and testing::Value().
The documentation for this struct was generated from the following file:
include/casts_eastl.hpp