v8toolkit: v8toolkit::CastToNative< eastl::vector_set< T, Args... > > Struct Template Reference
v8toolkit::CastToNative< eastl::vector_set< T, Args... > > Struct Template Reference
#include <casts_eastl.hpp>
Public Member Functions
eastl::vector_set< T, Args... > operator() (v8::Isolate *isolate, v8::Local< v8::Value > value) const
Detailed Description
template<class T, class... Args>
struct v8toolkit::CastToNative< eastl::vector_set< T, Args... > >
Definition at line 54 of file casts_eastl.hpp.
Member Function Documentation
template<class T , class... Args> eastl::vector_set<T, Args...> v8toolkit::CastToNative< eastl::vector_set< T, Args... > >::operator() (v8::Isolate * isolate, v8::Local< v8::Value > value) const inline
Definition at line 55 of file casts_eastl.hpp.
References testing::Args(), HANDLE_FUNCTION_VALUES, testing::Key(), testing::internal::move(), and testing::Value().
The documentation for this struct was generated from the following file:
include/casts_eastl.hpp