v8toolkit: v8toolkit::CallCallable< func::function< ReturnType(Args...)> > Struct Template Reference
v8toolkit::CallCallable< func::function< ReturnType(Args...)> > Struct Template Reference
#include <call_callable.h>
Public Types
using NonConstReturnType = std::remove_const_t< ReturnType >
Public Member Functions
template<class... Ts, class DefaultArgsTuple = std::tuple<>, std::size_t... ArgIndexes>
void operator() (func::function< ReturnType(Args...)> &function, const v8::FunctionCallbackInfo< v8::Value > &info, std::index_sequence< ArgIndexes... >, DefaultArgsTuple &&default_args_tuple=DefaultArgsTuple(), bool return_most_derived=false)
Detailed Description
template<class ReturnType, class... Args>
struct v8toolkit::CallCallable< func::function< ReturnType(Args...)> >
CallCallable for a normal function which has a non-void return type
Definition at line 85 of file call_callable.h.
Member Typedef Documentation
template<class ReturnType , class... Args> using v8toolkit::CallCallable< func::function< ReturnType(Args...)> >::NonConstReturnType = std::remove_const_t<ReturnType>
Definition at line 86 of file call_callable.h.
Member Function Documentation
template<class ReturnType , class... Args> template<class... Ts, class DefaultArgsTuple = std::tuple<>, std::size_t... ArgIndexes> void v8toolkit::CallCallable< func::function< ReturnType(Args...)> >::operator() (func::function< ReturnType(Args...)> & function, const v8::FunctionCallbackInfo< v8::Value > & info, std::index_sequence< ArgIndexes... > , DefaultArgsTuple && default_args_tuple = DefaultArgsTuple(), bool return_most_derived = false) inline
Definition at line 89 of file call_callable.h.
References testing::Args(), testing::internal::move(), and v8toolkit::run_function().
The documentation for this struct was generated from the following file:
include/call_callable.h