v8toolkit: func::detail::function_manager Struct Reference
func::detail::function_manager Struct Reference
#include <stdfunctionreplacement.h>
Static Public Member Functions
template<typename T , typename Allocator >
static FUNC_CONSTEXPR function_manager create_default_manager ()
template<typename T , typename Allocator >
static void templated_call_move_and_destroy (manager_storage_type &lhs, manager_storage_type &&rhs)
template<typename T , typename Allocator >
static void templated_call_copy (manager_storage_type &lhs, const manager_storage_type &rhs)
template<typename T , typename Allocator >
static void templated_call_destroy (manager_storage_type &self)
template<typename T , typename Allocator >
static void templated_call_copy_functor_only (manager_storage_type &lhs, const manager_storage_type &rhs)
template<typename T , typename >
static const std::type_info & templated_call_type_id ()
template<typename T , typename Allocator >
static void * templated_call_target (const manager_storage_type &self, const std::type_info &type)
Public Attributes
void(*const call_move_and_destroy)(manager_storage_type &lhs, manager_storage_type &&rhs)
void(*const call_copy)(manager_storage_type &lhs, const manager_storage_type &rhs)
void(*const call_copy_functor_only)(manager_storage_type &lhs, const manager_storage_type &rhs)
void(*const call_destroy)(manager_storage_type &manager)
const std::type_info &(*const call_type_id)()
void *(*const call_target)(const manager_storage_type &manager, const std::type_info &type)
Detailed Description
Definition at line 263 of file stdfunctionreplacement.h.
Member Function Documentation
template<typename T , typename Allocator > static FUNC_CONSTEXPR function_manager func::detail::function_manager::create_default_manager () inline static
Definition at line 266 of file stdfunctionreplacement.h.
template<typename T , typename Allocator > static void func::detail::function_manager::templated_call_move_and_destroy (manager_storage_type & lhs, manager_storage_type && rhs) inline static
Definition at line 298 of file stdfunctionreplacement.h.
References FUNC_MOVE.
template<typename T , typename Allocator > static void func::detail::function_manager::templated_call_copy (manager_storage_type & lhs, const manager_storage_type & rhs) inline static
Definition at line 307 of file stdfunctionreplacement.h.
References func::detail::manager_storage_type::get_allocator().
template<typename T , typename Allocator > static void func::detail::function_manager::templated_call_destroy (manager_storage_type & self) inline static
Definition at line 314 of file stdfunctionreplacement.h.
template<typename T , typename Allocator > static void func::detail::function_manager::templated_call_copy_functor_only (manager_storage_type & lhs, const manager_storage_type & rhs) inline static
Definition at line 321 of file stdfunctionreplacement.h.
template<typename T , typename > static const std::type_info& func::detail::function_manager::templated_call_type_id () inline static
Definition at line 328 of file stdfunctionreplacement.h.
template<typename T , typename Allocator > static void* func::detail::function_manager::templated_call_target (const manager_storage_type & self, const std::type_info & type) inline static
Definition at line 333 of file stdfunctionreplacement.h.
Member Data Documentation
void(* const func::detail::function_manager::call_move_and_destroy) (manager_storage_type &lhs, manager_storage_type &&rhs)
Definition at line 288 of file stdfunctionreplacement.h.
Referenced by func::function< Result(Arguments...)>::function().
void(* const func::detail::function_manager::call_copy) (manager_storage_type &lhs, const manager_storage_type &rhs)
Definition at line 289 of file stdfunctionreplacement.h.
void(* const func::detail::function_manager::call_copy_functor_only) (manager_storage_type &lhs, const manager_storage_type &rhs)
Definition at line 290 of file stdfunctionreplacement.h.
Referenced by func::function< Result(Arguments...)>::function().
void(* const func::detail::function_manager::call_destroy) (manager_storage_type &manager)
Definition at line 291 of file stdfunctionreplacement.h.
const std::type_info&(* const func::detail::function_manager::call_type_id) ()
Definition at line 293 of file stdfunctionreplacement.h.
void*(* const func::detail::function_manager::call_target) (const manager_storage_type &manager, const std::type_info &type)
Definition at line 294 of file stdfunctionreplacement.h.
The documentation for this struct was generated from the following file:
include/stdfunctionreplacement.h