v8toolkit: ClassFunction::TypeInfo Struct Reference
ClassFunction::TypeInfo Struct Reference
#include <parsed_method.h>
Public Member Functions
CXXRecordDecl const * get_plain_type_decl () const
string get_jsdoc_type_name () const
corresponding javascript type
TypeInfo (QualType const &type)
bool is_const () const
TypeInfo plain_without_const () const
bool is_templated () const
void for_each_templated_type (std::function< void(QualType)>) const
bool is_void () const
Public Attributes
QualType type
QualType plain_type
string name
name of actual type
string plain_name
name of type without reference or pointers
Detailed Description
Definition at line 23 of file parsed_method.h.
Constructor & Destructor Documentation
ClassFunction::TypeInfo::TypeInfo (QualType const & type)
Definition at line 5 of file parsed_method.cpp.
References cpp_to_js_type_conversions, and name.
Referenced by get_jsdoc_type_name(), and plain_without_const().
Member Function Documentation
CXXRecordDecl const * ClassFunction::TypeInfo::get_plain_type_decl () const
Definition at line 106 of file parsed_method.cpp.
References plain_type.
Referenced by get_jsdoc_type_name(), and is_templated().
string ClassFunction::TypeInfo::get_jsdoc_type_name () const
corresponding javascript type
Definition at line 47 of file parsed_method.cpp.
References for_each_templated_type(), get_plain_type_decl(), is_templated(), name, plain_name, plain_without_const(), print_vector(), and TypeInfo().
Referenced by ClassFunction::ParameterInfo::generate_js_stub(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), and DataMember::get_js_stub().
bool ClassFunction::TypeInfo::is_const () const
Definition at line 93 of file parsed_method.cpp.
References plain_type.
Referenced by DataMember::DataMember().
ClassFunction::TypeInfo ClassFunction::TypeInfo::plain_without_const () const
Definition at line 98 of file parsed_method.cpp.
References plain_type, and TypeInfo().
Referenced by get_jsdoc_type_name(), and ClassFunction::ParameterInfo::ParameterInfo().
bool ClassFunction::TypeInfo::is_templated () const
Definition at line 116 of file parsed_method.cpp.
References get_plain_type_decl().
Referenced by get_jsdoc_type_name().
void ClassFunction::TypeInfo::for_each_templated_type (std::function< void(QualType)> callback) const
Definition at line 128 of file parsed_method.cpp.
References plain_type, and print_logging.
Referenced by get_jsdoc_type_name().
bool ClassFunction::TypeInfo::is_void () const inline
Definition at line 59 of file parsed_method.h.
Referenced by MemberFunction::generate_js_stub(), and StaticFunction::generate_js_stub().
Member Data Documentation
QualType ClassFunction::TypeInfo::type
Definition at line 29 of file parsed_method.h.
Referenced by ClassFunction::ClassFunction(), and DataMember::DataMember().
QualType ClassFunction::TypeInfo::plain_type
Definition at line 34 of file parsed_method.h.
Referenced by for_each_templated_type(), get_plain_type_decl(), is_const(), and plain_without_const().
string ClassFunction::TypeInfo::name
name of actual type
Definition at line 39 of file parsed_method.h.
Referenced by DataMember::get_bindings(), get_jsdoc_type_name(), ClassFunction::get_return_and_class_and_parameter_types_string(), ClassFunction::get_return_and_parameter_types_string(), ClassFunction::ParameterInfo::ParameterInfo(), and TypeInfo().
string ClassFunction::TypeInfo::plain_name
name of type without reference or pointers
Definition at line 42 of file parsed_method.h.
Referenced by get_jsdoc_type_name().
The documentation for this struct was generated from the following files:
class_parser/parsed_method.h
class_parser/parsed_method.cpp