v8toolkit: v8toolkit::CastToJS< std::set< T, Rest... > > Struct Template Reference
v8toolkit::CastToJS< std::set< T, Rest... > > Struct Template Reference
#include <casts.hpp>
Public Member Functions
v8::Local< v8::Value > operator() (v8::Isolate *isolate, std::set< T, Rest... > const &set)
v8::Local< v8::Value > operator() (v8::Isolate *isolate, std::set< T, Rest... > &&set)
Detailed Description
template<class T, class... Rest>
struct v8toolkit::CastToJS< std::set< T, Rest... > >
Definition at line 1008 of file casts.hpp.
Member Function Documentation
template<class T , class... Rest> v8::Local<v8::Value> v8toolkit::CastToJS< std::set< T, Rest... > >::operator() (v8::Isolate * isolate, std::set< T, Rest... > const & set) inline
Definition at line 1009 of file casts.hpp.
References v8toolkit::cast_to_js_vector_helper().
template<class T , class... Rest> v8::Local<v8::Value> v8toolkit::CastToJS< std::set< T, Rest... > >::operator() (v8::Isolate * isolate, std::set< T, Rest... > && set) inline
Definition at line 1012 of file casts.hpp.
References testing::Args(), and v8toolkit::cast_to_js_vector_helper().
The documentation for this struct was generated from the following file:
include/casts.hpp