v8toolkit: v8toolkit::CastToJS< eastl::vector< T, Rest... > > Struct Template Reference
v8toolkit::CastToJS< eastl::vector< T, Rest... > > Struct Template Reference
#include <casts_eastl.hpp>
Public Member Functions
v8::Local< v8::Value > operator() (v8::Isolate *isolate, eastl::vector< T, Rest... > const &vector)
v8::Local< v8::Value > operator() (v8::Isolate *isolate, eastl::vector< T, Rest... > &&vector)
Detailed Description
template<class T, class... Rest>
struct v8toolkit::CastToJS< eastl::vector< T, Rest... > >
Definition at line 102 of file casts_eastl.hpp.
Member Function Documentation
template<class T , class... Rest> v8::Local< v8::Value > v8toolkit::CastToJS< eastl::vector< T, Rest... > >::operator() (v8::Isolate * isolate, eastl::vector< T, Rest... > const & vector)
Definition at line 111 of file casts_eastl.hpp.
References testing::A(), and v8toolkit::cast_to_js_vector_helper().
template<class T , class... Rest> v8::Local<v8::Value> v8toolkit::CastToJS< eastl::vector< T, Rest... > >::operator() (v8::Isolate * isolate, eastl::vector< T, Rest... > && vector) inline
Definition at line 104 of file casts_eastl.hpp.
References v8toolkit::CastToNative< T, class >::operator()().
The documentation for this struct was generated from the following file:
include/casts_eastl.hpp