v8toolkit: DataMember Struct Reference
DataMember Struct Reference
#include <parsed_method.h>
Public Member Functions
DataMember (WrappedClass &wrapped_class, WrappedClass &declared_in, FieldDecl *field_decl)
string get_js_stub ()
string get_bindings ()
Public Attributes
WrappedClass & wrapped_class
WrappedClass & declared_in
string short_name
string long_name
ClassFunction::TypeInfo type
FieldDecl const * field_decl
Annotations annotations
bool is_const = false
Detailed Description
Definition at line 151 of file parsed_method.h.
Constructor & Destructor Documentation
DataMember::DataMember (WrappedClass & wrapped_class, WrappedClass & declared_in, FieldDecl * field_decl)
Definition at line 154 of file parsed_method.cpp.
References WrappedClass::add_member_name(), annotations, WrappedClass::declaration_count, Annotations::has(), ClassFunction::TypeInfo::is_const(), is_const, short_name, ClassFunction::TypeInfo::type, type, update_wrapped_class_for_type(), and V8TOOLKIT_READONLY_STRING.
Member Function Documentation
string DataMember::get_js_stub ()
Definition at line 176 of file parsed_method.cpp.
References ClassFunction::TypeInfo::get_jsdoc_type_name(), short_name, and type.
string DataMember::get_bindings ()
Definition at line 185 of file parsed_method.cpp.
References is_const, ClassFunction::TypeInfo::name, and type.
Member Data Documentation
WrappedClass& DataMember::wrapped_class
Definition at line 152 of file parsed_method.h.
WrappedClass& DataMember::declared_in
Definition at line 153 of file parsed_method.h.
string DataMember::short_name
Definition at line 154 of file parsed_method.h.
Referenced by DataMember(), and get_js_stub().
string DataMember::long_name
Definition at line 155 of file parsed_method.h.
ClassFunction::TypeInfo DataMember::type
Definition at line 156 of file parsed_method.h.
Referenced by DataMember(), ClassFunction::ParameterInfo::generate_js_stub(), get_bindings(), and get_js_stub().
FieldDecl const* DataMember::field_decl
Definition at line 157 of file parsed_method.h.
Annotations DataMember::annotations
Definition at line 158 of file parsed_method.h.
Referenced by DataMember().
bool DataMember::is_const = false
Definition at line 161 of file parsed_method.h.
Referenced by DataMember(), and get_bindings().
The documentation for this struct was generated from the following files:
class_parser/parsed_method.h
class_parser/parsed_method.cpp