v8toolkit: ClassFunction Struct Reference
ClassFunction Struct Reference
#include <parsed_method.h>
Classes
class ParameterInfo
struct TypeInfo
Public Member Functions
string get_default_argument_tuple_string () const
string get_signature_string ()
ClassFunction (WrappedClass &wrapped_class, CXXMethodDecl const *method_decl)
bool compare_signatures (ClassFunction const &other)
string get_parameter_types_string () const
string get_return_and_class_and_parameter_types_string () const
string get_return_and_parameter_types_string () const
string get_js_input_parameter_string () const
Public Attributes
WrappedClass & wrapped_class
bool is_static
bool is_virtual
bool new_virtual
TypeInfo return_type
string return_type_comment
vector< ParameterInfo > parameters
CXXMethodDecl const * method_decl
string name
string js_name
CompilerInstance & compiler_instance
Annotations annotations
Detailed Description
Definition at line 12 of file parsed_method.h.
Constructor & Destructor Documentation
ClassFunction::ClassFunction (WrappedClass & wrapped_class, CXXMethodDecl const * method_decl)
Definition at line 267 of file parsed_method.cpp.
References annotations, compiler_instance, data_warning(), WrappedClass::declaration_count, ClassFunction::ParameterInfo::description, Annotations::get_regex(), get_source_for_source_range(), js_name, name, parameters, return_type, ClassFunction::TypeInfo::type, update_wrapped_class_for_type(), and V8TOOLKIT_USE_NAME_PREFIX.
Member Function Documentation
string ClassFunction::get_default_argument_tuple_string () const
Definition at line 427 of file parsed_method.cpp.
References get_type_string(), and parameters.
Referenced by MemberFunction::generate_js_bindings(), StaticFunction::generate_js_bindings(), and ConstructorFunction::generate_js_bindings().
string ClassFunction::get_signature_string ()
Definition at line 602 of file parsed_method.cpp.
References name, and parameters.
bool ClassFunction::compare_signatures (ClassFunction const & other)
string ClassFunction::get_parameter_types_string () const
Definition at line 487 of file parsed_method.cpp.
References parameters.
Referenced by ConstructorFunction::generate_js_bindings(), get_return_and_class_and_parameter_types_string(), and get_return_and_parameter_types_string().
string ClassFunction::get_return_and_class_and_parameter_types_string () const
Definition at line 463 of file parsed_method.cpp.
References get_parameter_types_string(), ClassFunction::TypeInfo::name, parameters, and return_type.
Referenced by MemberFunction::generate_js_bindings().
string ClassFunction::get_return_and_parameter_types_string () const
Definition at line 475 of file parsed_method.cpp.
References get_parameter_types_string(), ClassFunction::TypeInfo::name, parameters, and return_type.
Referenced by StaticFunction::generate_js_bindings().
string ClassFunction::get_js_input_parameter_string () const
Definition at line 501 of file parsed_method.cpp.
References parameters.
Referenced by MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), and ConstructorFunction::generate_js_stub().
Member Data Documentation
WrappedClass& ClassFunction::wrapped_class
Definition at line 16 of file parsed_method.h.
Referenced by ClassFunction::ParameterInfo::ParameterInfo().
bool ClassFunction::is_static
Definition at line 17 of file parsed_method.h.
bool ClassFunction::is_virtual
Definition at line 18 of file parsed_method.h.
bool ClassFunction::new_virtual
Definition at line 21 of file parsed_method.h.
TypeInfo ClassFunction::return_type
Definition at line 87 of file parsed_method.h.
Referenced by ClassFunction(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), get_return_and_class_and_parameter_types_string(), and get_return_and_parameter_types_string().
string ClassFunction::return_type_comment
Definition at line 88 of file parsed_method.h.
vector<ParameterInfo> ClassFunction::parameters
Definition at line 89 of file parsed_method.h.
Referenced by ClassFunction(), generate_bidirectional_classes(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), ConstructorFunction::generate_js_stub(), get_default_argument_tuple_string(), get_js_input_parameter_string(), get_parameter_types_string(), get_return_and_class_and_parameter_types_string(), get_return_and_parameter_types_string(), and get_signature_string().
CXXMethodDecl const* ClassFunction::method_decl
Definition at line 90 of file parsed_method.h.
Referenced by MemberFunction::generate_js_bindings().
string ClassFunction::name
Definition at line 93 of file parsed_method.h.
Referenced by ClassFunction(), ConstructorFunction::ConstructorFunction(), MemberFunction::generate_js_bindings(), StaticFunction::generate_js_bindings(), and get_signature_string().
string ClassFunction::js_name
Definition at line 96 of file parsed_method.h.
Referenced by ClassFunction(), ConstructorFunction::ConstructorFunction(), MemberFunction::generate_js_bindings(), StaticFunction::generate_js_bindings(), ConstructorFunction::generate_js_bindings(), MemberFunction::generate_js_stub(), StaticFunction::generate_js_stub(), MemberFunction::MemberFunction(), and StaticFunction::StaticFunction().
CompilerInstance& ClassFunction::compiler_instance
Definition at line 97 of file parsed_method.h.
Referenced by ClassFunction(), and ConstructorFunction::ConstructorFunction().
Annotations ClassFunction::annotations
Definition at line 98 of file parsed_method.h.
Referenced by ClassFunction().
The documentation for this struct was generated from the following files:
class_parser/parsed_method.h
class_parser/parsed_method.cpp