v8toolkit: v8toolkit::RequireResult Struct Reference
v8toolkit::RequireResult Struct Reference
#include <v8toolkit.h>
Public Member Functions
RequireResult (v8::Isolate *isolate, v8::Local< v8::Context > context, v8::Local< v8::Function > function, v8::Local< v8::Value > result, const time_t &time)
Public Attributes
v8::Isolate * isolate
v8::Global< v8::Context > context
v8::Global< v8::Function > function
v8::Global< v8::Value > result
time_t time
Detailed Description
Definition at line 955 of file v8toolkit.h.
Constructor & Destructor Documentation
v8toolkit::RequireResult::RequireResult (v8::Isolate * isolate, v8::Local< v8::Context > context, v8::Local< v8::Function > function, v8::Local< v8::Value > result, const time_t & time) inline
Definition at line 961 of file v8toolkit.h.
References v8toolkit::SetWeakCallbackData::callback, v8toolkit::dump_prototypes(), v8toolkit::foreach_directory(), v8toolkit::foreach_file(), v8toolkit::get_interesting_properties(), v8toolkit::require(), v8toolkit::require_directory(), and v8toolkit::run_script().
Member Data Documentation
v8::Isolate* v8toolkit::RequireResult::isolate
Definition at line 956 of file v8toolkit.h.
v8::Global<v8::Context> v8toolkit::RequireResult::context
Definition at line 957 of file v8toolkit.h.
v8::Global<v8::Function> v8toolkit::RequireResult::function
Definition at line 958 of file v8toolkit.h.
v8::Global<v8::Value> v8toolkit::RequireResult::result
Definition at line 959 of file v8toolkit.h.
time_t v8toolkit::RequireResult::time
Definition at line 960 of file v8toolkit.h.
The documentation for this struct was generated from the following file:
include/v8toolkit.h