v8toolkit: v8toolkit::Stuff< T > Struct Template Reference
v8toolkit::Stuff< T > Struct Template Reference
#include <v8helpers.h>
Public Member Functions
Stuff (T &&t)
Stuff (std::unique_ptr< T > t)
T * get ()
Static Public Member Functions
static std::unique_ptr< Stuff< T > > stuffer (T &&t)
static std::unique_ptr< Stuff< T > > stuffer (T const &t)
Public Attributes
std::unique_ptr< T > stuffed
Detailed Description
template<class T>
struct v8toolkit::Stuff< T >
Definition at line 567 of file v8helpers.h.
Constructor & Destructor Documentation
template<class T> v8toolkit::Stuff< T >::Stuff (T && t) inline
Definition at line 568 of file v8helpers.h.
template<class T> v8toolkit::Stuff< T >::Stuff (std::unique_ptr< T > t) inline
Definition at line 569 of file v8helpers.h.
Member Function Documentation
template<class T> static std::unique_ptr<Stuff<T> > v8toolkit::Stuff< T >::stuffer (T && t) inline static
Definition at line 572 of file v8helpers.h.
References testing::internal::move().
template<class T> static std::unique_ptr<Stuff<T> > v8toolkit::Stuff< T >::stuffer (T const & t) inline static
Definition at line 573 of file v8helpers.h.
References testing::internal::move().
template<class T> T* v8toolkit::Stuff< T >::get () inline
Definition at line 575 of file v8helpers.h.
Referenced by v8toolkit::ParameterBuilder< char * >::operator()(), v8toolkit::enable_if_t<!std::is_reference< std::result_of_t< CastToNative< std::remove_const_t< std::remove_reference_t< Container< char *, Rest... > > > >(v8::Isolate *, v8::Local< v8::Value >)> >::value >::operator()(), v8toolkit::enable_if_t<!std::is_reference< std::result_of_t< CastToNative< std::remove_reference_t< Container< const char *, Rest... > > >(v8::Isolate *, v8::Local< v8::Value >) > >::value >::operator()(), and v8toolkit::ParameterBuilder< char const * >::operator()().
Member Data Documentation
template<class T> std::unique_ptr<T> v8toolkit::Stuff< T >::stuffed
Definition at line 576 of file v8helpers.h.
The documentation for this struct was generated from the following file:
include/v8helpers.h