v8toolkit: test/v8_class_wrapper-test.cpp File Reference
v8_class_wrapper-test.cpp File Reference
#include "testing.h"
Classes
struct FlaggedDeleter< T >
Functions
TEST_F (JavaScriptFixture, Helpers)
TEST_F (JavaScriptFixture, NumberTypes)
TEST_F (JavaScriptFixture, ParameterBuilder)
TEST_F (JavaScriptFixture, CallingFunctionsWithUnwrappedTypes)
TEST_F (JavaScriptFixture, StringTypes)
TEST_F (JavaScriptFixture, UniquePointer_UnwrappedTypes)
TEST_F (JavaScriptFixture, Vectors)
TEST_F (JavaScriptFixture, Sets)
TEST_F (JavaScriptFixture, Maps)
TEST_F (JavaScriptFixture, ContainerTypes)
TEST_F (JavaScriptFixture, ObjectLifetimes)
TEST_F (JavaScriptFixture, StdFunctionCasts)
TEST_F (JavaScriptFixture, TEST_NAME)
Function Documentation
TEST_F (JavaScriptFixture , Helpers)
Definition at line 5 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ.
TEST_F (JavaScriptFixture , NumberTypes)
Definition at line 14 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ.
TEST_F (JavaScriptFixture , ParameterBuilder)
Definition at line 41 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
TEST_F (JavaScriptFixture , CallingFunctionsWithUnwrappedTypes)
Definition at line 68 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, and EXPECT_TRUE.
TEST_F (JavaScriptFixture , StringTypes)
Definition at line 88 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, and EXPECT_STREQ.
TEST_F (JavaScriptFixture , UniquePointer_UnwrappedTypes)
Definition at line 114 of file v8_class_wrapper-test.cpp.
References EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, and testing::internal::move().
TEST_F (JavaScriptFixture , Vectors)
Definition at line 170 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, and testing::internal::move().
TEST_F (JavaScriptFixture , Sets)
Definition at line 215 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, EXPECT_NE, and testing::internal::move().
TEST_F (JavaScriptFixture , Maps)
Definition at line 274 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, and testing::internal::move().
TEST_F (JavaScriptFixture , ContainerTypes)
Move each of these into its own test for its container type
Definition at line 322 of file v8_class_wrapper-test.cpp.
References std::tr1::make_tuple().
TEST_F (JavaScriptFixture , ObjectLifetimes)
Definition at line 377 of file v8_class_wrapper-test.cpp.
References v8toolkit::Isolate::create_context(), EXPECT_FALSE, and EXPECT_TRUE.
TEST_F (JavaScriptFixture , StdFunctionCasts)
Definition at line 415 of file v8_class_wrapper-test.cpp.
References EXPECT_EQ, EXPECT_FALSE, and EXPECT_TRUE.
TEST_F (JavaScriptFixture , TEST_NAME)
Definition at line 449 of file v8_class_wrapper-test.cpp.