#!/usr/bin/env bash

BUILD_DIR=Debug

if [ -d "$BUILD_DIR" ]; then
   echo "Build directory \"$BUILD_DIR\" already exists, exiting without doing anything"
   exit 1
fi
mkdir Debug
cd Debug


cmake \
    -DCMAKE_CXX_COMPILER=$CLANG_HOME/bin/clang++ \
    -DCMAKE_C_COMPILER=$CLANG_HOME/bin/clang \
    -DV8_INCLUDE_DIR=$V8_DIR/include \
    -DV8_BASE_SHARED_LIB_DIR=$V8_LIB_DIR \
    -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$CLANG_HOME/bin/clang++  -DCMAKE_CXX_FLAGS=-stdlib=libc++   ..