v8toolkit: include/casts.hpp File Reference
casts.hpp File Reference
#include <assert.h>
#include <string>
#include <vector>
#include <map>
#include <unordered_map>
#include <list>
#include <deque>
#include <array>
#include <memory>
#include <utility>
#include "v8.h"
#include "v8helpers.h"
Classes
struct v8toolkit::CastToNative< T, class >
struct v8toolkit::CastToNative< void >
struct CastToNative< std::function< Return(Params...)> >
struct v8toolkit::CastToNative< std::pair< FirstT, SecondT > >
struct v8toolkit::CastToNative< std::pair< FirstT, SecondT > const >
struct CastToNative< v8::Local< v8::Function > >
struct CastToNative< char * >
struct CastToNative< const char * >
struct CastToNative< std::vector< ElementType > >
struct CastToNative< const std::vector< ElementType > >
struct CastToNative< std::unique_ptr< T, Rest... >, std::enable_if_t< std::is_copy_constructible< T >::value > >
struct CastToNative< std::unique_ptr< T, Rest... >, std::enable_if_t<!std::is_copy_constructible< T >::value > >
struct CastToNative< std::map< Key, Value, Args... > >
struct CastToNative< std::multimap< Key, Value, Args... > >
struct CastToNative< std::map< Key, Value, Args... > const >
struct CastToJS< T, class >
struct CastToJS< T ** >
struct CastToJS< v8::Local< v8::Object > >
struct CastToJS< v8::Local< v8::Value > >
struct CastToJS< v8::Global< v8::Value > & >
struct CastToJS< std::pair< T1, T2 > >
struct CastToJS< std::pair< T1, T2 > const >
struct CastToJS< std::vector< T, Rest... > >
struct CastToJS< std::vector< T, Rest... > const >
struct CastToJS< std::list< U, Rest... > >
struct CastToJS< std::list< U, Rest... > const >
struct CastToJS< std::map< A, B, Rest... > >
struct CastToJS< std::map< A, B, Rest... > const >
struct CastToJS< std::multimap< A, B, Rest... > >
struct CastToJS< std::multimap< A, B, Rest... > const >
struct CastToJS< std::unordered_map< A, B, Rest... > >
struct CastToJS< std::unordered_map< A, B, Rest... > const >
struct CastToJS< std::deque< T, Rest... > >
struct CastToJS< std::deque< T, Rest... > const >
struct CastToJS< std::array< T, N > >
struct CastToJS< std::array< T, N > const >
struct CastToJS< std::unique_ptr< T, Rest... > >
struct CastToJS< std::unique_ptr< T, Rest... > & >
struct CastToJS< std::unique_ptr< T, Rest... > const & >
struct CastToJS< std::shared_ptr< T > >
struct CastToJS< std::shared_ptr< T > const >
struct CastTupleToJS< position, T >
struct CastTupleToJS< 0, std::tuple< Args... > >
struct CastTupleToJS< position, std::tuple< Args... > >
struct CastToJS< std::tuple< Args... > >
Namespaces
v8toolkit
Macros
#define V8TOOLKIT_COMMA ,
#define HANDLE_FUNCTION_VALUES
#define CAST_TO_NATIVE_WITH_CONST(TYPE, TEMPLATE)
#define CAST_TO_NATIVE_PRIMITIVE_WITH_CONST(TYPE)
#define CAST_TO_JS_TEMPLATED(TYPE, TEMPLATE)
#define CAST_TO_JS(TYPE)
Functions
v8toolkit::CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (bool) return static_cast< bool >(value -> ToBoolean() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (long long) return static_cast< long long >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (unsigned long long) return static_cast< unsigned long long >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (long) return static_cast< long >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (unsigned long) return static_cast< unsigned long >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (int) return static_cast< int >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (unsigned int) return static_cast< unsigned int >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (short) return static_cast< short >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (char) return static_cast< char >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (wchar_t) return static_cast< wchar_t >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (char16_t) return static_cast< char16_t >(value -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (char32_t) return static_cast< char32_t >(value -> ToInteger() ->Value())
template<template< class, class > class ContainerTemplate, class SecondT , class FirstT >
ContainerTemplate< FirstT, SecondT > pair_type_helper (v8::Isolate *isolate, v8::Local< v8::Value > value)
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (float) return static_cast< float >(value -> ToNumber() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (double) return static_cast< double >(value -> ToNumber() ->Value())
template<template< class, class, class... > class ContainerTemplate, class Key , class Value , class... Rest>
ContainerTemplate< Key, Value, Rest... > map_type_helper (v8::Isolate *isolate, v8::Local< v8::Value > value)
template<template< class, class, class... > class ContainerTemplate, class Key , class Value , class... Rest>
ContainerTemplate< Key, Value, Rest... > multimap_type_helper (v8::Isolate *isolate, v8::Local< v8::Value > value)
CAST_TO_JS (bool)
CAST_TO_JS (char)
CAST_TO_JS (unsigned char)
CAST_TO_JS (wchar_t)
CAST_TO_JS (char16_t)
CAST_TO_JS (char32_t)
CAST_TO_JS (short)
CAST_TO_JS (int)
CAST_TO_JS (long)
CAST_TO_JS (unsigned long long)
CAST_TO_JS (float)
CAST_TO_JS (double)
CAST_TO_JS (long double)
CAST_TO_JS (std::string)
CAST_TO_JS (char *)
template<template< class... > class VectorTemplate, class ValueType , class... Rest>
v8::Local< v8::Value > cast_to_js_vector_helper (v8::Isolate *isolate, VectorTemplate< ValueType, Rest... > const &vector)
Class Documentation
CastToJS
struct CastToJS
template<typename T, class = void>
struct CastToJS< T, class >
Casts from a native type to a boxed Javascript type
Definition at line 420 of file casts.hpp.
CastTupleToJS
struct CastTupleToJS
template<int position, class T>
struct CastTupleToJS< position, T >
Definition at line 769 of file casts.hpp.
Macro Definition Documentation
V8TOOLKIT_COMMA
#define V8TOOLKIT_COMMA ,
Definition at line 23 of file casts.hpp.
Referenced by CAST_TO_JS().
HANDLE_FUNCTION_VALUES
#define HANDLE_FUNCTION_VALUES
Value:
{ \
    if (value->IsFunction()) { \
        value = v8toolkit::call_simple_javascript_function(isolate, v8::Local<v8::Function>::Cast(value)); \
    } \
    }
Definition at line 28 of file casts.hpp.
Referenced by v8toolkit::CastToNative< std::pair< FirstT, SecondT > const >::operator()(), CastToNative< char * >::operator()(), CastToNative< const char * >::operator()(), CastToNative< std::vector< ElementType > >::operator()(), CastToNative< std::unique_ptr< T, Rest... >, std::enable_if_t< std::is_copy_constructible< T >::value > >::operator()(), CastToNative< std::unique_ptr< T, Rest... >, std::enable_if_t<!std::is_copy_constructible< T >::value > >::operator()(), and pair_type_helper().
CAST_TO_NATIVE_WITH_CONST
#define CAST_TO_NATIVE_WITH_CONST (TYPE, TEMPLATE)
Value:
template<TEMPLATE> \
 struct v8toolkit::CastToNative<TYPE>{              \
    TYPE operator()(v8::Isolate * isolate, v8::Local<v8::Value> value) const { \
        return v8toolkit::CastToNative<const TYPE>()(isolate, value);   \
    } \
}; \
\
template<TEMPLATE> \
 struct v8toolkit::CastToNative<TYPE const> {               \
    TYPE const operator()(v8::Isolate * isolate, v8::Local<v8::Value> value) const { \
    HANDLE_FUNCTION_VALUES;
Definition at line 38 of file casts.hpp.
Referenced by CAST_TO_JS().
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST
#define CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (TYPE)
Value:
template<> \
 struct v8toolkit::CastToNative<TYPE> {             \
    TYPE operator()(v8::Isolate * isolate, v8::Local<v8::Value> value) const; \
}; \
\
template<> \
 struct v8toolkit::CastToNative<const TYPE>{                \
    const TYPE operator()(v8::Isolate * isolate, v8::Local<v8::Value> value) const { \
        return v8toolkit::CastToNative<TYPE>()(isolate, value); \
    } \
}; \
 inline TYPE v8toolkit::CastToNative<TYPE>::operator()(v8::Isolate * isolate, v8::Local<v8::Value> value) const { \
    HANDLE_FUNCTION_VALUES;
Definition at line 52 of file casts.hpp.
CAST_TO_JS_TEMPLATED
#define CAST_TO_JS_TEMPLATED (TYPE, TEMPLATE)
Value:
template<TEMPLATE> struct v8toolkit::CastToJS<const TYPE> {     \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE const & value) const; \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE const && value) const { return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
template<TEMPLATE> \
struct v8toolkit::CastToJS<TYPE> {                  \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE & value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE && value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
template<TEMPLATE> \
struct v8toolkit::CastToJS<TYPE &> {                    \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE & value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
template<TEMPLATE> \
struct v8toolkit::CastToJS<const TYPE &> {                  \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE const & value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
template<TEMPLATE> \
inline v8::Local<v8::Value>  v8toolkit::CastToJS<const TYPE>::operator()(v8::Isolate * isolate, TYPE const & value) const
Definition at line 69 of file casts.hpp.
CAST_TO_JS
#define CAST_TO_JS (TYPE)
Value:
template<> struct v8toolkit::CastToJS<const TYPE> {     \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, const TYPE value) const; \
}; \
template<> \
 struct v8toolkit::CastToJS<TYPE> {                 \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
template<> \
 struct v8toolkit::CastToJS<TYPE &> {                   \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
 template<> \
 struct v8toolkit::CastToJS<const TYPE &> {                 \
    v8::Local<v8::Value> operator()(v8::Isolate * isolate, TYPE value) const {return v8toolkit::CastToJS<const TYPE>()(isolate, value);} \
}; \
inline v8::Local<v8::Value>  v8toolkit::CastToJS<const TYPE>::operator()(v8::Isolate * isolate, const TYPE value) const
Definition at line 92 of file casts.hpp.
Referenced by CAST_TO_JS().
Function Documentation
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [1/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (long long) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [2/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (unsigned long long) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [3/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (long) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [4/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (unsigned long) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [5/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (int) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [6/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (unsigned int) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [7/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (short) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [8/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (char) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [9/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (wchar_t) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [10/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (char16_t) -> ToInteger() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [11/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (char32_t) -> ToInteger() ->Value())
pair_type_helper()
template<template< class, class > class ContainerTemplate, class SecondT , class FirstT > ContainerTemplate<FirstT, SecondT> pair_type_helper (v8::Isolate * isolate, v8::Local< v8::Value > value)
Definition at line 158 of file casts.hpp.
References v8toolkit::get_array_length(), HANDLE_FUNCTION_VALUES, and v8toolkit::stringify_value().
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [12/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (float) -> ToNumber() ->Value())
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST() [13/13]
CAST_TO_NATIVE_PRIMITIVE_WITH_CONST (double) -> ToNumber() ->Value())
map_type_helper()
template<template< class, class, class... > class ContainerTemplate, class Key , class Value , class... Rest> ContainerTemplate<Key, Value, Rest...> map_type_helper (v8::Isolate * isolate, v8::Local< v8::Value > value)
Definition at line 336 of file casts.hpp.
References v8toolkit::for_each_own_property(), and v8toolkit::stringify_value().
Referenced by v8toolkit::CastToNative< eastl::vector_map< Key, Value, Args... > >::operator()(), and CastToNative< std::map< Key, Value, Args... > >::operator()().
multimap_type_helper()
template<template< class, class, class... > class ContainerTemplate, class Key , class Value , class... Rest> ContainerTemplate<Key, Value, Rest...> multimap_type_helper (v8::Isolate * isolate, v8::Local< v8::Value > value)
Definition at line 364 of file casts.hpp.
References v8toolkit::for_each_own_property(), v8toolkit::for_each_value(), and v8toolkit::stringify_value().
Referenced by v8toolkit::CastToNative< eastl::vector_multimap< Key, Value, Args... > >::operator()(), and CastToNative< std::multimap< Key, Value, Args... > >::operator()().
CAST_TO_JS() [1/15]
CAST_TO_JS (bool)
Definition at line 422 of file casts.hpp.
CAST_TO_JS() [2/15]
CAST_TO_JS (char)
Definition at line 426 of file casts.hpp.
CAST_TO_JS() [3/15]
CAST_TO_JS (unsigned char)
Definition at line 427 of file casts.hpp.
CAST_TO_JS() [4/15]
CAST_TO_JS (wchar_t)
Definition at line 429 of file casts.hpp.
CAST_TO_JS() [5/15]
CAST_TO_JS (char16_t)
Definition at line 430 of file casts.hpp.
CAST_TO_JS() [6/15]
CAST_TO_JS (char32_t)
Definition at line 431 of file casts.hpp.
CAST_TO_JS() [7/15]
CAST_TO_JS (short)
Definition at line 432 of file casts.hpp.
References CAST_TO_JS.
CAST_TO_JS() [8/15]
CAST_TO_JS (int)
Definition at line 437 of file casts.hpp.
References CAST_TO_JS.
CAST_TO_JS() [9/15]
CAST_TO_JS (long long)
Definition at line 440 of file casts.hpp.
References CAST_TO_JS.
CAST_TO_JS() [10/15]
CAST_TO_JS (unsigned long long)
Definition at line 444 of file casts.hpp.
CAST_TO_JS() [11/15]
CAST_TO_JS (float)
Definition at line 449 of file casts.hpp.
CAST_TO_JS() [12/15]
CAST_TO_JS (double)
Definition at line 450 of file casts.hpp.
CAST_TO_JS() [13/15]
CAST_TO_JS (long double)
Definition at line 451 of file casts.hpp.
CAST_TO_JS() [14/15]
CAST_TO_JS (std::string)
Definition at line 454 of file casts.hpp.
CAST_TO_JS() [15/15]
CAST_TO_JS (char *)
Definition at line 456 of file casts.hpp.
cast_to_js_vector_helper()
template<template< class... > class VectorTemplate, class ValueType , class... Rest> v8::Local< v8::Value > cast_to_js_vector_helper (v8::Isolate * isolate, VectorTemplate< ValueType, Rest... > const & vector)
Definition at line 949 of file casts.hpp.
Referenced by CastToJS< eastl::vector< T, Rest... > >::operator()().