v8helper: V8ClassWrapper< T > Class Template Reference
V8ClassWrapper< T > Class Template Reference
#include <v8_class_wrapper.hpp>
Public Types
typedef std::function< void(const v8::FunctionCallbackInfo< v8::Value > &info)> StdFunctionCallbackType
Public Member Functions
virtual ~V8ClassWrapper ()
template<typename... CONSTRUCTOR_PARAMETER_TYPES>
V8ClassWrapper< T > & add_constructor (std::string js_constructor_name, v8::Local< v8::ObjectTemplate > &parent_template)
template<class BEHAVIOR >
v8::Local< v8::Object > wrap_existing_cpp_object (v8::Local< v8::Context > context, T *existing_cpp_object)
template<typename MEMBER_TYPE >
V8ClassWrapper< T > & add_member (MEMBER_TYPE T::*member, std::string member_name)
template<class METHOD_TYPE >
V8ClassWrapper< T > & add_method (METHOD_TYPE method, std::string method_name)
Static Public Member Functions
static V8ClassWrapper< T > & get_instance (v8::Isolate *isolate)
Detailed Description
template<class T>
class V8ClassWrapper< T >
Provides a mechanism for creating javascript-ready objects from an arbitrary C++ class Can provide a JS constructor method or wrap objects created in another c++ function
Definition at line 76 of file v8_class_wrapper.hpp.
Member Typedef Documentation
template<class T> typedef std::function<void(const v8::FunctionCallbackInfo<v8::Value>& info)> V8ClassWrapper< T >::StdFunctionCallbackType
Definition at line 306 of file v8_class_wrapper.hpp.
Constructor & Destructor Documentation
template<class T> virtual V8ClassWrapper< T >::~V8ClassWrapper () inline virtual
V8ClassWrapper objects shouldn't be deleted during the normal flow of your program unless the associated isolate is going away forever. Things will break otherwise as no additional objects will be able to be created even though V8 will still present the ability to your javascript (I think)
Definition at line 232 of file v8_class_wrapper.hpp.
     {
         // this was happening when it wasn't supposed to, like when making temp copies.   need to disable copying or something
         //   if this line is to be added back
         // isolate_to_wrapper_map.erase(this->isolate);
     }
Member Function Documentation
template<class T> static V8ClassWrapper<T>& V8ClassWrapper< T >::get_instance (v8::Isolate * isolate) inline static
Returns a "singleton-per-isolate" instance of the V8ClassWrapper for the wrapped class type. For each isolate you need to add constructors/methods/members separately.
Definition at line 212 of file v8_class_wrapper.hpp.
Referenced by CastToJS< T >::operator()(), and CastToJS< T * >::operator()().
     {
         // if (DEBUG) printf("isolate to wrapper map %p size: %d\n", &isolate_to_wrapper_map, (int)isolate_to_wrapper_map.size());
         if (isolate_to_wrapper_map.find(isolate) == isolate_to_wrapper_map.end()) {
             auto new_object = new V8ClassWrapper<T>(isolate);
             isolate_to_wrapper_map.insert(std::make_pair(isolate, new_object));
             // if (DEBUG) printf("Creating instance %p for isolate: %p\n", new_object, isolate);
         }
         // if (DEBUG) printf("(after) isoate to wrapper map size: %d\n", (int)isolate_to_wrapper_map.size());
         auto object = isolate_to_wrapper_map[isolate];
         // if (DEBUG) printf("Returning v8 wrapper: %p\n", object);
         return *object;
     }
template<class T> template<typename... CONSTRUCTOR_PARAMETER_TYPES> V8ClassWrapper<T>& V8ClassWrapper< T >::add_constructor (std::string js_constructor_name, v8::Local< v8::ObjectTemplate > & parent_template) inline
Creates a javascript method of the specified name which, when called with the "new" keyword, will return a new object of this type
Definition at line 244 of file v8_class_wrapper.hpp.
     {
         // if you add a constructor after adding a member or method, it will be missing on objects created with
         //   this constructor
         assert(member_or_method_added == false);
         // create a function template even if no javascript constructor will be used so
         //   FunctionTemplate::InstanceTemplate can be populated.   That way if a javascript constructor is added
         //   later the FunctionTemplate will be ready to go
         auto constructor_template = v8::FunctionTemplate::New(isolate, V8ClassWrapper<T>::v8_constructor<CONSTRUCTOR_PARAMETER_TYPES...>);
         // When creating a new object, make sure they have room for a c++ object to shadow it
         constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
         // store it so it doesn't go away
         this->constructor_templates.push_back(constructor_template);
         // Add the constructor function to the parent object template (often the global template)
         parent_template->Set(v8::String::NewFromUtf8(isolate, js_constructor_name.c_str()), constructor_template);
         this->constructor_templates.push_back(constructor_template);
         return *this;
     }
template<class T> template<class BEHAVIOR > v8::Local<v8::Object> V8ClassWrapper< T >::wrap_existing_cpp_object (v8::Local< v8::Context > context, T * existing_cpp_object) inline
Used when wanting to return an object from a c++ function call back to javascript
Definition at line 277 of file v8_class_wrapper.hpp.
References DEBUG.
     {
         auto isolate = this->isolate;
         if (DEBUG) printf("Wrapping existing c++ object %p in v8 wrapper this: %p isolate %p\n", existing_cpp_object, this, isolate);
         // if there's currently a javascript object wrapping this pointer, return that instead of making a new one
         v8::Local<v8::Object> javascript_object;
         if(this->existing_wrapped_objects.find(existing_cpp_object) != this->existing_wrapped_objects.end()) {
             if (DEBUG) printf("Found existing javascript object for c++ object %p\n", existing_cpp_object);
             javascript_object = v8::Local<v8::Object>::New(isolate, this->existing_wrapped_objects[existing_cpp_object]);
         } else {
             if (DEBUG) printf("Creating new javascript object for c++ object %p\n", existing_cpp_object);
             v8::Isolate::Scope is(isolate);
             v8::Context::Scope cs(context);
             javascript_object = this->constructor_templates[0]->InstanceTemplate()->NewInstance();
             _initialize_new_js_object<BEHAVIOR>(isolate, javascript_object, existing_cpp_object);
             this->existing_wrapped_objects.insert(std::pair<T*, v8::Global<v8::Object>>(existing_cpp_object, v8::Global<v8::Object>(isolate, javascript_object)));
             if (DEBUG) printf("Inserting new object into existing_wrapped_objects hash that is now of size: %d\n", (int)this->existing_wrapped_objects.size());
         }
         return javascript_object;
     }
template<class T> template<typename MEMBER_TYPE > V8ClassWrapper<T>& V8ClassWrapper< T >::add_member (MEMBER_TYPE T::* member, std::string member_name) inline
Adds a getter and setter method for the specified class member add_member(&ClassName::member_name, "javascript_attribute_name");
Definition at line 318 of file v8_class_wrapper.hpp.
     {
         // stop additional constructors from being added
         member_or_method_added = true;
         // typedef MEMBER_TYPE T::*MEMBER_POINTER_TYPE;
         // this lambda is shared between the getter and the setter so it can only do work needed by both
         static auto get_member_reference = std::function<MEMBER_TYPE&(T*)>([member](T * cpp_object)->MEMBER_TYPE&{
             return cpp_object->*member;
         });
         for(auto constructor_template : this->constructor_templates) {
             constructor_template->InstanceTemplate()->SetAccessor(v8::String::NewFromUtf8(isolate,
                 member_name.c_str()),
                 _getter_helper<MEMBER_TYPE>,
                 _setter_helper<MEMBER_TYPE>,
                 v8::External::New(isolate, &get_member_reference));
         }
         return *this;
     }
template<class T> template<class METHOD_TYPE > V8ClassWrapper<T>& V8ClassWrapper< T >::add_method (METHOD_TYPE method, std::string method_name) inline
adds the ability to call the specified class instance method on an object of this type add_method(&ClassName::method_name, "javascript_attribute_name");
Definition at line 347 of file v8_class_wrapper.hpp.
References v8toolkit::bind().
     {
         // stop additional constructors from being added
         member_or_method_added = true;
         // this is leaked if this ever isn't used anymore
         StdFunctionCallbackType * f = new StdFunctionCallbackType([method](const v8::FunctionCallbackInfo<v8::Value>& info)
         {
             // get the behind-the-scenes c++ object
             v8::Local<v8::Object> self = info.Holder();
             v8::Local<v8::External> wrap = v8::Local<v8::External>::Cast(self->GetInternalField(0));
             void* ptr = wrap->Value();
             auto backing_object_pointer = static_cast<T*>(ptr);
             auto bound_method = v8toolkit::bind(*backing_object_pointer, method);
             v8toolkit::ParameterBuilder<0, decltype(bound_method), decltype(bound_method)>()(bound_method, info);
             // CallerQualifierRemover<METHOD_TYPE>()(method, *backing_object_pointer, info);
         });
         auto function_template = v8::FunctionTemplate::New(this->isolate, callback_helper, v8::External::New(this->isolate, f));
         for(auto constructor_template : this->constructor_templates) {
             constructor_template->InstanceTemplate()->Set(v8::String::NewFromUtf8(isolate, method_name.c_str()), function_template);
         }
         return *this;
     }
The documentation for this class was generated from the following file:
v8_class_wrapper.hpp