v8toolkit: v8toolkit::IsolateHelper Class Reference
v8toolkit::IsolateHelper Class Reference
#include <javascript.h>
Public Member Functions
virtual ~IsolateHelper ()
operator v8::Isolate * ()
operator v8::Local< v8::ObjectTemplate > ()
IsolateHelper & add_print (std::function< void(const std::string &)>)
IsolateHelper & add_print ()
void add_assert ()
void add_require (std::vector< std::string > paths=std::vector< std::string >{"./"})
void add_module_list ()
std::shared_ptr< ContextHelper > create_context ()
v8::Isolate * get_isolate ()
v8::Local< v8::ObjectTemplate > get_object_template ()
template<class T , class R = decltype(std::declval<T>()()), decltype(std::declval< T >()(), 1) = 1>
R operator() (T callable)
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr))), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr)), 1) = 1>
R operator() (T callable)
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr), v8::Local<v8::Context>())), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr), v8::Local< v8::Context >()), 1) = 1>
R operator() (T callable)
template<class Callable >
void add_function (std::string name, Callable callable)
template<class Variable >
void expose_variable (std::string name, Variable &variable)
template<class Variable >
void expose_variable_readonly (std::string name, Variable &variable)
void add_variable (const std::string &name, v8::Local< v8::ObjectTemplate > template_to_attach)
template<class T >
auto & wrap_class ()
v8::Local< v8::Value > json (std::string json)
Friends
class PlatformHelper
Detailed Description
Represents a v8::Isolate object. Any changes made here will be reflected in any contexts created after the change was made. An IsolateHleper will remain as long as the user has a shared_ptr to the IsolateHelper itself or a unique_ptr to any ContextHelper created from the IsolateHelper. Can only be created by calling PlatformHelper::create_isolate()
Definition at line 471 of file javascript.h.
Constructor & Destructor Documentation
v8toolkit::IsolateHelper::~IsolateHelper () virtual
Definition at line 220 of file javascript.cpp.
Member Function Documentation
v8toolkit::IsolateHelper::operator v8::Isolate * ()
Implicit cast to v8::Isolate* so an IsolateHelper can be used where a v8::Isolate* would otherwise be required
Definition at line 163 of file javascript.cpp.
v8toolkit::IsolateHelper::operator v8::Local< v8::ObjectTemplate > ()
Implicit cast to Local<ObjectTemplate> for the global object template used to create new contexts
IsolateHelper & v8toolkit::IsolateHelper::add_print (std::function< void(const std::string &)> callback)
Adds print helpers to global object template as defined in v8toolkit::add_print()
Definition at line 173 of file javascript.cpp.
References v8toolkit::add_print(), and get_object_template().
IsolateHelper & v8toolkit::IsolateHelper::add_print ()
Definition at line 181 of file javascript.cpp.
References v8toolkit::add_print(), and get_object_template().
void v8toolkit::IsolateHelper::add_assert ()
Definition at line 234 of file javascript.cpp.
References add_function(), v8toolkit::compare_contents(), and v8toolkit::stringify_value().
void v8toolkit::IsolateHelper::add_require (std::vector< std::string > paths = std::vector<std::string>{"./"})
Adds require() function to javascript as defined in v8toolkit::add_require()
Definition at line 190 of file javascript.cpp.
References v8toolkit::add_require(), and get_object_template().
void v8toolkit::IsolateHelper::add_module_list () inline
Definition at line 523 of file javascript.h.
References v8toolkit::add_module_list().
std::shared_ptr< ContextHelper > v8toolkit::IsolateHelper::create_context ()
Creates a ContextHelper populated by all customizations already applied to this IsolateHelper, but subsequent customizations to the IsolateHelper will not be applied to ContextHelpers already created.
Definition at line 203 of file javascript.cpp.
References get_object_template(), and operator()().
v8::Isolate * v8toolkit::IsolateHelper::get_isolate ()
Returns the isolate associated with this IsolateHelper
Definition at line 197 of file javascript.cpp.
v8::Local< v8::ObjectTemplate > v8toolkit::IsolateHelper::get_object_template ()
Returns the v8::ObjectTemplate used to create contexts from this IsolateHelper
Definition at line 215 of file javascript.cpp.
Referenced by add_function(), add_print(), add_require(), add_variable(), create_context(), expose_variable(), and expose_variable_readonly().
template<class T , class R = decltype(std::declval<T>()()), decltype(std::declval< T >()(), 1) = 1> R v8toolkit::IsolateHelper::operator() (T callable) inline
wraps "callable" in appropriate thread locks, isolate, and handle scopes
Definition at line 550 of file javascript.h.
References v8toolkit::scoped_run().
Referenced by create_context().
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr))), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr)), 1) = 1> R v8toolkit::IsolateHelper::operator() (T callable) inline
wraps "callable" in appropriate thread locks, isolate, and handle scopes Passes the v8::Isolate * to the callable function
Definition at line 562 of file javascript.h.
References v8toolkit::scoped_run().
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr), v8::Local<v8::Context>())), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr), v8::Local< v8::Context >()), 1) = 1> R v8toolkit::IsolateHelper::operator() (T callable) inline
wraps "callable" in appropriate thread locks, isolate, and handle scopes Passes the v8::Isolate * and v8::Local<v8::Context> to the callable function. Throws v8toolkit::InvalidCallException if the isolate is not currently in a context
Definition at line 575 of file javascript.h.
References v8toolkit::scoped_run().
template<class Callable > void v8toolkit::IsolateHelper::add_function (std::string name, Callable callable) inline
Adds the specified callable as <name> in javascript This can be a standard C++ function, a lambda, or anything else that supports being called with operator()
Definition at line 586 of file javascript.h.
References v8toolkit::add_function(), and get_object_template().
Referenced by add_assert().
template<class Variable > void v8toolkit::IsolateHelper::expose_variable (std::string name, Variable & variable) inline
Exposes an existing C++ variable as <name> to javascript
Definition at line 597 of file javascript.h.
References v8toolkit::expose_variable(), and get_object_template().
template<class Variable > void v8toolkit::IsolateHelper::expose_variable_readonly (std::string name, Variable & variable) inline
Definition at line 603 of file javascript.h.
References v8toolkit::expose_variable_readonly(), and get_object_template().
void v8toolkit::IsolateHelper::add_variable (const std::string & name, v8::Local< v8::ObjectTemplate > template_to_attach) inline
Definition at line 608 of file javascript.h.
References v8toolkit::add_variable(), and get_object_template().
template<class T > auto& v8toolkit::IsolateHelper::wrap_class () inline
Returns a V8ClassWrapper object for wrapping C++ classes in this isolate. Classes must be wrapped before contexts using them are created
Definition at line 618 of file javascript.h.
v8::Local<v8::Value> v8toolkit::IsolateHelper::json (std::string json) inline
Returns a value representing the JSON string specified or throws on bad JSON
Definition at line 625 of file javascript.h.
Friends And Related Function Documentation
friend class PlatformHelper friend
Definition at line 472 of file javascript.h.
The documentation for this class was generated from the following files:
javascript.h
javascript.cpp