v8toolkit: v8toolkit::V8ClassWrapper< T > Class Template Reference
v8toolkit::V8ClassWrapper< T > Class Template Reference
#include <v8_class_wrapper.h>
Public Types
typedef std::function< void(const v8::FunctionCallbackInfo< v8::Value > &info)> StdFunctionCallbackType
using AttributeAdder = std::function< void(v8::Local< v8::ObjectTemplate > &)>
Public Member Functions
v8::Local< v8::FunctionTemplate > make_function_template (v8::FunctionCallback callback=nullptr, const v8::Local< v8::Value > &data=v8::Local< v8::Value >())
v8::Local< v8::FunctionTemplate > get_function_template ()
T * get_cpp_object (v8::Local< v8::Object > object)
T * cast (AnyBase *any_base)
void init_instance_object_template (v8::Local< v8::ObjectTemplate > object_template)
void init_prototype_object_template (v8::Local< v8::ObjectTemplate > object_template)
template<class... CompatibleTypes>
std::enable_if_t< static_all_of< std::is_base_of< T, CompatibleTypes >::value... >::value, V8ClassWrapper< T > & > set_compatible_types ()
template<class ParentType >
std::enable_if_t< std::is_base_of< ParentType, T >::value, V8ClassWrapper< T > & > set_parent_type ()
virtual ~V8ClassWrapper ()
template<typename... CONSTRUCTOR_PARAMETER_TYPES>
v8toolkit::V8ClassWrapper< T > & add_constructor (std::string js_constructor_name, v8::Local< v8::ObjectTemplate > parent_template)
template<class BEHAVIOR >
v8::Local< v8::Value > wrap_existing_cpp_object (v8::Local< v8::Context > context, T *existing_cpp_object)
V8ClassWrapper< T > & finalize ()
bool is_finalized ()
template<class MEMBER_TYPE , class MemberClass , std::enable_if_t< std::is_base_of< MemberClass, T >::value, int > = 0>
V8ClassWrapper< T > & add_member (std::string member_name, MEMBER_TYPE MemberClass::*member)
template<class MEMBER_TYPE , class MemberClass , std::enable_if_t< std::is_base_of< MemberClass, T >::value, int > = 0>
V8ClassWrapper< T > & add_member_readonly (std::string member_name, MEMBER_TYPE MemberClass::*member)
template<class R , class... Args>
V8ClassWrapper< T > & add_method (const std::string &method_name, R(T::*method)(Args...) const)
template<class R , class... Args>
V8ClassWrapper< T > & add_method (const std::string &method_name, R(T::*method)(Args...))
template<class Callable >
V8ClassWrapper< T > & add_method (const std::string &method_name, Callable callable)
template<class Method , std::enable_if_t< is_const_member_function< Method >::value &&!std::is_const< T >::value, int > = 0>
void add_method_for_const_type (const std::string &method_name, Method method)
template<class Method , std::enable_if_t<!(is_const_member_function< Method >::value &&!std::is_const< T >::value), int > = 0>
void add_method_for_const_type (const std::string &method_name, Method method)
template<class M >
V8ClassWrapper< T > & _add_method (const std::string &method_name, M method)
Static Public Member Functions
template<class DestructorBehavior >
static void initialize_new_js_object (v8::Isolate *isolate, v8::Local< v8::Object > js_object, T *cpp_object)
static V8ClassWrapper< T > & get_instance (v8::Isolate *isolate)
Public Attributes
std::vector< AttributeAdder > member_adders
std::vector< AttributeAdder > method_adders
Detailed Description
template<class T>
class v8toolkit::V8ClassWrapper< T >
Provides a mechanism for creating javascript-ready objects from an arbitrary C++ class Can provide a JS constructor method or wrap objects created in another c++ function
Definition at line 145 of file v8_class_wrapper.h.
Member Typedef Documentation
template<class T> typedef std::function<void(const v8::FunctionCallbackInfo<v8::Value>& info)> v8toolkit::V8ClassWrapper< T >::StdFunctionCallbackType
Definition at line 520 of file v8_class_wrapper.h.
template<class T> using v8toolkit::V8ClassWrapper< T >::AttributeAdder = std::function<void(v8::Local<v8::ObjectTemplate> &)>
Definition at line 522 of file v8_class_wrapper.h.
Constructor & Destructor Documentation
template<class T> virtual v8toolkit::V8ClassWrapper< T >::~V8ClassWrapper () inline virtual
V8ClassWrapper objects shouldn't be deleted during the normal flow of your program unless the associated isolate is going away forever. Things will break otherwise as no additional objects will be able to be created even though V8 will still present the ability to your javascript (I think)
Definition at line 440 of file v8_class_wrapper.h.
Member Function Documentation
template<class T> template<class DestructorBehavior > static void v8toolkit::V8ClassWrapper< T >::initialize_new_js_object (v8::Isolate * isolate, v8::Local< v8::Object > js_object, T * cpp_object) inline static
Definition at line 263 of file v8_class_wrapper.h.
References v8toolkit::global_set_weak(), and V8_CLASS_WRAPPER_DEBUG.
template<class T> v8::Local<v8::FunctionTemplate> v8toolkit::V8ClassWrapper< T >::make_function_template (v8::FunctionCallback callback = nullptr, const v8::Local< v8::Value > & data = v8::Local<v8::Value>()) inline
Creates a new v8::FunctionTemplate capabale of creating wrapped T objects based on previously added methods and members. TODO: This needs to track all FunctionTemplates ever created so it can try to use them in GetInstanceByPrototypeChain
Definition at line 285 of file v8_class_wrapper.h.
template<class T> v8::Local<v8::FunctionTemplate> v8toolkit::V8ClassWrapper< T >::get_function_template () inline
Returns an existing constructor function template for the class/isolate OR creates one if none exist. This is to keep the number of constructor function templates as small as possible because looking up which one created an object takes linear time based on the number that exist
Definition at line 317 of file v8_class_wrapper.h.
References v8toolkit::make_function_template().
template<class T> T* v8toolkit::V8ClassWrapper< T >::get_cpp_object (v8::Local< v8::Object > object) inline
Definition at line 331 of file v8_class_wrapper.h.
References V8_CLASS_WRAPPER_DEBUG.
template<class T> T* v8toolkit::V8ClassWrapper< T >::cast (AnyBase * any_base) inline
Check to see if an object can be converted to type T, else return nullptr
Definition at line 343 of file v8_class_wrapper.h.
References V8_CLASS_WRAPPER_DEBUG.
template<class T> void v8toolkit::V8ClassWrapper< T >::init_instance_object_template (v8::Local< v8::ObjectTemplate > object_template) inline
Definition at line 361 of file v8_class_wrapper.h.
template<class T> void v8toolkit::V8ClassWrapper< T >::init_prototype_object_template (v8::Local< v8::ObjectTemplate > object_template) inline
Definition at line 368 of file v8_class_wrapper.h.
template<class T> static V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::get_instance (v8::Isolate * isolate) inline static
Returns a "singleton-per-isolate" instance of the V8ClassWrapper for the wrapped class type. For each isolate you need to add constructors/methods/members separately.
Definition at line 379 of file v8_class_wrapper.h.
References V8_CLASS_WRAPPER_DEBUG, and v8toolkit::is_const_member_function< T >::value.
Referenced by v8toolkit::V8ClassWrapper< T >::_add_method(), v8toolkit::JSFactory< Base, JSWrapperClass, TypeList< InternalConstructorParams... >, TypeList< ExternalConstructorParams... > >::add_subclass_function(), v8toolkit::JSFactory< Base, JSWrapperClass, TypeList< InternalConstructorParams... >, TypeList< ExternalConstructorParams... > >::operator()(), v8toolkit::CastToJS< T >::operator()(), v8toolkit::CastToJS< T * >::operator()(), v8toolkit::V8ClassWrapper< T >::set_parent_type(), v8toolkit::Isolate::wrap_class(), and v8toolkit::Context::wrap_object().
template<class T> template<class... CompatibleTypes> std::enable_if_t<static_all_of<std::is_base_of<T,CompatibleTypes>::value...>::value, V8ClassWrapper<T>&> v8toolkit::V8ClassWrapper< T >::set_compatible_types () inline
Species other types that can be substituted for T when calling a function expecting T but T is not being passsed. Only available for classes derived from T. T is always compatible and should not be specified here. Not calling this means that only T objects will be accepted for things that want a T. There is no automatic determination of inherited types by this library because I cannot figure out how. It's VERY important that any type marked as having this type as a parent be marked as being a compatible type.
Definition at line 407 of file v8_class_wrapper.h.
template<class T> template<class ParentType > std::enable_if_t<std::is_base_of<ParentType, T>::value, V8ClassWrapper<T>&> v8toolkit::V8ClassWrapper< T >::set_parent_type () inline
This wrapped class will inherit all the methods from the parent type (and its parent...)
It is VERY important that the type being marked as the parent type has this type set with set_compatible_types<>()
Definition at line 423 of file v8_class_wrapper.h.
References v8toolkit::V8ClassWrapper< T >::get_instance(), and v8toolkit::scoped_run().
template<class T> template<typename... CONSTRUCTOR_PARAMETER_TYPES> v8toolkit::V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::add_constructor (std::string js_constructor_name, v8::Local< v8::ObjectTemplate > parent_template) inline
Creates a javascript method with the specified name inside parent_template which, when called with the "new" keyword, will return a new object of this type.
Definition at line 453 of file v8_class_wrapper.h.
References v8toolkit::make_function_template().
template<class T> template<class BEHAVIOR > v8::Local<v8::Value> v8toolkit::V8ClassWrapper< T >::wrap_existing_cpp_object (v8::Local< v8::Context > context, T * existing_cpp_object) inline
Used when wanting to return an object from a c++ function call back to javascript, or in conjunction with add_variable to give a javascript name to an existing c++ object
add_variable(context, context->GetGlobal(), "js_name", class_wrapper.wrap_existing_cpp_object(context, some_c++_object));
Definition at line 478 of file v8_class_wrapper.h.
References V8_CLASS_WRAPPER_DEBUG.
template<class T> V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::finalize () inline
Function to force API user to declare that all members/methods have been added before any objects of the wrapped type can be created to make sure everything stays consistent Must be called before adding any constructors or using wrap_existing_object()
Definition at line 530 of file v8_class_wrapper.h.
References v8toolkit::V8ClassWrapper< T >::finalize().
Referenced by v8toolkit::V8ClassWrapper< T >::finalize().
template<class T> bool v8toolkit::V8ClassWrapper< T >::is_finalized () inline
returns whether finalize() has been called on this type for this isolate
Definition at line 545 of file v8_class_wrapper.h.
template<class T> template<class MEMBER_TYPE , class MemberClass , std::enable_if_t< std::is_base_of< MemberClass, T >::value, int > = 0> V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::add_member (std::string member_name, MEMBER_TYPE MemberClass::* member) inline
Adds a getter and setter method for the specified class member add_member(&ClassName::member_name, "javascript_attribute_name");
Definition at line 568 of file v8_class_wrapper.h.
References v8toolkit::V8ClassWrapper< T >::add_member_readonly().
template<class T> template<class MEMBER_TYPE , class MemberClass , std::enable_if_t< std::is_base_of< MemberClass, T >::value, int > = 0> V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::add_member_readonly (std::string member_name, MEMBER_TYPE MemberClass::* member) inline
Definition at line 594 of file v8_class_wrapper.h.
References v8toolkit::V8ClassWrapper< T >::add_member_readonly().
Referenced by v8toolkit::V8ClassWrapper< T >::add_member(), and v8toolkit::V8ClassWrapper< T >::add_member_readonly().
template<class T> template<class R , class... Args> V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::add_method (const std::string & method_name, R(T::*)(Args...) const method) inline
Definition at line 624 of file v8_class_wrapper.h.
Referenced by v8toolkit::V8ClassWrapper< T >::add_method_for_const_type().
template<class T> template<class R , class... Args> V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::add_method (const std::string & method_name, R(T::*)(Args...) method) inline
Adds the ability to call the specified class instance method on an object of this type
Definition at line 633 of file v8_class_wrapper.h.
template<class T> template<class Callable > V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::add_method (const std::string & method_name, Callable callable) inline
Adds a method to the javascript object that doesn't directly call into an actual method in the wrapped type.
Definition at line 643 of file v8_class_wrapper.h.
References v8toolkit::make_function_template().
template<class T> template<class Method , std::enable_if_t< is_const_member_function< Method >::value &&!std::is_const< T >::value, int > = 0> void v8toolkit::V8ClassWrapper< T >::add_method_for_const_type (const std::string & method_name, Method method) inline
Definition at line 657 of file v8_class_wrapper.h.
References v8toolkit::V8ClassWrapper< T >::add_method().
template<class T> template<class Method , std::enable_if_t<!(is_const_member_function< Method >::value &&!std::is_const< T >::value), int > = 0> void v8toolkit::V8ClassWrapper< T >::add_method_for_const_type (const std::string & method_name, Method method) inline
Definition at line 664 of file v8_class_wrapper.h.
template<class T> template<class M > V8ClassWrapper<T>& v8toolkit::V8ClassWrapper< T >::_add_method (const std::string & method_name, M method) inline
Definition at line 673 of file v8_class_wrapper.h.
References v8toolkit::bind(), v8toolkit::V8ClassWrapper< T >::get_instance(), v8toolkit::stringify_value(), and V8_CLASS_WRAPPER_DEBUG.
Member Data Documentation
template<class T> std::vector<AttributeAdder> v8toolkit::V8ClassWrapper< T >::member_adders
Definition at line 523 of file v8_class_wrapper.h.
template<class T> std::vector<AttributeAdder> v8toolkit::V8ClassWrapper< T >::method_adders
Definition at line 666 of file v8_class_wrapper.h.
The documentation for this class was generated from the following file:
include/v8_class_wrapper.h