v8toolkit: v8toolkit::PlatformHelper Class Reference
v8toolkit::PlatformHelper Class Reference
#include <javascript.h>
Static Public Member Functions
static void init (char *path_to_bin_files)
static void init (int argc, char **argv)
static void cleanup ()
static std::shared_ptr< IsolateHelper > create_isolate ()
Detailed Description
A singleton responsible for initializing the v8 platform and creating isolate helpers.
Definition at line 592 of file javascript.h.
Member Function Documentation
static void v8toolkit::PlatformHelper::init (char * path_to_bin_files) static
Initializes the v8 platform with default values and tells v8 to look for its .bin files in the given directory (often argv[0])
Referenced by main().
void v8toolkit::PlatformHelper::init (int argc, char ** argv) static
Parses argv for v8-specific options, applies them, and removes them from argv and adjusts argc accordingly. Looks in argv[0] for the v8 .bin files
Definition at line 260 of file javascript.cpp.
References v8toolkit::process_v8_flags().
void v8toolkit::PlatformHelper::cleanup () static
Shuts down V8. Any subsequent V8 usage is probably undefined, so make sure everything is done before you call this.
Definition at line 283 of file javascript.cpp.
std::shared_ptr< IsolateHelper > v8toolkit::PlatformHelper::create_isolate () static
Creates a new IsolateHelper wrapping a new v8::Isolate instance. Each isolate is completely separate from all the others and each isolate can be used simultaneously across threads (but only 1 thread per isolate at a time) An IsolateHelper will remain as long as the caller has a shared_ptr to the IsolateHelper or any ContextHelpers created from the IsolateHelper still exist. Once neither of those things is the case, the IsolateHelper will be automatically destroyed. If any threads are still running when this happens, the results are undefined. TODO: Can active threads maintain links to their ContextHelpers to stop this from happening?
Definition at line 293 of file javascript.cpp.
Referenced by main(), run_comparison_tests(), run_tests(), run_type_conversion_test(), test_asserts(), test_casts(), and test_lifetimes().
The documentation for this class was generated from the following files:
javascript.h
javascript.cpp