v8toolkit: v8toolkit::ArrayBufferAllocator Class Reference
v8toolkit::ArrayBufferAllocator Class Reference
#include <v8toolkit.h>
Public Member Functions
virtual void * Allocate (size_t length) override
virtual void * AllocateUninitialized (size_t length) override
virtual void Free (void *data, size_t) override
Detailed Description
Example allocator code from V8 Docs
Definition at line 1136 of file v8toolkit.h.
Member Function Documentation
virtual void* v8toolkit::ArrayBufferAllocator::Allocate (size_t length) inline override virtual
Definition at line 1138 of file v8toolkit.h.
virtual void* v8toolkit::ArrayBufferAllocator::AllocateUninitialized (size_t length) inline override virtual
Definition at line 1142 of file v8toolkit.h.
virtual void v8toolkit::ArrayBufferAllocator::Free (void * data, size_t) inline override virtual
Definition at line 1143 of file v8toolkit.h.
References v8toolkit::add_module_list(), v8toolkit::add_require(), v8toolkit::delete_require_cache_for_isolate(), v8toolkit::dump_prototypes(), v8toolkit::get_file_contents(), v8toolkit::get_interesting_properties(), v8toolkit::require(), v8toolkit::require_directory(), and v8toolkit::run_script().
The documentation for this class was generated from the following file:
include/v8toolkit.h