v8helper: v8toolkit::ContextHelper Class Reference
v8toolkit::ContextHelper Class Reference
#include <javascript.h>
Classes
class CompilationError
class ExecutionError
Public Member Functions
virtual ~ContextHelper ()
operator v8::Isolate * ()
operator v8::Local< v8::Context > ()
operator v8::Global< v8::Context > ()
v8::Local< v8::Context > get_context ()
v8::Isolate * get_isolate ()
std::shared_ptr< IsolateHelper > get_isolate_helper ()
v8::Global< v8::Script > compile (const std::string)
v8::Global< v8::Script > compile (const v8::Local< v8::String > script)
v8::Global< v8::Script > compile_from_file (const std::string)
v8::Global< v8::Value > run (const v8::Global< v8::Script > &script)
v8::Global< v8::Value > run (const std::string)
v8::Global< v8::Value > run (const v8::Local< v8::Value > script)
std::future< v8::Global< v8::Value > > run_async (const v8::Global< v8::Script > &script, std::launch launch_policy=std::launch::async|std::launch::deferred)
std::future< v8::Global< v8::Value > > run_async (const std::string, std::launch launch_policy=std::launch::async|std::launch::deferred)
std::future< v8::Global< v8::Value > > run_async (const v8::Local< v8::Value > script, std::launch launch_policy=std::launch::async|std::launch::deferred)
std::thread run_thread (const v8::Global< v8::Script > &script)
std::thread run_thread (const std::string)
std::thread run_thread (const v8::Local< v8::Value > script)
void run_detached (const v8::Global< v8::Script > &script)
void run_detached (const std::string)
void run_detached (const v8::Local< v8::Value > script)
template<class T , class R = decltype(std::declval<T>()()), decltype(std::declval< T >()(), 1) = 1>
R operator() (T callable)
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr))), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr)), 1) = 1>
R operator() (T callable)
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr), v8::Local<v8::Context>())), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr), v8::Local< v8::Context >()), 1) = 1>
R operator() (T callable)
template<class Function >
void add_function (std::string name, Function function)
template<class Variable >
void expose_variable (std::string name, Variable &variable)
template<class T >
auto wrap_object (T *object)
Friends
class IsolateHelper
Detailed Description
Wrapper around a v8::Cnotext object with a link back to its associated isolate This object can be used wherever a v8::Isolate * or a Local or Global v8::Context is wanted. Can only be created via IsolateHelper::create_context()
Definition at line 19 of file javascript.h.
Constructor & Destructor Documentation
v8toolkit::ContextHelper::~ContextHelper () virtual
Definition at line 33 of file javascript.cpp.
Member Function Documentation
v8toolkit::ContextHelper::operator v8::Isolate * () inline
Implicit cast to v8::Isolate *
Definition at line 77 of file javascript.h.
v8toolkit::ContextHelper::operator v8::Local< v8::Context > () inline
Implicit cast to v8::Local<v8::Context>
Definition at line 82 of file javascript.h.
v8toolkit::ContextHelper::operator v8::Global< v8::Context > () inline
Implicit cast to v8::Global<v8::Context>
Definition at line 87 of file javascript.h.
v8::Local< v8::Context > v8toolkit::ContextHelper::get_context ()
Returns a Local copy of the associated v8::Context
Definition at line 17 of file javascript.cpp.
Referenced by add_function(), and expose_variable().
v8::Isolate * v8toolkit::ContextHelper::get_isolate ()
Returns the v8::Isolate * this context is associated with
Definition at line 21 of file javascript.cpp.
std::shared_ptr< IsolateHelper > v8toolkit::ContextHelper::get_isolate_helper ()
Returns the IsolateHelper wrapping the isolate this context is associated with
Definition at line 26 of file javascript.cpp.
v8::Global< v8::Script > v8toolkit::ContextHelper::compile (const std::string javascript_source)
Compiles the contents of the passed in string as javascripts Throws v8toolkit::CompilationError on compilation error
Definition at line 44 of file javascript.cpp.
References v8toolkit::scoped_run().
Referenced by compile_from_file(), and run().
v8::Global<v8::Script> v8toolkit::ContextHelper::compile (const v8::Local< v8::String > script)
Compiles the contents of the passed in v8::String as javascript Throws v8toolkit::CompilationError on compilation error
v8::Global< v8::Script > v8toolkit::ContextHelper::compile_from_file (const std::string filename)
Loads the contents of the given file as javascript Throws v8toolkit::CompilationError on compilation error TODO: what if the file can't be opened?
Definition at line 39 of file javascript.cpp.
References compile(), and v8toolkit::get_file_contents().
v8::Global< v8::Value > v8toolkit::ContextHelper::run (const v8::Global< v8::Script > & script)
Runs the previously compiled v8::Script. Throws v8toolkit::ExecutionError on execution error
Definition at line 67 of file javascript.cpp.
References v8toolkit::scoped_run().
Referenced by run(), run_async(), run_detached(), and run_thread().
v8::Global< v8::Value > v8toolkit::ContextHelper::run (const std::string code)
Compiles and runs the contents ot the passed in string Throws v8toolkit::CompilationError on compilation error Throws v8toolkit::ExecutionError on execution error
Definition at line 95 of file javascript.cpp.
References compile(), and run().
v8::Global< v8::Value > v8toolkit::ContextHelper::run (const v8::Local< v8::Value > script)
Definition at line 103 of file javascript.cpp.
References run().
std::future< v8::Global< v8::Value > > v8toolkit::ContextHelper::run_async (const v8::Global< v8::Script > & script, std::launch launch_policy = std::launch::async | std::launch::deferred)
Executes the previously compiled v8::script in a std::async and returns the std::future associated with it. While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in execution?
Definition at line 108 of file javascript.cpp.
References run().
std::future< v8::Global< v8::Value > > v8toolkit::ContextHelper::run_async (const std::string code, std::launch launch_policy = std::launch::async | std::launch::deferred)
Compiles and runs the contents of the passed in string in a std::async and returns the std::future associated with it. While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in compilation? TODO: what happens if there are errors in execution?
Definition at line 117 of file javascript.cpp.
References run().
std::future< v8::Global< v8::Value > > v8toolkit::ContextHelper::run_async (const v8::Local< v8::Value > script, std::launch launch_policy = std::launch::async | std::launch::deferred)
Executes the previously compiled v8::script in a std::async and returns the std::future associated with it. While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in execution?
Definition at line 131 of file javascript.cpp.
References run().
std::thread v8toolkit::ContextHelper::run_thread (const v8::Global< v8::Script > & script)
Executes the previously compiled v8::script in a std::thread and returns the std::thread associated with it. It must either be joined or detached before the std::thread object is destroyed While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in execution?
Definition at line 169 of file javascript.cpp.
References run().
std::thread v8toolkit::ContextHelper::run_thread (const std::string code)
Compiles and runs the contents of the passed in string in a in a std::thread and returns the std::thread associated with it. It must either be joined or detached before the std::thread object is destroyed While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in compilation? TODO: what happens if there are errors in execution?
Definition at line 178 of file javascript.cpp.
References run().
std::thread v8toolkit::ContextHelper::run_thread (const v8::Local< v8::Value > script)
Executes the previously compiled v8::script in a std::thread and returns the std::thread associated with it. It must either be joined or detached before the std::thread object is destroyed While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in execution?
Definition at line 188 of file javascript.cpp.
References run().
void v8toolkit::ContextHelper::run_detached (const v8::Global< v8::Script > & script)
Executes the previously compiled v8::script in a detached std::thread. While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in execution?
Definition at line 141 of file javascript.cpp.
References run().
void v8toolkit::ContextHelper::run_detached (const std::string code)
Compiles and runs the contents of the passed in string in a detached std::thread. While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in compilation? TODO: what happens if there are errors in execution?
Definition at line 150 of file javascript.cpp.
References run().
void v8toolkit::ContextHelper::run_detached (const v8::Local< v8::Value > script)
Executes the previously compiled v8::script in a detached std::thread. While any number of threaded calls can be made, only one context per isolate can be actively running at a time. Additional calls will be queued but will block until they can acquire the v8::Locker object for their isolate TODO: what happens if there are errors in execution?
Definition at line 160 of file javascript.cpp.
References run().
template<class T , class R = decltype(std::declval<T>()()), decltype(std::declval< T >()(), 1) = 1> R v8toolkit::ContextHelper::operator() (T callable) inline
Calls v8toolkit::scoped_run with the assciated isolate and context data
Definition at line 254 of file javascript.h.
References v8toolkit::scoped_run().
Referenced by add_function().
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr))), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr)), 1) = 1> R v8toolkit::ContextHelper::operator() (T callable) inline
Calls v8toolkit::scoped_run with the assciated isolate and context data Passes the v8::Isolate * into the callback
Definition at line 268 of file javascript.h.
References v8toolkit::scoped_run().
template<class T , class R = decltype(std::declval<T>()(static_cast<v8::Isolate*>(nullptr), v8::Local<v8::Context>())), decltype(std::declval< T >()(static_cast< v8::Isolate * >(nullptr), v8::Local< v8::Context >()), 1) = 1> R v8toolkit::ContextHelper::operator() (T callable) inline
Calls v8toolkit::scoped_run with the assciated isolate and context data Passes the v8::Isolate * and context into the callback
Definition at line 282 of file javascript.h.
References v8toolkit::scoped_run().
template<class Function > void v8toolkit::ContextHelper::add_function (std::string name, Function function) inline
Adds a function to this context only See: v8toolkit::add_function
Definition at line 294 of file javascript.h.
References v8toolkit::add_function(), get_context(), and operator()().
template<class Variable > void v8toolkit::ContextHelper::expose_variable (std::string name, Variable & variable) inline
Exposes a C++ variable to this context only see: v8toolkit::expose_variable
Definition at line 306 of file javascript.h.
References v8toolkit::expose_variable(), and get_context().
template<class T > auto v8toolkit::ContextHelper::wrap_object (T * object)
Returns a javascript object representation of the given c++ object see: votoolkit::V8ClassWrapper
Friends And Related Function Documentation
friend class IsolateHelper friend
Definition at line 20 of file javascript.h.
The documentation for this class was generated from the following files:
javascript.h
javascript.cpp