v8helper: javascript_sample.cpp File Reference
javascript_sample.cpp File Reference
#include <stdio.h>
#include "javascript.h"
Classes
class Foo
Functions
Foo get_foo ()
auto run_tests ()
int main (int argc, char **argv)
Variables
int x = 1
int y = 2
int y2 = 3
Class Documentation
class Foo
Definition at line 7 of file javascript_sample.cpp.
Function Documentation
Foo get_foo ()
Definition at line 12 of file javascript_sample.cpp.
 {printf("in get_foo\n");return Foo();}
auto run_tests ()
Definition at line 18 of file javascript_sample.cpp.
References v8toolkit::PlatformHelper::create_isolate(), v8toolkit::ContextHelper::ExecutionError::what(), x, y, and y2.
Referenced by main().
 {
     auto ih1 = PlatformHelper::create_isolate();
     auto ih2 = PlatformHelper::create_isolate();
     return (*ih1)([&](){
         ih1->add_print();
         // expose global variable x as "x" in all contexts created from this isolate
         ih1->expose_variable("x", x);
         ih1->add_function("return_hi", [](){return "hi";});
         auto c = ih1->create_context();
         auto c2 = ih1->create_context();
         c->run("println(\"x is: \", x);");
         c->run("println('return_hi():',return_hi());");
         ih1->expose_variable("y", y);
         ih1->add_function("return_bye", [](){return "bye";});
         try {
             c->run("println(y)");
         } catch(v8toolkit::ContextHelper::ExecutionError & e) {
             printf("Expected failure, as 'y' is not present in contexts created before y was added to isolate: %s\n", e.what());
         }
         try {
             c->run("println(return_bye())");
         } catch(v8toolkit::ContextHelper::ExecutionError & e) {
             printf("Expected failure, as 'return_bye' is not present in contexts created before return_bye was added to isolate: %s\n", e.what());
         }
         auto c3 = ih1->create_context();
         printf("But they do exist on c3, as it was created after they were added to the isolate helper\n");
         c3->run("println('y is: ', y)");
         c3->run("println('return_bye(): ', return_bye())");
         (*c)([&](){
             // however, you can add them to an individual context
             c->expose_variable("y", y2);
             c->add_function("return_bye", [](){return "goodbye";});
         });
         printf("Now slightly different versions of 'y' and 'return_bye' have been added to c\n");
         c->run("println('y is:', y)");
         c->run("println('return_bye():', return_bye())");
         printf("but they're still not on c2, which was made at the same time as c\n");
         try {
             c2->run("println(y)");
         } catch(v8toolkit::ContextHelper::ExecutionError & e) {
             printf("Expected failure, as 'y' is not present in contexts created before y was added to isolate: %s\n", e.what());
         }
         try {
             c2->run("println(return_bye())");
         } catch(v8toolkit::ContextHelper::ExecutionError & e) {
             printf("Expected failure, as 'return_bye' is not present in contexts created before return_bye was added to isolate: %s\n", e.what());
         }
         // returning context to demonstrate how having a context alive keeps an IsolateHelper alive even though the
         //   direct shared_ptr to it is destroyed at the end of this function
         return c;
     });
 }
int main (int argc, char ** argv)
Definition at line 86 of file javascript_sample.cpp.
References v8toolkit::PlatformHelper::init(), and run_tests().
{
     PlatformHelper::init(argc, argv);
     auto context = run_tests();
     printf("after run_tests, one isolate helper was destroyed, since it made no contexts\n");
     printf("Program ending, so last context and the isolate that made it will now be destroyed\n");
 }
Variable Documentation
int x = 1
Definition at line 14 of file javascript_sample.cpp.
Referenced by run_tests().
int y = 2
Definition at line 15 of file javascript_sample.cpp.
Referenced by run_tests().
int y2 = 3
Definition at line 16 of file javascript_sample.cpp.
Referenced by run_tests().