v8toolkit: v8toolkit::CastToNative< T, class > Struct Template Reference
v8toolkit::CastToNative< T, class > Struct Template Reference
#include <casts.hpp>
Public Member Functions
T & operator() (v8::Isolate *isolate, v8::Local< v8::Value > value)
Detailed Description
template<typename T, class>
struct v8toolkit::CastToNative< T, class >
Casts from a boxed Javascript type to a native type
Definition at line 115 of file casts.hpp.
Member Function Documentation
template<typename T, class > std::function< Return(Params...)> v8toolkit::CastToNative< Return, Params >::operator() (v8::Isolate * isolate, v8::Local< v8::Value > value) inline
Definition at line 1453 of file v8_class_wrapper.h.
Referenced by CastToJS< eastl::vector< T, Rest... > >::operator()(), CastToJS< std::pair< T1, T2 > >::operator()(), CastToJS< std::vector< T, Rest... > >::operator()(), CastToJS< std::list< U, Rest... > >::operator()(), CastToJS< std::map< A, B, Rest... > >::operator()(), CastToJS< std::multimap< A, B, Rest... > >::operator()(), CastToJS< std::unordered_map< A, B, Rest... > >::operator()(), CastToJS< std::deque< T, Rest... > >::operator()(), and CastToJS< std::array< T, N > >::operator()().
The documentation for this struct was generated from the following files:
include/casts.hpp
include/v8_class_wrapper.h
include/casts_impl.hpp