v8helper: v8_toolbox.hpp File Reference
v8_toolbox.hpp File Reference
#include <iostream>
#include <assert.h>
#include "include/libplatform/libplatform.h"
#include "include/v8.h"
#include "casts.hpp"
Classes
struct CallCallable< T >
struct CallCallable< std::function< R(PARAMETERS...)> >
struct CallCallable< std::function< void(PARAMETERS...)> >
struct ParameterBuilder< depth, T, U >
struct ParameterBuilder< depth, FUNCTION_TYPE, std::function< RET(HEAD, TAIL...)> >
struct ParameterBuilder< depth, T, std::function< void(const v8::FunctionCallbackInfo< v8::Value > &)> >
struct Bind< T, U >
struct Bind< CLASS_TYPE, R(CLASS_TYPE::*)(Args...)>
class ArrayBufferAllocator
Functions
void process_v8_flags (int &argc, char **argv)
void expose_gc ()
template<class R , class... Args>
v8::Local< v8::FunctionTemplate > make_function_template (v8::Isolate *isolate, std::function< R(Args...)> f)
template<class R , class CLASS , class... Args>
std::function< R(Args...)> make_std_function_from_callable (R(CLASS::*f)(Args...) const, CLASS callable)
template<class T >
v8::Local< v8::FunctionTemplate > make_function_template (v8::Isolate *isolate, T callable)
template<class R , class... Args>
v8::Local< v8::FunctionTemplate > make_function_template (v8::Isolate *isolate, R(*f)(Args...))
template<class R , class... Args>
void add_function (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > &object_template, const char *name, std::function< R(Args...)> function)
template<class T >
void add_function (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > &object_template, const char *name, T callable)
template<class R , class... Args>
void add_function (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > &object_template, const char *name, R(*function)(Args...))
void add_function (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > &object_template, const char *name, void(*function)(const v8::FunctionCallbackInfo< v8::Value > &))
template<class VARIABLE_TYPE >
void _variable_getter (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Value > &info)
template<class VARIABLE_TYPE >
void _variable_setter (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< void > &info)
template<class VARIABLE_TYPE >
void expose_variable (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > &object_template, const char *name, VARIABLE_TYPE &variable)
template<class VARIABLE_TYPE >
void expose_variable_readonly (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > &object_template, const char *name, VARIABLE_TYPE &variable)
template<class CALLBACK_FUNCTION >
void global_set_weak (v8::Isolate *isolate, v8::Local< v8::Object > &javascript_object, CALLBACK_FUNCTION function)
void _print_helper (const v8::FunctionCallbackInfo< v8::Value > &args, bool append_newline)
void printobj (const v8::FunctionCallbackInfo< v8::Value > &args)
void add_print (v8::Isolate *isolate, v8::Local< v8::ObjectTemplate > global_template)
template<class CLASS , class R , class... Args>
std::function< R(Args...)> bind (CLASS &object, R(CLASS::*method)(Args...))
template<class CALLABLE >
void scoped_run (v8::Isolate *isolate, CALLABLE callable)
template<class CALLABLE >
void scoped_run (v8::Isolate *isolate, v8::Local< v8::Context > context, CALLABLE callable)
Class Documentation
struct CallCallable
template<class T>
struct CallCallable< T >
Functor to call a given std::function and, if it has a non-null return value, return its value back to javascript
Definition at line 42 of file v8_toolbox.hpp.
struct ParameterBuilder
template<int depth, typename T, typename U>
struct ParameterBuilder< depth, T, U >
Class for turning a function parameter list into a parameter pack useful for actually calling the function
Definition at line 70 of file v8_toolbox.hpp.
struct Bind
template<class T, class U>
struct Bind< T, U >
Accepts an object and a method on that object to be called later via its operator() Does not require knowledge of how many parameters the method takes or any placeholder arguments Can be wrapped with a std::function
Definition at line 346 of file v8_toolbox.hpp.
Function Documentation
void process_v8_flags (int & argc, char ** argv)
Library of standalone helper functions for using V8. Can be used independently of V8ClassWrapper parses v8-related flags and removes them, adjusting argc as needed
Definition at line 20 of file v8_toolbox.hpp.
 {
     v8::V8::SetFlagsFromCommandLine(&argc, argv, true);
 }
void expose_gc ()
exposes the garbage collector to javascript same as passing –expose-gc as a command-line flag To encourage javascript garbage collection run from c++, use: while(!v8::Isolate::IdleNotificationDeadline([time])) {};
Definition at line 32 of file v8_toolbox.hpp.
 {
     static const char * EXPOSE_GC = "--expose-gc";
     v8::V8::SetFlagsFromString(EXPOSE_GC, strlen(EXPOSE_GC));
 }
template<class R , class... Args> v8::Local<v8::FunctionTemplate> make_function_template (v8::Isolate * isolate, std::function< R(Args...)> f)
Creates a function template from a std::function
Definition at line 133 of file v8_toolbox.hpp.
Referenced by add_function(), and make_function_template().
 {
     auto copy = new std::function<R(Args...)>(f);
     return v8::FunctionTemplate::New(isolate, [](const v8::FunctionCallbackInfo<v8::Value>& args) {
         auto callable = *(std::function<R(Args...)>*)v8::External::Cast(*(args.Data()))->Value();
         ParameterBuilder<0, std::function<R(Args...)>, std::function<R(Args...)>>()(callable, args);
     }, v8::External::New(isolate, (void*)copy));
 }
template<class R , class CLASS , class... Args> std::function<R(Args...)> make_std_function_from_callable (R(CLASS::*)(Args...) const f, CLASS callable)
Definition at line 145 of file v8_toolbox.hpp.
Referenced by make_function_template().
 {
     return std::function<R(Args...)>(callable);
 }
template<class T > v8::Local<v8::FunctionTemplate> make_function_template (v8::Isolate * isolate, T callable)
Definition at line 153 of file v8_toolbox.hpp.
References make_function_template(), and make_std_function_from_callable().
 {
     return make_function_template(isolate, make_std_function_from_callable(&T::operator(), callable));
 }
template<class R , class... Args> v8::Local<v8::FunctionTemplate> make_function_template (v8::Isolate * isolate, R(*)(Args...) f)
Creates a function template from a c-style function pointer
Definition at line 164 of file v8_toolbox.hpp.
References make_function_template().
 {
     return make_function_template(isolate, std::function<R(Args...)>(f));
 }
template<class R , class... Args> void add_function (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > & object_template, const char * name, std::function< R(Args...)> function)
Helper to both create a function template and bind it with the specified name to the specified object template
Definition at line 174 of file v8_toolbox.hpp.
References make_function_template().
Referenced by add_print().
{
     object_template->Set(isolate, name, make_function_template(isolate, function));
 }
template<class T > void add_function (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > & object_template, const char * name, T callable)
Definition at line 179 of file v8_toolbox.hpp.
References make_function_template().
{
     object_template->Set(isolate, name, make_function_template(isolate, callable));
 }
template<class R , class... Args> void add_function (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > & object_template, const char * name, R(*)(Args...) function)
Definition at line 184 of file v8_toolbox.hpp.
References make_function_template().
{
     object_template->Set(isolate, name, make_function_template(isolate, function));
 }
void add_function (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > & object_template, const char * name, void(*)(const v8::FunctionCallbackInfo< v8::Value > &) function)
add a function that directly handles the v8 callback data explicit function typing needed to coerce non-capturing lambdas into c-style function pointers
Definition at line 192 of file v8_toolbox.hpp.
References make_function_template().
{
     object_template->Set(isolate, name, make_function_template(isolate, function));
 }
template<class VARIABLE_TYPE > void _variable_getter (v8::Local< v8::String > property, const v8::PropertyCallbackInfo< v8::Value > & info)
Definition at line 199 of file v8_toolbox.hpp.
 {
     auto isolate = info.GetIsolate();
     info.GetReturnValue().Set(CastToJS<VARIABLE_TYPE>()(isolate, *(VARIABLE_TYPE*)v8::External::Cast(*(info.Data()))->Value()));
 }
template<class VARIABLE_TYPE > void _variable_setter (v8::Local< v8::String > property, v8::Local< v8::Value > value, const v8::PropertyCallbackInfo< void > & info)
Definition at line 207 of file v8_toolbox.hpp.
 {
     auto isolate = info.GetIsolate();
     *(VARIABLE_TYPE*)v8::External::Cast(*(info.Data()))->Value() = CastToNative<VARIABLE_TYPE>()(value);
 }
template<class VARIABLE_TYPE > void expose_variable (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > & object_template, const char * name, VARIABLE_TYPE & variable)
Exposes the specified variable to javascript as the specified name in the given object template (usually the global template). Allows reads and writes to the variable
Definition at line 219 of file v8_toolbox.hpp.
{
     object_template->SetAccessor(v8::String::NewFromUtf8(isolate, name), _variable_getter<VARIABLE_TYPE>, _variable_setter<VARIABLE_TYPE>, v8::External::New(isolate, &variable));
 }
template<class VARIABLE_TYPE > void expose_variable_readonly (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > & object_template, const char * name, VARIABLE_TYPE & variable)
Exposes the specified variable to javascript as the specified name in the given object template (usually the global template). Allows reads to the variable. Writes are ignored.
Definition at line 227 of file v8_toolbox.hpp.
{
     object_template->SetAccessor(v8::String::NewFromUtf8(isolate, name), _variable_getter<VARIABLE_TYPE>, 0, v8::External::New(isolate, &variable));
 }
template<class CALLBACK_FUNCTION > void global_set_weak (v8::Isolate * isolate, v8::Local< v8::Object > & javascript_object, CALLBACK_FUNCTION function)
Takes a local and creates a weak global reference callback for it
Definition at line 236 of file v8_toolbox.hpp.
 {
     struct SetWeakCallbackData{
         SetWeakCallbackData(CALLBACK_FUNCTION function, v8::Isolate * isolate, v8::Local<v8::Object> & javascript_object) :
             function(function) {
                 this->global.Reset(isolate, javascript_object);
         }
         CALLBACK_FUNCTION function;
         v8::Global<v8::Object> global;
     };
     auto callback_data = new SetWeakCallbackData(function, isolate, javascript_object);
     callback_data->global.template SetWeak<SetWeakCallbackData>(callback_data,
         [](const v8::WeakCallbackData<v8::Object, SetWeakCallbackData> & data){
             SetWeakCallbackData * callback_data = data.GetParameter();
             callback_data->function();
             callback_data->global.Reset();
             delete callback_data;
         });
 }
void _print_helper (const v8::FunctionCallbackInfo< v8::Value > & args, bool append_newline)
Definition at line 290 of file v8_toolbox.hpp.
Referenced by add_print().
{
     if (args.Length() > 0) {
         for (int i = 0; i < args.Length(); i++) {
             if (i > 0) {
                 std::cout << " ";
             }
             std::cout << *v8::String::Utf8Value(args[i]);
         }
     }
     if (append_newline) {
         std::cout << std::endl;
     }
 }
void printobj (const v8::FunctionCallbackInfo< v8::Value > & args)
Definition at line 308 of file v8_toolbox.hpp.
Referenced by add_print().
{
     for (int i = 0; i < args.Length(); i++) {
         auto object = v8::Object::Cast(*args[i]);
         if(object->InternalFieldCount() > 0) {
             v8::Local<v8::External> wrap = v8::Local<v8::External>::Cast(object->GetInternalField(0));
             printf(">>> Object %p: %s\n", wrap->Value(), *v8::String::Utf8Value(args[i]));
         } else {
             printf(">>> Object does not appear to be a wrapped c++ class (no internal fields): %s\n", *v8::String::Utf8Value(args[i]));
         }
     }
 }
void add_print (v8::Isolate * isolate, v8::Local< v8::ObjectTemplate > global_template)
Definition at line 327 of file v8_toolbox.hpp.
References _print_helper(), add_function(), and printobj().
 {
 #ifdef USE_BOOST
     add_function(isolate, global_template, "printf",    [](const v8::FunctionCallbackInfo<v8::Value>& args){_printf_helper(args, false);});
     add_function(isolate, global_template, "printfln",  [](const v8::FunctionCallbackInfo<v8::Value>& args){_printf_helper(args, true);});
 #endif
     add_function(isolate, global_template, "print",    [](const v8::FunctionCallbackInfo<v8::Value>& args){_print_helper(args, false);});
     add_function(isolate, global_template, "println",  [](const v8::FunctionCallbackInfo<v8::Value>& args){_print_helper(args, true);});
     add_function(isolate, global_template, "printobj", [](const v8::FunctionCallbackInfo<v8::Value>& args){printobj(args);});
 }
template<class CLASS , class R , class... Args> std::function<R(Args...)> bind (CLASS & object, R(CLASS::*)(Args...) method)
Helper function to create a Bind object using type deduction and wrap it in a std::function object.
Definition at line 368 of file v8_toolbox.hpp.
Referenced by V8ClassWrapper< T >::add_method().
 {
     return std::function<R(Args...)>(Bind<CLASS, R(CLASS::*)(Args...)>(object, method));
 }
template<class CALLABLE > void scoped_run (v8::Isolate * isolate, CALLABLE callable)
Helper function to run the callable inside contexts. If the isolate is currently inside a context, it will use that context automatically otherwise no context::scope will be created
Definition at line 380 of file v8_toolbox.hpp.
 {
     v8::Isolate::Scope isolate_scope(isolate);
     v8::HandleScope handle_scope(isolate);
     if (isolate->InContext()) {
         auto context = isolate->GetCurrentContext();
         v8::Context::Scope context_scope(context);
         callable();
     } else {
         callable();
     }
 }
template<class CALLABLE > void scoped_run (v8::Isolate * isolate, v8::Local< v8::Context > context, CALLABLE callable)
Helper function to run the callable inside contexts. This version is good when the isolate isn't currently within a context but a context has been created to be used
Definition at line 400 of file v8_toolbox.hpp.
 {
     v8::Isolate::Scope isolate_scope(isolate);
     v8::HandleScope handle_scope(isolate);
     v8::Context::Scope context_scope(context);
     callable();
 }